package workspaces

var PERM_ROOT_PASSPORTS = "root/passports"
var PERM_ROOT_PASSPORTS_DELETE = "root/passports/delete"
var PERM_ROOT_PASSPORTS_CREATE = "root/passports/create"
var PERM_ROOT_PASSPORTS_ADD = "root/passports/add"
var PERM_ROOT_PASSPORTS_ADD_EMAIL = "root/passports/add/email"
var PERM_ROOT_PASSPORTS_ADD_USERNAME = "root/passports/add/username"
var PERM_ROOT_PASSPORTS_ADD_PHONE = "root/passports/add/phone"

var ALL_PASSPORTS_PERMISSIONS = []string{
	PERM_ROOT_PASSPORTS,
	PERM_ROOT_PASSPORTS_DELETE,
	PERM_ROOT_PASSPORTS_CREATE,
	PERM_ROOT_PASSPORTS_ADD,
	PERM_ROOT_PASSPORTS_ADD_EMAIL,
	PERM_ROOT_PASSPORTS_ADD_USERNAME,
	PERM_ROOT_PASSPORTS_ADD_PHONE,
}
