package workspaces

// var PERM_ROOT_WORKSPACES = "root/workspaces"
// var PERM_ROOT_WORKSPACES_ROLE = "root/workspaces/role"
// var PERM_ROOT_WORKSPACES_ROLE_CREATE = "root/workspaces/role/create"
// var PERM_ROOT_WORKSPACES_ROLE_QUERY = "root/workspaces/role/query"
// var PERM_ROOT_WORKSPACES_ROLE_ASSIGN = "root/workspaces/role/assign"
// var PERM_ROOT_WORKSPACES_ROLE_DELETE = "root/workspaces/role/delete"
// var PERM_ROOT_WORKSPACES_ROLE_DELETE_EDIT = "root/workspaces/role/delete/edit"
// var PERM_ROOT_WORKSPACES_ROLE_DELETE_EDIT_TITLE = "root/workspaces/role/delete/edit/title"
// var PERM_ROOT_WORKSPACES_ROLE_DELETE_EDIT_LEVEL = "root/workspaces/role/delete/edit/level"
// var PERM_ROOT_WORKSPACES_USER = "root/workspaces/user"
// var PERM_ROOT_WORKSPACES_CONFIG = "root/workspaces/config"
// var PERM_ROOT_WORKSPACES_USER_CREATE = "root/workspaces/user/create"
// var PERM_ROOT_WORKSPACES_USER_QUERY = "root/workspaces/user/query"
// var PERM_ROOT_WORKSPACES_USER_ASSIGN = "root/workspaces/user/assign"
// var PERM_ROOT_WORKSPACES_USER_DELETE = "root/workspaces/user/delete"
// var PERM_ROOT_WORKSPACES_USER_DELETE_EDIT = "root/workspaces/user/delete/edit"
// var PERM_ROOT_WORKSPACES_INVITE = "root/workspaces/invite"
// var PERM_ROOT_WORKSPACES_VIEW_INVITES = "root/workspaces/view_invites"
// var PERM_ROOT_WORKSPACES_SUB_WORKSPACE = "root/workspaces/subworkspaces"
// var PERM_ROOT_WORKSPACES_DELETE = "root/workspaces/delete"
// var PERM_ROOT_BROWSE_CAPABILITIES = "root/capabilities"

// var ALL_WORKSPACES_PERMISSIONS = []string{
// 	PERM_ROOT_WORKSPACES,
// 	PERM_ROOT_WORKSPACES_ROLE,
// 	PERM_ROOT_WORKSPACES_ROLE_CREATE,
// 	PERM_ROOT_WORKSPACES_ROLE_QUERY,
// 	PERM_ROOT_WORKSPACES_ROLE_ASSIGN,
// 	PERM_ROOT_WORKSPACES_ROLE_DELETE,
// 	PERM_ROOT_WORKSPACES_ROLE_DELETE_EDIT,
// 	PERM_ROOT_WORKSPACES_ROLE_DELETE_EDIT_TITLE,
// 	PERM_ROOT_WORKSPACES_ROLE_DELETE_EDIT_LEVEL,
// 	PERM_ROOT_WORKSPACES_CONFIG,
// 	PERM_ROOT_WORKSPACES_SUB_WORKSPACE,
// 	PERM_ROOT_WORKSPACES_INVITE,
// 	PERM_ROOT_WORKSPACES_VIEW_INVITES,
// 	PERM_ROOT_WORKSPACES_DELETE,
// 	PERM_ROOT_WORKSPACES_USER,
// 	PERM_ROOT_WORKSPACES_USER_CREATE,
// 	PERM_ROOT_WORKSPACES_USER_QUERY,
// 	PERM_ROOT_WORKSPACES_USER_ASSIGN,
// 	PERM_ROOT_WORKSPACES_USER_DELETE,
// 	PERM_ROOT_WORKSPACES_USER_DELETE_EDIT,
// 	PERM_ROOT_BROWSE_CAPABILITIES,
// }
