/**
 * Fields for entity. Use this when creating forms in React/Angular,
 * instead of giving string to each one, use it from here, so in case of
 * updating any fields you don't loose it.
 */

export const ActivationKeyEntityFields = {
  visibility: "visibility",
  workspaceId: "workspaceId",
  linkerId: "linkerId",
  parentId: "parentId",
  parent: "parent",
  parent$: "parent",
  uniqueId: "uniqueId",
  userId: "userId",
  series: "series",
  used: "used",
  planId: "planId",
  plan: {
    visibility: "plan.visibility",
    workspaceId: "plan.workspaceId",
    linkerId: "plan.linkerId",
    parentId: "plan.parentId",
    parent: "plan.parent",
    parent$: "parent",
    uniqueId: "plan.uniqueId",
    userId: "plan.userId",
    translations: "plan.translations",
    name: "plan.name",
    duration: "plan.duration",
    productId: "plan.productId",
    product: {
      visibility: "plan.product.visibility",
      workspaceId: "plan.product.workspaceId",
      linkerId: "plan.product.linkerId",
      parentId: "plan.product.parentId",
      parent: "plan.product.parent",
      parent$: "parent",
      uniqueId: "plan.product.uniqueId",
      userId: "plan.product.userId",
      translations: "plan.product.translations",
      name: "plan.product.name",
      "-": "plan.product.-",
      publicKey: "plan.product.publicKey",
      rank: "plan.product.rank",
      updated: "plan.product.updated",
      created: "plan.product.created",
      createdFormatted: "plan.product.createdFormatted",
      updatedFormatted: "plan.product.updatedFormatted",
    },
    product$: "product",
    priceTagId: "plan.priceTagId",
    priceTag: {
      visibility: "plan.priceTag.visibility",
      workspaceId: "plan.priceTag.workspaceId",
      linkerId: "plan.priceTag.linkerId",
      parentId: "plan.priceTag.parentId",
      parent: "plan.priceTag.parent",
      parent$: "parent",
      uniqueId: "plan.priceTag.uniqueId",
      userId: "plan.priceTag.userId",
      variations: "plan.priceTag.variations",
      rank: "plan.priceTag.rank",
      updated: "plan.priceTag.updated",
      created: "plan.priceTag.created",
      createdFormatted: "plan.priceTag.createdFormatted",
      updatedFormatted: "plan.priceTag.updatedFormatted",
    },
    priceTag$: "priceTag",
    permissions: "plan.permissions",
    rank: "plan.rank",
    updated: "plan.updated",
    created: "plan.created",
    createdFormatted: "plan.createdFormatted",
    updatedFormatted: "plan.updatedFormatted",
  },
  plan$: "plan",
  rank: "rank",
  updated: "updated",
  created: "created",
  createdFormatted: "createdFormatted",
  updatedFormatted: "updatedFormatted",
};
