/**
 * Fields for entity. Use this when creating forms in React/Angular,
 * instead of giving string to each one, use it from here, so in case of
 * updating any fields you don't loose it.
 */

export const ProductPlanEntityFields = {
  visibility: "visibility",
  workspaceId: "workspaceId",
  linkerId: "linkerId",
  parentId: "parentId",
  parent: "parent",
  parent$: "parent",
  uniqueId: "uniqueId",
  userId: "userId",
  translations: "translations",
  name: "name",
  duration: "duration",
  productId: "productId",
  product: {
    visibility: "product.visibility",
    workspaceId: "product.workspaceId",
    linkerId: "product.linkerId",
    parentId: "product.parentId",
    parent: "product.parent",
    parent$: "parent",
    uniqueId: "product.uniqueId",
    userId: "product.userId",
    translations: "product.translations",
    name: "product.name",
    "-": "product.-",
    publicKey: "product.publicKey",
    rank: "product.rank",
    updated: "product.updated",
    created: "product.created",
    createdFormatted: "product.createdFormatted",
    updatedFormatted: "product.updatedFormatted",
  },
  product$: "product",
  priceTagId: "priceTagId",
  priceTag: {
    visibility: "priceTag.visibility",
    workspaceId: "priceTag.workspaceId",
    linkerId: "priceTag.linkerId",
    parentId: "priceTag.parentId",
    parent: "priceTag.parent",
    parent$: "parent",
    uniqueId: "priceTag.uniqueId",
    userId: "priceTag.userId",
    variations: "priceTag.variations",
    rank: "priceTag.rank",
    updated: "priceTag.updated",
    created: "priceTag.created",
    createdFormatted: "priceTag.createdFormatted",
    updatedFormatted: "priceTag.updatedFormatted",
  },
  priceTag$: "priceTag",
  permissions: "permissions",
  rank: "rank",
  updated: "updated",
  created: "created",
  createdFormatted: "createdFormatted",
  updatedFormatted: "updatedFormatted",
};
