package storage

/*
*	Generated by fireback <no value>
*	Written by Ali Torabi.
*	Checkout the repository for licenses and contribution: https://github.com/torabian/fireback
 */
import (
	"time"

	"github.com/gin-gonic/gin"
	"github.com/torabian/fireback/modules/fireback"
	"github.com/torabian/fireback/modules/fireback/application"
	"github.com/torabian/fireback/modules/storage/migrations"
	migrationsmysql "github.com/torabian/fireback/modules/storage/migrations_mysql"
	migrationssqlite "github.com/torabian/fireback/modules/storage/migrations_sqlite"
	"github.com/urfave/cli/v3"
)

type StorageModuleConfig struct {
	// MountPoint, if set, prefixes both UploadsBasePath and
	// DownloadsBasePath, e.g. MountPoint "/api" with the default base paths
	// mounts "/api/files" and "/api/downloads". Slashes are normalized, so
	// it doesn't matter whether MountPoint/UploadsBasePath/DownloadsBasePath
	// have leading/trailing slashes or not - the joined result never has
	// missing or doubled-up slashes.
	MountPoint string

	// UploadsBasePath is where the tus protocol endpoints
	// (POST/HEAD/PATCH/GET/DELETE, see handler.go's Mount) are mounted.
	// Defaults to "/files".
	UploadsBasePath string

	// DownloadsBasePath is where the JSON metadata + range-capable download
	// endpoints (see download.go's MountDownloads) are mounted. Defaults to
	// "/downloads".
	DownloadsBasePath string

	// ReaperInterval is how often SweepOrphaned runs in the background to
	// delete uploads nothing has claimed. Defaults to 1 hour. A negative
	// value disables the reaper entirely.
	ReaperInterval time.Duration

	// UnclaimedTTL/IncompleteTTL feed SweepOrphaned - see its docs in
	// reaper.go. Both default to 24h.
	UnclaimedTTL  time.Duration
	IncompleteTTL time.Duration

	// DisableUploadsMount, if true, skips mounting the tus upload endpoints
	// (Mount: POST/HEAD/PATCH/GET/DELETE at UploadsBasePath) entirely.
	// Useful for a deployment that only ever writes uploads out-of-band (via
	// Admin.UploadFile / the CLI, see Cli.go) and wants no public write
	// endpoint at all. The reaper and download endpoints are unaffected.
	DisableUploadsMount bool

	// DisableDownloadsMount, if true, skips mounting the read-only download
	// endpoints (MountDownloads: JSON metadata + ranged /raw at
	// DownloadsBasePath) entirely. Useful when an app wants to serve files
	// through its own signed-URL/proxy/CDN layer instead of exposing this
	// module's download routes directly.
	DisableDownloadsMount bool

	// Authenticate resolves an incoming request's identity - typically by
	// reading its Authorization header - into an AuthContext. It's the
	// single place fileupload looks up who's making a request: Mount and
	// MountDownloads both call it on every request, and its result is what
	// gets persisted per upload (see AuthContext, FileRecord) and passed to
	// Quota.
	//
	// Leave nil to disable authentication entirely: every request is
	// treated as Anonymous - no owner is recorded, Quota is never
	// consulted, and every upload is readable/writable by anyone. That's
	// this module's behavior from before this mechanism existed.
	//
	// Inside a fireback app, StorageModuleSetup defaults this to
	// resolving the same bearer token fireback's own
	// SecurityModel/WithAuthorization middleware resolves elsewhere in the
	// app (via fireback.WithAuthorizationPure) - see defaultAuthenticate in
	// webserver.go. Set your own to customize, e.g. to also require a
	// specific permission, or to plug in an entirely different auth scheme.
	Authenticate func(c *gin.Context) (AuthContext, error)

	// Quota returns the maximum total bytes auth is allowed to have stored
	// across all of their uploads combined. It's checked once per upload
	// creation, against the size the client declares up front (its
	// Upload-Length header) plus whatever auth already has stored -
	// uploads that would cross the limit are rejected before a single byte
	// is written.
	//
	// Defaults to a flat DefaultQuotaBytes (2 GiB) per user if nil. Return
	// a negative number for "no limit" for a given identity, e.g. based on
	// AccessLevel - this is the extension point for per-user/per-plan
	// quotas. Never consulted for Anonymous auth (Authenticate is nil, or
	// it resolved no UserId).
	Quota func(auth AuthContext) int64
}

func StorageModuleSetup(cfg *StorageModuleConfig) *application.ModuleProvider {
	module := &application.ModuleProvider{
		Name: "storage",
		CliHandlers: []*cli.Command{
			{
				Name: "storage",
				Commands: []*cli.Command{
					deleteCmd,
					usageCmd,
					uploadCmd,
				},
			},
		},
		// Mounts the tus upload endpoint, the read/download endpoints, and
		// starts the background orphan reaper - see mountOnFirebackApp in
		// webserver.go. Runs once when the gin server for this app is set
		// up; the reaper itself is non-blocking (StartReaper spawns its own
		// goroutine), so this hook returns as soon as the routes are
		// registered.
		GinWebServerInitHooks: []func(g *gin.RouterGroup, x *application.Application) error{
			func(g *gin.RouterGroup, x *application.Application) error {
				return mountOnFirebackApp(g, cfg)
			},
		},
	}

	// Goose framework directory, which would contain sql files for that
	// framework, which would be running near automigration of gorm - picked
	// per-vendor since the three schemas' SQL isn't portable between each
	// other (see migrations_sqlite/00001_create_tus_uploads.sql's own
	// comment). Not set for any other vendor - matches
	// mountOnFirebackApp/OpenStoreForFireback's own silent no-op for
	// anything this module doesn't back itself with.
	//
	// fireback.LoadConfiguration() is safe to call this early (before
	// CommonHeadlessAppStart's own env loading has necessarily run yet,
	// since ModuleProvider construction typically happens in main.go before
	// that) - same self-sufficiency NewPgxPool's own doc comment relies on.
	vendor, _ := fireback.GetDatabaseDsn(fireback.LoadConfiguration())
	switch vendor {
	case "postgres":
		module.GoMigrateDirectory = &migrations.MigrationsFs
	case "sqlite":
		module.GoMigrateDirectory = &migrationssqlite.MigrationsFs
	case "mysql", "mariadb":
		module.GoMigrateDirectory = &migrationsmysql.MigrationsFs
	}

	return module
}
