package izaTheme

/*
*	Generated by fireback 1.2.5
*	Written by Ali Torabi.
*	Checkout the repository for licenses and contribution: https://github.com/torabian/fireback
 */
import (
	"reflect"

	"github.com/gin-gonic/gin"
	"github.com/torabian/fireback/modules/fireback"
	"github.com/urfave/cli"
)

// using shared actions here
// / For emi, we also need to print the handlers, and also print security model, which is a part of Fireback
// / and not available in Emi (won't be)
var HomePageImpl func(c HomePageActionRequest, query fireback.QueryDSL) (*HomePageActionResponse, error) = nil
var HomePageSecurityModel *fireback.SecurityModel = nil

// This can be both used as cli and http
var HomePageActionDef fireback.Module3Action = fireback.Module3Action{
	CliName:       HomePageActionMeta().CliName,
	Description:   HomePageActionMeta().Description,
	Name:          HomePageActionMeta().Name,
	Method:        HomePageActionMeta().Method,
	Url:           HomePageActionMeta().URL,
	SecurityModel: HomePageSecurityModel,
	Handlers: []gin.HandlerFunc{
		func(m *gin.Context) {
			req := HomePageActionRequest{
				QueryParams: m.Request.URL.Query(),
				Headers:     m.Request.Header,
				GinCtx:      m,
			}
			var query fireback.QueryDSL
			query = fireback.ExtractQueryDslFromGinContext(m)
			resp, err := HomePageImpl(req, query)
			fireback.WriteActionResponseToGin(m, resp, err)
		},
	},
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, HomePageSecurityModel)
		req := HomePageActionRequest{}
		resp, err := HomePageImpl(req, query)
		fireback.HandleActionInCli2(c, resp, err, map[string]map[string]string{})
		return nil
	},
}
var ProductSingleScreenImpl func(c ProductSingleScreenActionRequest, query fireback.QueryDSL) (*ProductSingleScreenActionResponse, error) = nil
var ProductSingleScreenSecurityModel *fireback.SecurityModel = nil

// This can be both used as cli and http
var ProductSingleScreenActionDef fireback.Module3Action = fireback.Module3Action{
	CliName:       ProductSingleScreenActionMeta().CliName,
	Description:   ProductSingleScreenActionMeta().Description,
	Name:          ProductSingleScreenActionMeta().Name,
	Method:        ProductSingleScreenActionMeta().Method,
	Url:           ProductSingleScreenActionMeta().URL,
	SecurityModel: ProductSingleScreenSecurityModel,
	Handlers: []gin.HandlerFunc{
		func(m *gin.Context) {
			req := ProductSingleScreenActionRequest{
				QueryParams: m.Request.URL.Query(),
				Headers:     m.Request.Header,
				GinCtx:      m,
			}
			var query fireback.QueryDSL
			query = fireback.ExtractQueryDslFromGinContext(m)
			resp, err := ProductSingleScreenImpl(req, query)
			fireback.WriteActionResponseToGin(m, resp, err)
		},
	},
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, ProductSingleScreenSecurityModel)
		req := ProductSingleScreenActionRequest{}
		resp, err := ProductSingleScreenImpl(req, query)
		fireback.HandleActionInCli2(c, resp, err, map[string]map[string]string{})
		return nil
	},
}

func IzaThemeCustomActions() []fireback.Module3Action {
	routes := []fireback.Module3Action{
		//// Let's add actions for emi acts
		HomePageActionDef,
		ProductSingleScreenActionDef,
		/// End for emi actions
	}
	return routes
}

var IzaThemeCustomActionsCli = []cli.Command{}

// Only to include some headers
func IzaThemeJsonInclude() {
	str4 := reflect.ValueOf(nil)
	_ = str4
}

// Use the actions bundle for ease and provide it to the ModuleProvider
// and it would gather all actions in the module level
var IzaThemeCliActionsBundle = &fireback.CliActionsBundle{
	Name:  "izaTheme",
	Usage: ``,
	// Here we will include entities actions, as well as module level actions
	Subcommands: cli.Commands{
		HomePageActionDef.ToCli(),
		ProductSingleScreenActionDef.ToCli(),
	},
}

func GetIzaThemeActionsBundle() *fireback.ModuleActionsBundle {
	return &fireback.ModuleActionsBundle{
		Actions:   IzaThemeCustomActions(),
		CliAction: IzaThemeCliActionsBundle,
	}
}
func GetIzaThemeActionsCli() []cli.Command {
	return IzaThemeCustomActionsCli
}
