package geo

var GEOCITY_EVENT_CREATED = "geoCity.created"
var GEOCITY_EVENT_UPDATED = "geoCity.updated"
var GEOCITY_EVENT_DELETED = "geoCity.deleted"

var GEOCITY_EVENTS = []string{
	GEOCITY_EVENT_CREATED,
	GEOCITY_EVENT_UPDATED,
	GEOCITY_EVENT_DELETED,
}
