package geo

var PERM_ROOT_GEOLOCATION_DELETE = "root/geolocation/delete"
var PERM_ROOT_GEOLOCATION_CREATE = "root/geolocation/create"
var PERM_ROOT_GEOLOCATION_UPDATE = "root/geolocation/update"
var PERM_ROOT_GEOLOCATION_QUERY = "root/geolocation/query"
var PERM_ROOT_GEOLOCATION = "root/geolocation"

var ALL_GEOLOCATION_PERMISSIONS = []string{
	PERM_ROOT_GEOLOCATION_DELETE,
	PERM_ROOT_GEOLOCATION_CREATE,
	PERM_ROOT_GEOLOCATION_UPDATE,
	PERM_ROOT_GEOLOCATION_QUERY,
	PERM_ROOT_GEOLOCATION,
}
