package geo

var GEOLOCATIONTYPE_EVENT_CREATED = "geoLocationType.created"
var GEOLOCATIONTYPE_EVENT_UPDATED = "geoLocationType.updated"
var GEOLOCATIONTYPE_EVENT_DELETED = "geoLocationType.deleted"

var GEOLOCATIONTYPE_EVENTS = []string{
	GEOLOCATIONTYPE_EVENT_CREATED,
	GEOLOCATIONTYPE_EVENT_UPDATED,
	GEOLOCATIONTYPE_EVENT_DELETED,
}
