package geo

var GEOLOCATION_EVENT_CREATED = "geoLocation.created"
var GEOLOCATION_EVENT_UPDATED = "geoLocation.updated"
var GEOLOCATION_EVENT_DELETED = "geoLocation.deleted"

var GEOLOCATION_EVENTS = []string{
	GEOLOCATION_EVENT_CREATED,
	GEOLOCATION_EVENT_UPDATED,
	GEOLOCATION_EVENT_DELETED,
}
