package geo

var PERM_ROOT_GEOLOCATIONTYPE_DELETE = "root/geolocationtype/delete"
var PERM_ROOT_GEOLOCATIONTYPE_CREATE = "root/geolocationtype/create"
var PERM_ROOT_GEOLOCATIONTYPE_UPDATE = "root/geolocationtype/update"
var PERM_ROOT_GEOLOCATIONTYPE_QUERY = "root/geolocationtype/query"
var PERM_ROOT_GEOLOCATIONTYPE = "root/geolocationtype"

var ALL_GEOLOCATIONTYPE_PERMISSIONS = []string{
	PERM_ROOT_GEOLOCATIONTYPE_DELETE,
	PERM_ROOT_GEOLOCATIONTYPE_CREATE,
	PERM_ROOT_GEOLOCATIONTYPE_UPDATE,
	PERM_ROOT_GEOLOCATIONTYPE_QUERY,
	PERM_ROOT_GEOLOCATIONTYPE,
}
