package geo

var GEOPROVINCE_EVENT_CREATED = "geoProvince.created"
var GEOPROVINCE_EVENT_UPDATED = "geoProvince.updated"
var GEOPROVINCE_EVENT_DELETED = "geoProvince.deleted"

var GEOPROVINCE_EVENTS = []string{
	GEOPROVINCE_EVENT_CREATED,
	GEOPROVINCE_EVENT_UPDATED,
	GEOPROVINCE_EVENT_DELETED,
}
