package geo

var PERM_ROOT_GEOPROVINCE_DELETE = "root/geoprovince/delete"
var PERM_ROOT_GEOPROVINCE_CREATE = "root/geoprovince/create"
var PERM_ROOT_GEOPROVINCE_UPDATE = "root/geoprovince/update"
var PERM_ROOT_GEOPROVINCE_QUERY = "root/geoprovince/query"
var PERM_ROOT_GEOPROVINCE = "root/geoprovince"

var ALL_GEOPROVINCE_PERMISSIONS = []string{
	PERM_ROOT_GEOPROVINCE_DELETE,
	PERM_ROOT_GEOPROVINCE_CREATE,
	PERM_ROOT_GEOPROVINCE_UPDATE,
	PERM_ROOT_GEOPROVINCE_QUERY,
	PERM_ROOT_GEOPROVINCE,
}
