package geo

var GEOSTATE_EVENT_CREATED = "geoState.created"
var GEOSTATE_EVENT_UPDATED = "geoState.updated"
var GEOSTATE_EVENT_DELETED = "geoState.deleted"

var GEOSTATE_EVENTS = []string{
	GEOSTATE_EVENT_CREATED,
	GEOSTATE_EVENT_UPDATED,
	GEOSTATE_EVENT_DELETED,
}
