package geo

var PERM_ROOT_GEOSTATE_DELETE = "root/geostate/delete"
var PERM_ROOT_GEOSTATE_CREATE = "root/geostate/create"
var PERM_ROOT_GEOSTATE_UPDATE = "root/geostate/update"
var PERM_ROOT_GEOSTATE_QUERY = "root/geostate/query"
var PERM_ROOT_GEOSTATE = "root/geostate"

var ALL_GEOSTATE_PERMISSIONS = []string{
	PERM_ROOT_GEOSTATE_DELETE,
	PERM_ROOT_GEOSTATE_CREATE,
	PERM_ROOT_GEOSTATE_UPDATE,
	PERM_ROOT_GEOSTATE_QUERY,
	PERM_ROOT_GEOSTATE,
}
