package geo

var PERM_ROOT_LOCATIONDATA_DELETE = "root/locationdata/delete"
var PERM_ROOT_LOCATIONDATA_CREATE = "root/locationdata/create"
var PERM_ROOT_LOCATIONDATA_UPDATE = "root/locationdata/update"
var PERM_ROOT_LOCATIONDATA_QUERY = "root/locationdata/query"
var PERM_ROOT_LOCATIONDATA = "root/locationdata"

var ALL_LOCATIONDATA_PERMISSIONS = []string{
	PERM_ROOT_LOCATIONDATA_DELETE,
	PERM_ROOT_LOCATIONDATA_CREATE,
	PERM_ROOT_LOCATIONDATA_UPDATE,
	PERM_ROOT_LOCATIONDATA_QUERY,
	PERM_ROOT_LOCATIONDATA,
}
