package geo

var LOCATIONDATA_EVENT_CREATED = "locationData.created"
var LOCATIONDATA_EVENT_UPDATED = "locationData.updated"
var LOCATIONDATA_EVENT_DELETED = "locationData.deleted"

var LOCATIONDATA_EVENTS = []string{
	LOCATIONDATA_EVENT_CREATED,
	LOCATIONDATA_EVENT_UPDATED,
	LOCATIONDATA_EVENT_DELETED,
}
