/**
 * Fields for entity. Use this when creating forms in React/Angular,
 * instead of giving string to each one, use it from here, so in case of
 * updating any fields you don't loose it.
 */

export const NotificationConfigEntityFields = {
  visibility: "visibility",
  workspaceId: "workspaceId",
  linkerId: "linkerId",
  parentId: "parentId",
  parent: "parent",
  parent$: "parent",
  uniqueId: "uniqueId",
  userId: "userId",
  cascadeToSubWorkspaces: "cascadeToSubWorkspaces",
  forcedCascadeEmailProvider: "forcedCascadeEmailProvider",
  generalEmailProviderId: "generalEmailProviderId",
  generalEmailProvider: {
    visibility: "generalEmailProvider.visibility",
    workspaceId: "generalEmailProvider.workspaceId",
    linkerId: "generalEmailProvider.linkerId",
    parentId: "generalEmailProvider.parentId",
    parent: "generalEmailProvider.parent",
    parent$: "parent",
    uniqueId: "generalEmailProvider.uniqueId",
    userId: "generalEmailProvider.userId",
    type: "generalEmailProvider.type",
    apiKey: "generalEmailProvider.apiKey",
    rank: "generalEmailProvider.rank",
    updated: "generalEmailProvider.updated",
    created: "generalEmailProvider.created",
    createdFormatted: "generalEmailProvider.createdFormatted",
    updatedFormatted: "generalEmailProvider.updatedFormatted",
  },
  generalEmailProvider$: "generalEmailProvider",
  generalGsmProviderId: "generalGsmProviderId",
  generalGsmProvider: {
    visibility: "generalGsmProvider.visibility",
    workspaceId: "generalGsmProvider.workspaceId",
    linkerId: "generalGsmProvider.linkerId",
    parentId: "generalGsmProvider.parentId",
    parent: "generalGsmProvider.parent",
    parent$: "parent",
    uniqueId: "generalGsmProvider.uniqueId",
    userId: "generalGsmProvider.userId",
    apiKey: "generalGsmProvider.apiKey",
    mainSenderNumber: "generalGsmProvider.mainSenderNumber",
    type: "generalGsmProvider.type",
    invokeUrl: "generalGsmProvider.invokeUrl",
    invokeBody: "generalGsmProvider.invokeBody",
    rank: "generalGsmProvider.rank",
    updated: "generalGsmProvider.updated",
    created: "generalGsmProvider.created",
    createdFormatted: "generalGsmProvider.createdFormatted",
    updatedFormatted: "generalGsmProvider.updatedFormatted",
  },
  generalGsmProvider$: "generalGsmProvider",
  inviteToWorkspaceContent: "inviteToWorkspaceContent",
  inviteToWorkspaceContentExcerpt: "inviteToWorkspaceContentExcerpt",
  inviteToWorkspaceContentDefault: "inviteToWorkspaceContentDefault",
  inviteToWorkspaceContentDefaultExcerpt:
    "inviteToWorkspaceContentDefaultExcerpt",
  inviteToWorkspaceTitle: "inviteToWorkspaceTitle",
  inviteToWorkspaceTitleDefault: "inviteToWorkspaceTitleDefault",
  inviteToWorkspaceSenderId: "inviteToWorkspaceSenderId",
  inviteToWorkspaceSender: {
    visibility: "inviteToWorkspaceSender.visibility",
    workspaceId: "inviteToWorkspaceSender.workspaceId",
    linkerId: "inviteToWorkspaceSender.linkerId",
    parentId: "inviteToWorkspaceSender.parentId",
    parent: "inviteToWorkspaceSender.parent",
    parent$: "parent",
    uniqueId: "inviteToWorkspaceSender.uniqueId",
    userId: "inviteToWorkspaceSender.userId",
    fromName: "inviteToWorkspaceSender.fromName",
    fromEmailAddress: "inviteToWorkspaceSender.fromEmailAddress",
    replyTo: "inviteToWorkspaceSender.replyTo",
    nickName: "inviteToWorkspaceSender.nickName",
    rank: "inviteToWorkspaceSender.rank",
    updated: "inviteToWorkspaceSender.updated",
    created: "inviteToWorkspaceSender.created",
    createdFormatted: "inviteToWorkspaceSender.createdFormatted",
    updatedFormatted: "inviteToWorkspaceSender.updatedFormatted",
  },
  inviteToWorkspaceSender$: "inviteToWorkspaceSender",
  forgetPasswordContent: "forgetPasswordContent",
  forgetPasswordContentExcerpt: "forgetPasswordContentExcerpt",
  forgetPasswordContentDefault: "forgetPasswordContentDefault",
  forgetPasswordContentDefaultExcerpt: "forgetPasswordContentDefaultExcerpt",
  forgetPasswordTitle: "forgetPasswordTitle",
  forgetPasswordTitleDefault: "forgetPasswordTitleDefault",
  forgetPasswordSenderId: "forgetPasswordSenderId",
  forgetPasswordSender: {
    visibility: "forgetPasswordSender.visibility",
    workspaceId: "forgetPasswordSender.workspaceId",
    linkerId: "forgetPasswordSender.linkerId",
    parentId: "forgetPasswordSender.parentId",
    parent: "forgetPasswordSender.parent",
    parent$: "parent",
    uniqueId: "forgetPasswordSender.uniqueId",
    userId: "forgetPasswordSender.userId",
    fromName: "forgetPasswordSender.fromName",
    fromEmailAddress: "forgetPasswordSender.fromEmailAddress",
    replyTo: "forgetPasswordSender.replyTo",
    nickName: "forgetPasswordSender.nickName",
    rank: "forgetPasswordSender.rank",
    updated: "forgetPasswordSender.updated",
    created: "forgetPasswordSender.created",
    createdFormatted: "forgetPasswordSender.createdFormatted",
    updatedFormatted: "forgetPasswordSender.updatedFormatted",
  },
  forgetPasswordSender$: "forgetPasswordSender",
  acceptLanguage: "acceptLanguage",
  acceptLanguageExcerpt: "acceptLanguageExcerpt",
  confirmEmailSenderId: "confirmEmailSenderId",
  confirmEmailSender: {
    visibility: "confirmEmailSender.visibility",
    workspaceId: "confirmEmailSender.workspaceId",
    linkerId: "confirmEmailSender.linkerId",
    parentId: "confirmEmailSender.parentId",
    parent: "confirmEmailSender.parent",
    parent$: "parent",
    uniqueId: "confirmEmailSender.uniqueId",
    userId: "confirmEmailSender.userId",
    fromName: "confirmEmailSender.fromName",
    fromEmailAddress: "confirmEmailSender.fromEmailAddress",
    replyTo: "confirmEmailSender.replyTo",
    nickName: "confirmEmailSender.nickName",
    rank: "confirmEmailSender.rank",
    updated: "confirmEmailSender.updated",
    created: "confirmEmailSender.created",
    createdFormatted: "confirmEmailSender.createdFormatted",
    updatedFormatted: "confirmEmailSender.updatedFormatted",
  },
  confirmEmailSender$: "confirmEmailSender",
  confirmEmailContent: "confirmEmailContent",
  confirmEmailContentExcerpt: "confirmEmailContentExcerpt",
  confirmEmailContentDefault: "confirmEmailContentDefault",
  confirmEmailContentDefaultExcerpt: "confirmEmailContentDefaultExcerpt",
  confirmEmailTitle: "confirmEmailTitle",
  confirmEmailTitleDefault: "confirmEmailTitleDefault",
  rank: "rank",
  updated: "updated",
  created: "created",
  createdFormatted: "createdFormatted",
  updatedFormatted: "updatedFormatted",
};
