package abac

import (
	"bytes"
	"encoding/json"
	"github.com/gin-gonic/gin"
	"github.com/torabian/emi/emigo"
	"github.com/urfave/cli/v3"
	"io"
	"net/http"
	"net/url"
)

/**
* Action to communicate with the action ConfirmClassicPassportTotpAction
 */
/*
Here is a quick function implementation to make your life easier:
// Actual implementation of ConfirmClassicPassportTotpAction
func ConfirmClassicPassportTotpAction(c ConfirmClassicPassportTotpActionRequest) (*ConfirmClassicPassportTotpActionResponse, error) {
	return &ConfirmClassicPassportTotpActionResponse{
		// Payload is an interface. Use it at carefully.
	}, nil
}
*/
func ConfirmClassicPassportTotpActionMeta() struct {
	Name        string
	CliName     string
	URL         string
	Method      string
	Description string
} {
	return struct {
		Name        string
		CliName     string
		URL         string
		Method      string
		Description string
	}{
		Name:        "ConfirmClassicPassportTotpAction",
		CliName:     "confirm-classic-passport-totp-action",
		URL:         "/passport/totp/confirm",
		Method:      "POST",
		Description: `When user requires to setup the totp for an specifc passport, they can use this endpoint to confirm it.`,
	}
}
func GetConfirmClassicPassportTotpActionReqCliFlags(prefix string) []emigo.CliFlag {
	return []emigo.CliFlag{
		{
			Name:        prefix + "value",
			Type:        "string",
			Description: "Passport value, email or phone number which is already successfully registered.",
		},
		{
			Name:        prefix + "password",
			Type:        "string",
			Description: "Password related to the passport. Totp is only available for passports with a password. Basically totp is protecting passport, not otp over email or sms.",
		},
		{
			Name:        prefix + "totp-code",
			Type:        "string",
			Description: "The totp code generated by authenticator such as google or microsft apps.",
		},
	}
}
func CastConfirmClassicPassportTotpActionReqFromCli(c emigo.CliCastable) ConfirmClassicPassportTotpActionReq {
	data := ConfirmClassicPassportTotpActionReq{}
	if c.IsSet("value") {
		data.Value = c.String("value")
	}
	if c.IsSet("password") {
		data.Password = c.String("password")
	}
	if c.IsSet("totp-code") {
		data.TotpCode = c.String("totp-code")
	}
	return data
}

// The base class definition for confirmClassicPassportTotpActionReq
type ConfirmClassicPassportTotpActionReq struct {
	// Passport value, email or phone number which is already successfully registered.
	Value string `json:"value" validate:"required" yaml:"value"`
	// Password related to the passport. Totp is only available for passports with a password. Basically totp is protecting passport, not otp over email or sms.
	Password string `json:"password" validate:"required" yaml:"password"`
	// The totp code generated by authenticator such as google or microsft apps.
	TotpCode string `json:"totpCode" validate:"required" yaml:"totpCode"`
}

func (x *ConfirmClassicPassportTotpActionReq) Json() string {
	if x != nil {
		str, _ := json.MarshalIndent(x, "", "  ")
		return string(str)
	}
	return ""
}
func GetConfirmClassicPassportTotpActionResCliFlags(prefix string) []emigo.CliFlag {
	return []emigo.CliFlag{
		{
			Name: prefix + "session",
			Type: "one",
		},
	}
}
func CastConfirmClassicPassportTotpActionResFromCli(c emigo.CliCastable) ConfirmClassicPassportTotpActionRes {
	data := ConfirmClassicPassportTotpActionRes{}
	return data
}

// The base class definition for confirmClassicPassportTotpActionRes
type ConfirmClassicPassportTotpActionRes struct {
	Session UserSessionDto `json:"session" yaml:"session"`
}

func (x *ConfirmClassicPassportTotpActionRes) Json() string {
	if x != nil {
		str, _ := json.MarshalIndent(x, "", "  ")
		return string(str)
	}
	return ""
}

type ConfirmClassicPassportTotpActionResponse struct {
	StatusCode int
	Headers    map[string]string
	Payload    interface{}
	// Do not manually fill this in. It has no effect. This is only useful when you are using
	// client code, and want to get access to the original response. When sending response from your
	// application it will be ignored.
	resp *http.Response
}

func (x *ConfirmClassicPassportTotpActionResponse) SetContentType(contentType string) *ConfirmClassicPassportTotpActionResponse {
	if x.Headers == nil {
		x.Headers = make(map[string]string)
	}
	x.Headers["Content-Type"] = contentType
	return x
}
func (x *ConfirmClassicPassportTotpActionResponse) AsStream(r io.Reader, contentType string) *ConfirmClassicPassportTotpActionResponse {
	x.Payload = r
	x.SetContentType(contentType)
	return x
}
func (x *ConfirmClassicPassportTotpActionResponse) AsJSON(payload any) *ConfirmClassicPassportTotpActionResponse {
	x.Payload = payload
	x.SetContentType("application/json")
	return x
}

// When the response is expected as documentation, you call this to get some type
// safety for the action which is happening.
func (x *ConfirmClassicPassportTotpActionResponse) WithIdeal(payload ConfirmClassicPassportTotpActionRes) *ConfirmClassicPassportTotpActionResponse {
	x.Payload = payload
	return x
}
func (x *ConfirmClassicPassportTotpActionResponse) AsHTML(payload string) *ConfirmClassicPassportTotpActionResponse {
	x.Payload = payload
	x.SetContentType("text/html; charset=utf-8")
	return x
}
func (x *ConfirmClassicPassportTotpActionResponse) AsBytes(payload []byte) *ConfirmClassicPassportTotpActionResponse {
	x.Payload = payload
	x.SetContentType("application/octet-stream")
	return x
}
func (x ConfirmClassicPassportTotpActionResponse) GetStatusCode() int {
	return x.StatusCode
}
func (x ConfirmClassicPassportTotpActionResponse) GetRespHeaders() map[string]string {
	return x.Headers
}
func (x ConfirmClassicPassportTotpActionResponse) GetPayload() interface{} {
	return x.Payload
}

// ConfirmClassicPassportTotpActionRaw registers a raw Gin route for the ConfirmClassicPassportTotpAction action.
// This gives the developer full control over middleware, handlers, and response handling.
func ConfirmClassicPassportTotpActionRaw(r *gin.Engine, handlers ...gin.HandlerFunc) {
	meta := ConfirmClassicPassportTotpActionMeta()
	r.Handle(meta.Method, meta.URL, handlers...)
}

type ConfirmClassicPassportTotpActionRequestSig = func(c ConfirmClassicPassportTotpActionRequest) (*ConfirmClassicPassportTotpActionResponse, error)

// ConfirmClassicPassportTotpActionHandler returns the HTTP method, route URL, and a typed Gin handler for the ConfirmClassicPassportTotpAction action.
// Developers implement their business logic as a function that receives a typed request object
// and returns either an *ActionResponse or nil. JSON marshalling, headers, and errors are handled automatically.
func ConfirmClassicPassportTotpActionHandler(
	handler ConfirmClassicPassportTotpActionRequestSig,
) (method, url string, h gin.HandlerFunc) {
	meta := ConfirmClassicPassportTotpActionMeta()
	return meta.Method, meta.URL, func(m *gin.Context) {
		var body ConfirmClassicPassportTotpActionReq
		if err := m.ShouldBindJSON(&body); err != nil {
			m.JSON(http.StatusBadRequest, gin.H{"error": "invalid JSON: " + err.Error()})
			return
		}
		// Build typed request wrapper
		req := ConfirmClassicPassportTotpActionRequest{
			Body:        body,
			QueryParams: m.Request.URL.Query(),
			Headers:     m.Request.Header,
			GinCtx:      m,
		}
		resp, err := handler(req)
		if err != nil {
			m.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
			return
		}
		// If the handler returned nil (and no error), it means the response was handled manually.
		if resp == nil {
			return
		}
		// Apply headers
		for k, v := range resp.Headers {
			m.Header(k, v)
		}
		// Apply status and payload
		status := resp.StatusCode
		if status == 0 {
			status = http.StatusOK
		}
		if resp.Payload != nil {
			m.JSON(status, resp.Payload)
		} else {
			m.Status(status)
		}
	}
}

// ConfirmClassicPassportTotpAction is a high-level convenience wrapper around ConfirmClassicPassportTotpActionHandler.
// It automatically constructs and registers the typed route on the Gin engine.
// Use this when you don't need custom middleware or route grouping.
func ConfirmClassicPassportTotpActionGin(r gin.IRoutes, handler ConfirmClassicPassportTotpActionRequestSig) {
	method, url, h := ConfirmClassicPassportTotpActionHandler(handler)
	r.Handle(method, url, h)
}

/**
 * Query parameters for ConfirmClassicPassportTotpAction
 */
// Query wrapper with private fields
type ConfirmClassicPassportTotpActionQuery struct {
	values url.Values
	mapped map[string]interface{}
	// Typesafe fields
}

func ConfirmClassicPassportTotpActionQueryFromString(rawQuery string) ConfirmClassicPassportTotpActionQuery {
	v := ConfirmClassicPassportTotpActionQuery{}
	values, _ := url.ParseQuery(rawQuery)
	mapped := map[string]interface{}{}
	if result, err := emigo.UnmarshalQs(rawQuery); err == nil {
		mapped = result
	}
	decoder, err := emigo.NewDecoder(&emigo.DecoderConfig{
		TagName:          "json", // reuse json tags
		WeaklyTypedInput: true,   // "1" -> int, "true" -> bool
		Result:           &v,
	})
	if err == nil {
		_ = decoder.Decode(mapped)
	}
	v.values = values
	v.mapped = mapped
	return v
}
func ConfirmClassicPassportTotpActionQueryFromGin(c *gin.Context) ConfirmClassicPassportTotpActionQuery {
	return ConfirmClassicPassportTotpActionQueryFromString(c.Request.URL.RawQuery)
}
func ConfirmClassicPassportTotpActionQueryFromHttp(r *http.Request) ConfirmClassicPassportTotpActionQuery {
	return ConfirmClassicPassportTotpActionQueryFromString(r.URL.RawQuery)
}
func (q ConfirmClassicPassportTotpActionQuery) Values() url.Values {
	return q.values
}
func (q ConfirmClassicPassportTotpActionQuery) Mapped() map[string]interface{} {
	return q.mapped
}
func (q *ConfirmClassicPassportTotpActionQuery) SetValues(v url.Values) {
	q.values = v
}
func (q *ConfirmClassicPassportTotpActionQuery) SetMapped(m map[string]interface{}) {
	q.mapped = m
}

type ConfirmClassicPassportTotpActionRequest struct {
	Body        ConfirmClassicPassportTotpActionReq
	QueryParams url.Values
	// Automatically casted headers, for purpose of typesafe headers in later versions
	Headers http.Header
	// Gin context for each request in case of a direct access requirement
	GinCtx *gin.Context
	// Urfave context, per each request
	CliCtx *cli.Command
	// Reference to the application instance, in such scenarios that entire
	// application is wrapped into a single struct that holds database connection,
	// routes, etc.
	Application interface{}
}

func (x ConfirmClassicPassportTotpActionRequest) IsGin() bool {
	return x.GinCtx != nil
}
func (x ConfirmClassicPassportTotpActionRequest) IsCli() bool {
	return x.CliCtx != nil
}

// type ConfirmClassicPassportTotpActionResult struct {
// /resp *http.Response
// /	Payload interface{}
// /}
func ConfirmClassicPassportTotpActionClientCreateUrl(
	req ConfirmClassicPassportTotpActionRequest,
	config *emigo.APIClient, // optional pre-built request
) (*url.URL, error) {
	meta := ConfirmClassicPassportTotpActionMeta()
	urlAddr := meta.URL
	urlAddr = config.BaseURL + urlAddr
	// Build final URL with query string
	u, err := url.Parse(urlAddr)
	if err != nil {
		return nil, err
	}
	// if UrlValues present, encode and append
	if len(req.QueryParams) > 0 {
		u.RawQuery = req.QueryParams.Encode()
	}
	return u, nil
}
func ConfirmClassicPassportTotpActionClientExecuteTyped(httpReq *http.Request) (*ConfirmClassicPassportTotpActionResponse, error) {
	resp, err := http.DefaultClient.Do(httpReq)
	if err != nil {
		return nil, err
	}
	// At this point, response is valid, and we need to return the results.
	var result ConfirmClassicPassportTotpActionResponse
	result.resp = resp
	defer resp.Body.Close()
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return &ConfirmClassicPassportTotpActionResponse{Payload: result}, err
	}
	if err := json.Unmarshal(respBody, &result.Payload); err != nil {
		return &ConfirmClassicPassportTotpActionResponse{Payload: result}, err
	}
	return &ConfirmClassicPassportTotpActionResponse{Payload: result}, nil
}
func ConfirmClassicPassportTotpActionClientBuildRequest(req ConfirmClassicPassportTotpActionRequest, reqUrl *url.URL, config *emigo.APIClient) (*http.Request, error) {
	meta := ConfirmClassicPassportTotpActionMeta()
	bodyBytes, err := json.Marshal(req.Body)
	if err != nil {
		return nil, err
	}
	httpReq, err := http.NewRequest(meta.Method, reqUrl.String(), bytes.NewReader(bodyBytes))
	if err != nil {
		return nil, err
	}
	httpReq.Header = make(http.Header)
	// copy defaults
	for k, v := range config.Headers {
		for _, vv := range v {
			httpReq.Header.Add(k, vv)
		}
	}
	// override with request-specific headers
	for k, v := range req.Headers {
		httpReq.Header.Del(k) // ensure override, not duplicate
		for _, vv := range v {
			httpReq.Header.Add(k, vv)
		}
	}
	return httpReq, nil
}
func ConfirmClassicPassportTotpActionCall(
	req ConfirmClassicPassportTotpActionRequest,
	config *emigo.APIClient, // optional pre-built request
) (*ConfirmClassicPassportTotpActionResponse, error) {
	// This function intentionally is split into 3 different sections, so in case
	// of some modifications that we did not anticipate, at least a part would become quite useful.
	// first we create url, apply all path parameters, query params, etc
	u, err := ConfirmClassicPassportTotpActionClientCreateUrl(req, config)
	if err != nil {
		return nil, err
	}
	// We create the request from the body in second stage
	r, err := ConfirmClassicPassportTotpActionClientBuildRequest(req, u, config)
	if err != nil {
		return nil, err
	}
	// This one would execute the request and cast the result.
	return ConfirmClassicPassportTotpActionClientExecuteTyped(r)
}
