package abac

/*
*	Generated by fireback 1.2.2
*	Written by Ali Torabi.
*	Checkout the repository for licenses and contribution: https://github.com/torabian/fireback
 */
import (
	"embed"
	"encoding/json"
	"fmt"
	"github.com/gin-gonic/gin"
	jsoniter "github.com/json-iterator/go"
	"github.com/schollz/progressbar/v3"
	metas "github.com/torabian/fireback/modules/abac/metas"
	mocks "github.com/torabian/fireback/modules/abac/mocks/EmailProvider"
	seeders "github.com/torabian/fireback/modules/abac/seeders/EmailProvider"
	"github.com/torabian/fireback/modules/fireback"
	"github.com/urfave/cli"
	"gopkg.in/yaml.v2"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"log"
	reflect "reflect"
	"strings"
	"time"
)

var emailProviderSeedersFs = &seeders.ViewsFs

func ResetEmailProviderSeeders(fs *embed.FS) {
	emailProviderSeedersFs = fs
}

type EmailProviderEntityQs struct {
	Type   fireback.QueriableField `cli:"type" table:"email_provider" column:"type" qs:"type"`
	ApiKey fireback.QueriableField `cli:"api-key" table:"email_provider" column:"api_key" qs:"apiKey"`
}

func (x *EmailProviderEntityQs) GetQuery() string {
	return fireback.GenerateQueryStringStyle(reflect.ValueOf(x), "")
}

var EmailProviderQsFlags = []cli.Flag{
	&cli.StringFlag{
		Name:  "type",
		Usage: "",
	},
	&cli.StringFlag{
		Name:  "api-key",
		Usage: "",
	},
}

type EmailProviderEntity struct {
	// Defines the visibility of the record in the table.
	// Visibility is a detailed topic, you can check all of the visibility values in fireback/visibility.go
	// by default, visibility of record are 0, means they are protected by the workspace
	// which are being created, and visible to every member of the workspace
	Visibility fireback.String `json:"visibility,omitempty" yaml:"visibility,omitempty" xml:"visibility,omitempty"`
	// The unique-id of the workspace which content belongs to. Upon creation this will be designated
	// to the selected workspace by user, if they have write access. You can change this value
	// or prevent changes to it manually (on root features for example modifying other workspace)
	WorkspaceId fireback.String `json:"workspaceId,omitempty" xml:"workspaceId,omitempty" yaml:"workspaceId,omitempty"`
	// The unique-id of the parent table, which this record is being linked to.
	// used internally for making relations in fireback, generally does not need manual changes
	// or modification by the developer or user. For example, if you have a object inside an object
	// the unique-id of the parent will be written in the child.
	LinkerId fireback.String `json:"linkerId,omitempty" xml:"linkerId,omitempty" yaml:"linkerId,omitempty"`
	// Used for recursive or parent-child operations. Some tables, are having nested relations,
	// and this field makes the table self refrenceing. ParentId needs to exist in the table before
	// creating of modifying a record.
	ParentId fireback.String `json:"parentId,omitempty" xml:"parentId,omitempty" yaml:"parentId,omitempty"`
	// Makes a field deletable. Some records should not be deletable at all.
	// default it's true.
	IsDeletable *bool `json:"isDeletable,omitempty" xml:"isDeletable,omitempty" yaml:"isDeletable,omitempty" gorm:"default:true"`
	// Makes a field updatable. Some records should not be updatable at all.
	// default it's true.
	IsUpdatable *bool `json:"isUpdatable,omitempty" xml:"isUpdatable,omitempty" yaml:"isUpdatable,omitempty" gorm:"default:true"`
	// The unique-id of the user which is creating the record, or the record belongs to.
	// Administration might want to change this to any user, by default Fireback fills
	// it to the current authenticated user.
	UserId fireback.String `json:"userId,omitempty" xml:"userId,omitempty" yaml:"userId,omitempty"`
	// General mechanism to rank the elements. From code perspective, it's just a number,
	// but you can sort it based on any logic for records to make a ranking, sorting.
	// they should not be unique across a table.
	Rank fireback.Int64 `json:"rank,omitempty" yaml:"rank,omitempty" xml:"rank,omitempty" gorm:"type:int;name:rank"`
	// Primary numeric key in the database. This value is not meant to be exported to public
	// or be used to access data at all. Rather a mechanism of indexing columns internally
	// or cursor pagination in future releases of fireback, or better search performance.
	ID uint `gorm:"primaryKey;autoIncrement" json:"-" yaml:"-" xml:"-"`
	// Unique id of the record across the table. This value will be accessed from public APIs,
	// and many other places intead of numeric ID property.
	// Upon generation, a UUID automatically is being assigned, and if user has specified the
	// Unique id in the post body, it will be used. This mechanism allows to manage unsaved
	// content on front-end much easier than requiring parent to exists first.
	UniqueId string `json:"uniqueId,omitempty" xml:"uniqueId,omitempty" gorm:"unique;not null;size:100;" yaml:"uniqueId,omitempty"`
	// The time that the record has been updated in datetime.
	// the field will be automatically populated by gorm orm.
	UpdatedAt *time.Time `json:"updated,omitempty" xml:"updated,omitempty" yaml:"updated,omitempty"`
	// The time that the record has been created in datetime.
	// the field will be automatically populated by gorm orm.
	CreatedAt *time.Time `json:"created,omitempty" xml:"created,omitempty" yaml:"created,omitempty"`
	// The time that the record has been deleted softly (means the data still exists in database, but no longer visible to any feature) in nano datatime
	// you need to make sure check this field if writing custom sql queries.
	// the field will be automatically populated by gorm orm.
	DeletedAt *time.Time `json:"deleted,omitempty" xml:"deleted,omitempty" yaml:"deleted,omitempty"`
	// Record creation date time formatting based on locale of the headers, or other
	// possible factors.
	CreatedFormatted string `json:"createdFormatted,omitempty" xml:"createdFormatted,omitempty" yaml:"createdFormatted,omitempty" sql:"-" gorm:"-"`
	// Record update date time formatting based on locale of the headers, or other
	// possible factors.
	UpdatedFormatted string                 `json:"updatedFormatted,omitempty" xml:"updatedFormatted,omitempty" yaml:"updatedFormatted,omitempty" sql:"-" gorm:"-"`
	Type             string                 `json:"type" xml:"type" yaml:"type"  validate:"required"        `
	ApiKey           string                 `json:"apiKey" xml:"apiKey" yaml:"apiKey"        `
	Children         []*EmailProviderEntity `csv:"-" gorm:"-" sql:"-" json:"children,omitempty" xml:"children,omitempty"  yaml:"children,omitempty"`
	LinkedTo         *EmailProviderEntity   `csv:"-" yaml:"-" gorm:"-" json:"-" sql:"-" xml:"-"`
}

func EmailProviderEntityStream(q fireback.QueryDSL) (chan []*EmailProviderEntity, *fireback.QueryResultMeta, error) {
	cn := make(chan []*EmailProviderEntity)
	q.ItemsPerPage = 50
	q.StartIndex = 0
	_, qrm, err := EmailProviderActions.Query(q)
	if err != nil {
		return nil, nil, err
	}
	go func() {
		defer close(cn)
		for i := 0; i <= int(qrm.TotalAvailableItems)-1; i++ {
			items, _, _ := EmailProviderActions.Query(q)
			i += q.ItemsPerPage
			q.StartIndex = i
			cn <- items
		}
	}()
	return cn, qrm, nil
}

type EmailProviderEntityList struct {
	Items []*EmailProviderEntity
}

func NewEmailProviderEntityList(items []*EmailProviderEntity) *EmailProviderEntityList {
	return &EmailProviderEntityList{
		Items: items,
	}
}
func (x *EmailProviderEntityList) Json() string {
	if x != nil {
		str, _ := json.MarshalIndent(x, "", "  ")
		return (string(str))
	}
	return ""
}
func (x *EmailProviderEntityList) ToTree() *fireback.TreeOperation[EmailProviderEntity] {
	return fireback.NewTreeOperation(
		x.Items,
		func(t *EmailProviderEntity) string {
			if !t.ParentId.Valid {
				return ""
			}
			return t.ParentId.String
		},
		func(t *EmailProviderEntity) string {
			return t.UniqueId
		},
	)
}

var EmailProviderPreloadRelations []string = []string{}

type emailProviderActionsSig struct {
	Update         func(query fireback.QueryDSL, dto *EmailProviderEntity) (*EmailProviderEntity, *fireback.IError)
	Create         func(dto *EmailProviderEntity, query fireback.QueryDSL) (*EmailProviderEntity, *fireback.IError)
	Upsert         func(dto *EmailProviderEntity, query fireback.QueryDSL) (*EmailProviderEntity, *fireback.IError)
	SeederInit     func() *EmailProviderEntity
	Remove         func(query fireback.QueryDSL) (int64, *fireback.IError)
	MultiInsert    func(dtos []*EmailProviderEntity, query fireback.QueryDSL) ([]*EmailProviderEntity, *fireback.IError)
	GetOne         func(query fireback.QueryDSL) (*EmailProviderEntity, *fireback.IError)
	GetByWorkspace func(query fireback.QueryDSL) (*EmailProviderEntity, *fireback.IError)
	Query          func(query fireback.QueryDSL) ([]*EmailProviderEntity, *fireback.QueryResultMeta, error)
}

var EmailProviderActions emailProviderActionsSig = emailProviderActionsSig{
	Update:         EmailProviderActionUpdateFn,
	Create:         EmailProviderActionCreateFn,
	Upsert:         EmailProviderActionUpsertFn,
	Remove:         EmailProviderActionRemoveFn,
	SeederInit:     EmailProviderActionSeederInitFn,
	MultiInsert:    EmailProviderMultiInsertFn,
	GetOne:         EmailProviderActionGetOneFn,
	GetByWorkspace: EmailProviderActionGetByWorkspaceFn,
	Query:          EmailProviderActionQueryFn,
}

func EmailProviderActionUpsertFn(dto *EmailProviderEntity, query fireback.QueryDSL) (*EmailProviderEntity, *fireback.IError) {
	return nil, nil
}

var EMAIL_PROVIDER_EVENT_CREATED = "emailProvider.created"
var EMAIL_PROVIDER_EVENT_UPDATED = "emailProvider.updated"
var EMAIL_PROVIDER_EVENT_DELETED = "emailProvider.deleted"
var EMAIL_PROVIDER_EVENTS = []string{
	EMAIL_PROVIDER_EVENT_CREATED,
	EMAIL_PROVIDER_EVENT_UPDATED,
	EMAIL_PROVIDER_EVENT_DELETED,
}

type EmailProviderFieldMap struct {
	Type   fireback.TranslatedString `yaml:"type"`
	ApiKey fireback.TranslatedString `yaml:"apiKey"`
}

var EmailProviderEntityMetaConfig map[string]int64 = map[string]int64{}
var EmailProviderEntityJsonSchema = fireback.ExtractEntityFields(reflect.ValueOf(&EmailProviderEntity{}))

func entityEmailProviderFormatter(dto *EmailProviderEntity, query fireback.QueryDSL) {
	if dto == nil {
		return
	}
}
func EmailProviderActionSeederMultiple(query fireback.QueryDSL, count int) {
	successInsert := 0
	failureInsert := 0
	batchSize := 100
	bar := progressbar.Default(int64(count))
	// Collect entities in batches
	var entitiesBatch []*EmailProviderEntity
	for i := 1; i <= count; i++ {
		entity := EmailProviderActions.SeederInit()
		entitiesBatch = append(entitiesBatch, entity)
		// When batch size is reached, perform the batch insert
		if len(entitiesBatch) == batchSize || i == count {
			// Insert batch
			_, err := EmailProviderActions.MultiInsert(entitiesBatch, query)
			if err == nil {
				successInsert += len(entitiesBatch)
			} else {
				fmt.Println(err)
				failureInsert += len(entitiesBatch)
			}
			// Clear the batch after insert
			entitiesBatch = nil
		}
		bar.Add(1)
	}
	fmt.Println("Success", successInsert, "Failure", failureInsert)
}
func EmailProviderActionSeeder(query fireback.QueryDSL, count int) {
	successInsert := 0
	failureInsert := 0
	bar := progressbar.Default(int64(count))
	for i := 1; i <= count; i++ {
		entity := EmailProviderActions.SeederInit()
		_, err := EmailProviderActions.Create(entity, query)
		if err == nil {
			successInsert++
		} else {
			fmt.Println(err)
			failureInsert++
		}
		bar.Add(1)
	}
	fmt.Println("Success", successInsert, "Failure", failureInsert)
}
func (x *EmailProviderEntity) Seeder() string {
	obj := EmailProviderActions.SeederInit()
	v, _ := json.MarshalIndent(obj, "", "  ")
	return string(v)
}
func EmailProviderActionSeederInitFn() *EmailProviderEntity {
	entity := &EmailProviderEntity{}
	return entity
}
func EmailProviderAssociationCreate(dto *EmailProviderEntity, query fireback.QueryDSL) error {
	return nil
}

/**
* These kind of content are coming from another entity, which is indepndent module
* If we want to create them, we need to do it before. This is not association.
**/
func EmailProviderRelationContentCreate(dto *EmailProviderEntity, query fireback.QueryDSL) error {
	return nil
}
func EmailProviderRelationContentUpdate(dto *EmailProviderEntity, query fireback.QueryDSL) error {
	return nil
}
func EmailProviderPolyglotUpdateHandler(dto *EmailProviderEntity, query fireback.QueryDSL) {
	if dto == nil {
		return
	}
}

/**
 * This will be validating your entity fully. Important note is that, you add validate:* tag
 * in your entity, it will automatically work here. For slices inside entity, make sure you add
 * extra line of AppendSliceErrors, otherwise they won't be detected
 */
func EmailProviderValidator(dto *EmailProviderEntity, isPatch bool) *fireback.IError {
	err := fireback.CommonStructValidatorPointer(dto, isPatch)
	return err
}

// Creates a set of natural language queries, which can be used with
// AI tools to create content or help with some tasks
var EmailProviderAskCmd cli.Command = cli.Command{
	Name:  "nlp",
	Usage: "Set of natural language queries which helps creating content or data",
	Subcommands: []cli.Command{
		{
			Name:  "sample",
			Usage: "Asks for generating sample by giving an example data",
			Flags: []cli.Flag{
				&cli.StringFlag{
					Name:  "format",
					Usage: "Format of the export or import file. Can be 'yaml', 'yml', 'json'",
					Value: "yaml",
				},
				&cli.IntFlag{
					Name:  "count",
					Usage: "How many samples to ask",
					Value: 30,
				},
			},
			Action: func(c *cli.Context) error {
				v := &EmailProviderEntity{}
				format := c.String("format")
				request := "\033[1m" + `
I need you to create me an array of exact signature as the example given below,
with at least ` + fmt.Sprint(c.String("count")) + ` items, mock the content with few words, and guess the possible values
based on the common sense. I need the output to be a valid ` + format + ` file.
Make sure you wrap the entire array in 'items' field. Also before that, I provide some explanation of each field:
Type: (type: enum) Description: 
ApiKey: (type: string) Description: 
And here is the actual object signature:
` + v.Seeder() + `
`
				fmt.Println(request)
				return nil
			},
		},
	},
}

func EmailProviderEntityPreSanitize(dto *EmailProviderEntity, query fireback.QueryDSL) {
}
func EmailProviderEntityBeforeCreateAppend(dto *EmailProviderEntity, query fireback.QueryDSL) {
	if dto.UniqueId == "" {
		dto.UniqueId = fireback.UUID()
	}
	dto.WorkspaceId = fireback.NewString(query.WorkspaceId)
	dto.UserId = fireback.NewString(query.UserId)
	EmailProviderRecursiveAddUniqueId(dto, query)
}
func EmailProviderRecursiveAddUniqueId(dto *EmailProviderEntity, query fireback.QueryDSL) {
}

/*
*
	Batch inserts, do not have all features that create
	operation does. Use it with unnormalized content,
	or read the source code carefully.
  This is not marked as an action, because it should not be available publicly
  at this moment.
*
*/
func EmailProviderMultiInsertFn(dtos []*EmailProviderEntity, query fireback.QueryDSL) ([]*EmailProviderEntity, *fireback.IError) {
	if len(dtos) > 0 {
		for index := range dtos {
			EmailProviderEntityPreSanitize(dtos[index], query)
			EmailProviderEntityBeforeCreateAppend(dtos[index], query)
		}
		var dbref *gorm.DB = nil
		if query.Tx == nil {
			dbref = fireback.GetDbRef()
		} else {
			dbref = query.Tx
		}
		query.Tx = dbref
		err := dbref.Create(&dtos).Error
		if err != nil {
			return nil, fireback.GormErrorToIError(err)
		}
	}
	return dtos, nil
}
func EmailProviderActionBatchCreateFn(dtos []*EmailProviderEntity, query fireback.QueryDSL) ([]*EmailProviderEntity, *fireback.IError) {
	if dtos != nil && len(dtos) > 0 {
		items := []*EmailProviderEntity{}
		for _, item := range dtos {
			s, err := EmailProviderActions.Create(item, query)
			if err != nil {
				return nil, err
			}
			items = append(items, s)
		}
		return items, nil
	}
	return dtos, nil
}
func EmailProviderDeleteEntireChildren(query fireback.QueryDSL, dto *EmailProviderEntity) *fireback.IError {
	// intentionally removed this. It's hard to implement it, and probably wrong without
	// proper on delete cascade
	return nil
}
func EmailProviderActionCreateFn(dto *EmailProviderEntity, query fireback.QueryDSL) (*EmailProviderEntity, *fireback.IError) {
	// 1. Validate always
	if iError := EmailProviderValidator(dto, false); iError != nil {
		return nil, iError
	}
	// 1.5 Sanitize the content coming of the front-end
	EmailProviderEntityPreSanitize(dto, query)
	// 2. Append the necessary information about user, workspace
	EmailProviderEntityBeforeCreateAppend(dto, query)
	// 3. Create other entities if we want select from them
	EmailProviderRelationContentCreate(dto, query)
	// 4. Create the entity
	var dbref *gorm.DB = nil
	if query.Tx == nil {
		dbref = fireback.GetDbRef()
	} else {
		dbref = query.Tx
	}
	query.Tx = dbref
	err := dbref.Create(&dto).Error
	if err != nil {
		err := fireback.GormErrorToIError(err)
		return nil, err
	}
	// 5. Create sub entities, objects or arrays, association to other entities
	EmailProviderAssociationCreate(dto, query)
	// 6. Fire the event into system
	actionEvent, eventErr := NewEmailProviderCreatedEvent(dto, &query)
	if actionEvent != nil && eventErr == nil {
		fireback.GetEventBusInstance().FireEvent(query, *actionEvent)
	} else {
		log.Default().Panicln("Creating event has failed for %v", dto)
	}
	/*
		event.MustFire(EMAIL_PROVIDER_EVENT_CREATED, event.M{
			"entity":   dto,
			"entityKey": fireback.GetTypeString(&EmailProviderEntity{}),
			"target":   "workspace",
			"unqiueId": query.WorkspaceId,
		})
	*/
	return dto, nil
}
func EmailProviderActionGetOneFn(query fireback.QueryDSL) (*EmailProviderEntity, *fireback.IError) {
	refl := reflect.ValueOf(&EmailProviderEntity{})
	item, err := fireback.GetOneEntity[EmailProviderEntity](query, refl)
	entityEmailProviderFormatter(item, query)
	return item, err
}
func EmailProviderActionGetByWorkspaceFn(query fireback.QueryDSL) (*EmailProviderEntity, *fireback.IError) {
	refl := reflect.ValueOf(&EmailProviderEntity{})
	item, err := fireback.GetOneByWorkspaceEntity[EmailProviderEntity](query, refl)
	entityEmailProviderFormatter(item, query)
	return item, err
}
func EmailProviderActionQueryFn(query fireback.QueryDSL) ([]*EmailProviderEntity, *fireback.QueryResultMeta, error) {
	refl := reflect.ValueOf(&EmailProviderEntity{})
	items, meta, err := fireback.QueryEntitiesPointer[EmailProviderEntity](query, refl)
	for _, item := range items {
		entityEmailProviderFormatter(item, query)
	}
	return items, meta, err
}

var emailProviderMemoryItems []*EmailProviderEntity = []*EmailProviderEntity{}

func EmailProviderEntityIntoMemory() {
	q := fireback.QueryDSL{
		ItemsPerPage: 500,
		StartIndex:   0,
	}
	_, qrm, _ := EmailProviderActions.Query(q)
	for i := 0; i <= int(qrm.TotalAvailableItems)-1; i++ {
		items, _, _ := EmailProviderActions.Query(q)
		emailProviderMemoryItems = append(emailProviderMemoryItems, items...)
		i += q.ItemsPerPage
		q.StartIndex = i
	}
}
func EmailProviderMemGet(id uint) *EmailProviderEntity {
	for _, item := range emailProviderMemoryItems {
		if item.ID == id {
			return item
		}
	}
	return nil
}
func EmailProviderMemJoin(items []uint) []*EmailProviderEntity {
	res := []*EmailProviderEntity{}
	for _, item := range items {
		v := EmailProviderMemGet(item)
		if v != nil {
			res = append(res, v)
		}
	}
	return res
}
func EmailProviderUpdateExec(dbref *gorm.DB, query fireback.QueryDSL, fields *EmailProviderEntity) (*EmailProviderEntity, *fireback.IError) {
	uniqueId := fields.UniqueId
	query.TriggerEventName = EMAIL_PROVIDER_EVENT_UPDATED
	EmailProviderEntityPreSanitize(fields, query)
	var item EmailProviderEntity
	var itemRefetched EmailProviderEntity
	// If the entity is distinct by workspace, then the Query.WorkspaceId
	// which is selected is being used as the condition for create or update
	// if not, the unique Id is being used
	cond2 := &EmailProviderEntity{UniqueId: uniqueId}
	q := dbref.
		Where(cond2).
		FirstOrCreate(&item)
	err := q.UpdateColumns(fields).Error
	if err != nil {
		return nil, fireback.GormErrorToIError(err)
	}
	query.Tx = dbref
	EmailProviderRelationContentUpdate(fields, query)
	EmailProviderPolyglotUpdateHandler(fields, query)
	if ero := EmailProviderDeleteEntireChildren(query, fields); ero != nil {
		return nil, ero
	}
	// @meta(update has many)
	err = dbref.
		Preload(clause.Associations).
		Where(&EmailProviderEntity{UniqueId: uniqueId}).
		First(&itemRefetched).Error
	if err != nil {
		return nil, fireback.GormErrorToIError(err)
	}
	actionEvent, eventErr := NewEmailProviderUpdatedEvent(fields, &query)
	if actionEvent != nil && eventErr == nil {
		fireback.GetEventBusInstance().FireEvent(query, *actionEvent)
	} else {
		log.Default().Panicln("Updating event has failed for %v", fields)
	}
	/*
	   event.MustFire(query.TriggerEventName, event.M{
	     "entity":   &item,
	     "target":   "workspace",
	     "unqiueId": query.WorkspaceId,
	   })*/
	return &itemRefetched, nil
}
func EmailProviderActionUpdateFn(query fireback.QueryDSL, fields *EmailProviderEntity) (*EmailProviderEntity, *fireback.IError) {
	if fields == nil {
		return nil, fireback.Create401Error(&fireback.FirebackMessages.BodyIsMissing, []string{})
	}
	// 1. Validate always
	if iError := EmailProviderValidator(fields, true); iError != nil {
		return nil, iError
	}
	// Let's not add this. I am not sure of the consequences
	// EmailProviderRecursiveAddUniqueId(fields, query)
	var dbref *gorm.DB = nil
	if query.Tx == nil {
		dbref = fireback.GetDbRef()
		var item *EmailProviderEntity
		vf := dbref.Transaction(func(tx *gorm.DB) error {
			dbref = tx
			var err *fireback.IError
			item, err = EmailProviderUpdateExec(dbref, query, fields)
			if err == nil {
				return nil
			} else {
				return err
			}
		})
		return item, fireback.CastToIError(vf)
	} else {
		dbref = query.Tx
		return EmailProviderUpdateExec(dbref, query, fields)
	}
}

var EmailProviderWipeCmd cli.Command = cli.Command{
	Name:  "wipe",
	Usage: "Wipes entire emailproviders ",
	Action: func(c *cli.Context) error {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{PERM_ROOT_EMAIL_PROVIDER_DELETE},
			AllowOnRoot:    true,
		})
		count, _ := EmailProviderActionWipeClean(query)
		fmt.Println("Removed", count, "of entities")
		return nil
	},
}

func EmailProviderActionRemoveFn(query fireback.QueryDSL) (int64, *fireback.IError) {
	refl := reflect.ValueOf(&EmailProviderEntity{})
	query.ActionRequires = []fireback.PermissionInfo{PERM_ROOT_EMAIL_PROVIDER_DELETE}
	return fireback.RemoveEntity[EmailProviderEntity](query, refl)
}
func EmailProviderActionWipeClean(query fireback.QueryDSL) (int64, error) {
	var err error
	var count int64 = 0
	{
		subCount, subErr := fireback.WipeCleanEntity[EmailProviderEntity]()
		if subErr != nil {
			fmt.Println("Error while wiping 'EmailProviderEntity'", subErr)
			return count, subErr
		} else {
			count += subCount
		}
	}
	return count, err
}
func EmailProviderActionBulkUpdate(
	query fireback.QueryDSL, dto *fireback.BulkRecordRequest[EmailProviderEntity]) (
	*fireback.BulkRecordRequest[EmailProviderEntity], *fireback.IError,
) {
	result := []*EmailProviderEntity{}
	err := fireback.GetDbRef().Transaction(func(tx *gorm.DB) error {
		query.Tx = tx
		for _, record := range dto.Records {
			item, err := EmailProviderActions.Update(query, record)
			if err != nil {
				return err
			} else {
				result = append(result, item)
			}
		}
		return nil
	})
	if err == nil {
		return dto, nil
	}
	return nil, err.(*fireback.IError)
}
func (x *EmailProviderEntity) Json() string {
	if x != nil {
		str, _ := json.MarshalIndent(x, "", "  ")
		return (string(str))
	}
	return ""
}

var EmailProviderEntityMeta = fireback.TableMetaData{
	EntityName:    "EmailProvider",
	ExportKey:     "email-providers",
	TableNameInDb: "email-provider_entities",
	EntityObject:  &EmailProviderEntity{},
	ExportStream:  EmailProviderActionExportT,
	ImportQuery:   EmailProviderActionImport,
}

func EmailProviderActionExport(
	query fireback.QueryDSL,
) (chan []byte, *fireback.IError) {
	return fireback.YamlExporterChannel[EmailProviderEntity](query, EmailProviderActions.Query, EmailProviderPreloadRelations)
}
func EmailProviderActionExportT(
	query fireback.QueryDSL,
) (chan []interface{}, *fireback.IError) {
	return fireback.YamlExporterChannelT[EmailProviderEntity](query, EmailProviderActions.Query, EmailProviderPreloadRelations)
}
func EmailProviderActionImport(
	dto interface{}, query fireback.QueryDSL,
) *fireback.IError {
	var json = jsoniter.ConfigCompatibleWithStandardLibrary
	var content EmailProviderEntity
	cx, err2 := json.Marshal(dto)
	if err2 != nil {
		return fireback.Create401Error(&fireback.FirebackMessages.InvalidContent, []string{})
	}
	json.Unmarshal(cx, &content)
	_, err := EmailProviderActions.Create(&content, query)
	return err
}

var EmailProviderCommonCliFlags = []cli.Flag{
	&cli.StringFlag{
		Name:     "wid",
		Required: false,
		Usage:    "Provide workspace id, if you want to change the data workspace",
	},
	&cli.StringFlag{
		Name:     "uid",
		Required: false,
		Usage:    "Unique Id - external unique hash to query entity",
	},
	&cli.StringFlag{
		Name:     "pid",
		Required: false,
		Usage:    " Parent record id of the same type",
	},
	&cli.StringFlag{
		Name:     "type",
		Required: true,
		Usage:    `One of: 'terminal', 'sendgrid' (enum)`,
	},
	&cli.StringFlag{
		Name:     "api-key",
		Required: false,
		Usage:    `apiKey (string)`,
	},
}
var EmailProviderCommonInteractiveCliFlags = []fireback.CliInteractiveFlag{
	{
		Name:        "type",
		StructField: "Type",
		Required:    true,
		Recommended: false,
		Usage:       `One of: 'terminal', 'sendgrid'`,
		Type:        "string",
	},
	{
		Name:        "apiKey",
		StructField: "ApiKey",
		Required:    false,
		Recommended: false,
		Usage:       `apiKey`,
		Type:        "string",
	},
}
var EmailProviderCommonCliFlagsOptional = []cli.Flag{
	&cli.StringFlag{
		Name:     "wid",
		Required: false,
		Usage:    "Provide workspace id, if you want to change the data workspace",
	},
	&cli.StringFlag{
		Name:     "uid",
		Required: false,
		Usage:    "Unique Id - external unique hash to query entity",
	},
	&cli.StringFlag{
		Name:     "pid",
		Required: false,
		Usage:    " Parent record id of the same type",
	},
	&cli.StringFlag{
		Name:     "type",
		Required: true,
		Usage:    `One of: 'terminal', 'sendgrid' (enum)`,
	},
	&cli.StringFlag{
		Name:     "api-key",
		Required: false,
		Usage:    `apiKey (string)`,
	},
}
var EmailProviderCreateCmd cli.Command = EMAIL_PROVIDER_ACTION_POST_ONE.ToCli()
var EmailProviderCreateInteractiveCmd cli.Command = cli.Command{
	Name:  "ic",
	Usage: "Creates a new entity, using requied fields in an interactive name",
	Flags: []cli.Flag{
		&cli.BoolFlag{
			Name:  "all",
			Usage: "Interactively asks for all inputs, not only required ones",
		},
	},
	Action: func(c *cli.Context) {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{PERM_ROOT_EMAIL_PROVIDER_CREATE},
			AllowOnRoot:    true,
		})
		entity := &EmailProviderEntity{}
		fireback.PopulateInteractively(entity, c, EmailProviderCommonInteractiveCliFlags)
		if entity, err := EmailProviderActions.Create(entity, query); err != nil {
			fmt.Println(err.Error())
		} else {
			f, _ := yaml.Marshal(entity)
			fmt.Println(fireback.FormatYamlKeys(string(f)))
		}
	},
}
var EmailProviderUpdateCmd cli.Command = cli.Command{
	Name:    "update",
	Aliases: []string{"u"},
	Flags:   EmailProviderCommonCliFlagsOptional,
	Usage:   "Updates entity by passing the parameters",
	Action: func(c *cli.Context) error {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{PERM_ROOT_EMAIL_PROVIDER_UPDATE},
			AllowOnRoot:    true,
		})
		entity := CastEmailProviderFromCli(c)
		if entity, err := EmailProviderActions.Update(query, entity); err != nil {
			fmt.Println(err.Error())
		} else {
			f, _ := json.MarshalIndent(entity, "", "  ")
			fmt.Println(string(f))
		}
		return nil
	},
}

func (x *EmailProviderEntity) FromCli(c *cli.Context) *EmailProviderEntity {
	return CastEmailProviderFromCli(c)
}
func CastEmailProviderFromCli(c *cli.Context) *EmailProviderEntity {
	template := &EmailProviderEntity{}
	if c.IsSet("uid") {
		template.UniqueId = c.String("uid")
	}
	if c.IsSet("pid") {
		template.ParentId = fireback.NewStringAutoNull(c.String("pid"))
	}
	if c.IsSet("type") {
		template.Type = c.String("type")
	}
	if c.IsSet("api-key") {
		template.ApiKey = c.String("api-key")
	}
	return template
}
func EmailProviderSyncSeederFromFs(fsRef *embed.FS, fileNames []string, q fireback.QueryDSL) {
	fireback.SeederFromFSImport(
		q,
		EmailProviderActions.Create,
		reflect.ValueOf(&EmailProviderEntity{}).Elem(),
		fsRef,
		fileNames,
		true,
	)
}
func EmailProviderSyncSeeders() {
	fireback.SeederFromFSImport(
		fireback.QueryDSL{WorkspaceId: fireback.USER_SYSTEM},
		EmailProviderActions.Create,
		reflect.ValueOf(&EmailProviderEntity{}).Elem(),
		emailProviderSeedersFs,
		[]string{},
		true,
	)
}
func EmailProviderImportMocks() {
	fireback.SeederFromFSImport(
		fireback.QueryDSL{},
		EmailProviderActions.Create,
		reflect.ValueOf(&EmailProviderEntity{}).Elem(),
		&mocks.ViewsFs,
		[]string{},
		false,
	)
}
func EmailProviderWriteQueryMock(ctx fireback.MockQueryContext) {
	for _, lang := range ctx.Languages {
		itemsPerPage := 9999
		if ctx.ItemsPerPage > 0 {
			itemsPerPage = ctx.ItemsPerPage
		}
		f := fireback.QueryDSL{ItemsPerPage: itemsPerPage, Language: lang, WithPreloads: ctx.WithPreloads, Deep: true}
		items, count, _ := EmailProviderActions.Query(f)
		result := fireback.QueryEntitySuccessResult(f, items, count)
		fireback.WriteMockDataToFile(lang, "", "EmailProvider", result)
	}
}
func EmailProvidersActionQueryString(keyword string, page int) ([]string, *fireback.QueryResultMeta, error) {
	searchFields := []string{
		`unique_id %"{keyword}"%`,
		`name %"{keyword}"%`,
	}
	m := func(item *EmailProviderEntity) string {
		label := item.UniqueId
		// if item.Name != nil {
		// 	label += " >>> " + *item.Name
		// }
		return label
	}
	query := fireback.QueryStringCastCli(searchFields, keyword, page)
	items, meta, err := EmailProviderActions.Query(query)
	stringItems := []string{}
	for _, item := range items {
		label := m(item)
		stringItems = append(stringItems, label)
	}
	return stringItems, meta, err
}

var EmailProviderDevCommands = []cli.Command{
	EmailProviderWipeCmd,
	{
		Name:  "mock",
		Usage: "Generates mock records based on the entity definition",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:  "count",
				Usage: "how many activation key do you need to be generated and stored in database",
				Value: 10,
			},
			&cli.BoolFlag{
				Name:  "batch",
				Usage: "Multiple insert into database mode. Might miss children and relations at the moment",
			},
		},
		Action: func(c *cli.Context) error {
			query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
				ActionRequires: []fireback.PermissionInfo{PERM_ROOT_EMAIL_PROVIDER_CREATE},
				AllowOnRoot:    true,
			})
			if c.Bool("batch") {
				EmailProviderActionSeederMultiple(query, c.Int("count"))
			} else {
				EmailProviderActionSeeder(query, c.Int("count"))
			}
			return nil
		},
	},
	{
		Name:    "init",
		Aliases: []string{"i"},
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "format",
				Usage: "Format of the export or import file. Can be 'yaml', 'yml', 'json'",
				Value: "yaml",
			},
		},
		Usage: "Creates a basic seeder file for you, based on the definition module we have. You can populate this file as an example",
		Action: func(c *cli.Context) error {
			seed := EmailProviderActions.SeederInit()
			fireback.CommonInitSeeder(strings.TrimSpace(c.String("format")), seed)
			return nil
		},
	},
	cli.Command{
		Name:  "mlist",
		Usage: "Prints the list of embedded mocks into the app",
		Action: func(c *cli.Context) error {
			if entity, err := fireback.GetSeederFilenames(&mocks.ViewsFs, ""); err != nil {
				fmt.Println(err.Error())
			} else {
				f, _ := json.MarshalIndent(entity, "", "  ")
				fmt.Println(string(f))
			}
			return nil
		},
	},
	cli.Command{
		Name:  "msync",
		Usage: "Tries to sync mocks into the system",
		Action: func(c *cli.Context) error {
			fireback.CommonCliImportEmbedCmd(c,
				EmailProviderActions.Create,
				reflect.ValueOf(&EmailProviderEntity{}).Elem(),
				&mocks.ViewsFs,
			)
			return nil
		},
	},
}
var EmailProviderImportExportCommands = []cli.Command{
	{
		Name:    "validate",
		Aliases: []string{"v"},
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "file",
				Usage: "Validates an import file, such as yaml, json, csv, and gives some insights how the after import it would look like",
				Value: "email-provider-seeder-email-provider.yml",
				// Uncomment before publish, they need to specify
				// Required: true,
			},
			&cli.StringFlag{
				Name:  "format",
				Usage: "Format of the export or import file. Can be 'yaml', 'yml', 'json'",
				Value: "yaml",
			},
		},
		Usage: "Reads a yaml file containing an array of email-providers, you can run this to validate if your import file is correct, and how it would look like after import",
		Action: func(c *cli.Context) error {
			data := &[]EmailProviderEntity{}
			fireback.ReadYamlFile(c.String("file"), data)
			fmt.Println(data)
			return nil
		},
	},
	cli.Command{
		Name:  "slist",
		Usage: "Prints the list of files attached to this module for syncing or bootstrapping project",
		Action: func(c *cli.Context) error {
			if entity, err := fireback.GetSeederFilenames(emailProviderSeedersFs, ""); err != nil {
				fmt.Println(err.Error())
			} else {
				f, _ := json.MarshalIndent(entity, "", "  ")
				fmt.Println(string(f))
			}
			return nil
		},
	},
	cli.Command{
		Name:  "ssync",
		Usage: "Tries to sync the embedded content into the database, the list could be seen by 'slist' command",
		Action: func(c *cli.Context) error {
			fireback.CommonCliImportEmbedCmd(c,
				EmailProviderActions.Create,
				reflect.ValueOf(&EmailProviderEntity{}).Elem(),
				emailProviderSeedersFs,
			)
			return nil
		},
	},
	cli.Command{
		Name:    "export",
		Aliases: []string{"e"},
		Flags: append(fireback.CommonQueryFlags,
			&cli.StringFlag{
				Name:     "file",
				Usage:    "The address of file you want the csv/yaml/json be exported to",
				Required: true,
			}),
		Usage: "Exports a query results into the csv/yaml/json format",
		Action: func(c *cli.Context) error {
			return fireback.CommonCliExportCmd2(c,
				EmailProviderEntityStream,
				reflect.ValueOf(&EmailProviderEntity{}).Elem(),
				c.String("file"),
				&metas.MetaFs,
				"EmailProviderFieldMap.yml",
				EmailProviderPreloadRelations,
			)
		},
	},
	cli.Command{
		Name: "import",
		Flags: append(
			append(
				fireback.CommonQueryFlags,
				&cli.StringFlag{
					Name:     "file",
					Usage:    "The address of file you want the csv be imported from",
					Required: true,
				}),
			EmailProviderCommonCliFlagsOptional...,
		),
		Usage: "imports csv/yaml/json file and place it and its children into database",
		Action: func(c *cli.Context) error {
			fireback.CommonCliImportCmdAuthorized(c,
				EmailProviderActions.Create,
				reflect.ValueOf(&EmailProviderEntity{}).Elem(),
				c.String("file"),
				&fireback.SecurityModel{
					ActionRequires: []fireback.PermissionInfo{PERM_ROOT_EMAIL_PROVIDER_CREATE},
					AllowOnRoot:    true,
				},
				func() EmailProviderEntity {
					v := CastEmailProviderFromCli(c)
					return *v
				},
			)
			return nil
		},
	},
}
var EmailProviderCliCommands []cli.Command = []cli.Command{
	EMAIL_PROVIDER_ACTION_QUERY.ToCli(),
	EMAIL_PROVIDER_ACTION_TABLE.ToCli(),
	EmailProviderCreateCmd,
	EmailProviderUpdateCmd,
	EmailProviderAskCmd,
	EmailProviderCreateInteractiveCmd,
	fireback.GetCommonRemoveQuery(
		reflect.ValueOf(&EmailProviderEntity{}).Elem(),
		EmailProviderActions.Remove,
	),
}

func EmailProviderCliFn() cli.Command {
	commands := append(EmailProviderImportExportCommands, EmailProviderCliCommands...)
	if !fireback.GetConfig().Production {
		commands = append(commands, EmailProviderDevCommands...)
	}
	return cli.Command{
		Name:        "emailprovider",
		Description: "EmailProviders module actions",
		Usage:       `Thirdparty services which will send email, allows each workspace graphically configure their token without the need of restarting servers`,
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "language",
				Value: "en",
			},
		},
		Subcommands: commands,
	}
}

var EMAIL_PROVIDER_ACTION_TABLE = fireback.Module3Action{
	Name:          "table",
	ActionAliases: []string{"t"},
	Flags:         fireback.CommonQueryFlags,
	Description:   "Table formatted queries all of the entities in database based on the standard query format",
	Action:        EmailProviderActions.Query,
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		fireback.CommonCliTableCmd2(c,
			EmailProviderActions.Query,
			security,
			reflect.ValueOf(&EmailProviderEntity{}).Elem(),
		)
		return nil
	},
}
var EMAIL_PROVIDER_ACTION_QUERY = fireback.Module3Action{
	Method: "GET",
	Url:    "/email-providers",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_EMAIL_PROVIDER_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			qs := &EmailProviderEntityQs{}
			fireback.HttpQueryEntity(c, EmailProviderActions.Query, qs)
		},
	},
	Format:         "QUERY",
	Action:         EmailProviderActions.Query,
	ResponseEntity: &[]EmailProviderEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "EmailProviderEntity",
	},
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		qs := &EmailProviderEntityQs{}
		fireback.CommonCliQueryCmd3(
			c,
			EmailProviderActions.Query,
			security,
			qs,
		)
		return nil
	},
	CliName:       "query",
	Name:          "query",
	ActionAliases: []string{"q"},
	Flags:         append(fireback.CommonQueryFlags, EmailProviderQsFlags...),
	Description:   "Queries all of the entities in database based on the standard query format (s+)",
}
var EMAIL_PROVIDER_ACTION_EXPORT = fireback.Module3Action{
	Method: "GET",
	Url:    "/email-providers/export",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_EMAIL_PROVIDER_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpStreamFileChannel(c, EmailProviderActionExport)
		},
	},
	Format:         "QUERY",
	Action:         EmailProviderActionExport,
	ResponseEntity: &[]EmailProviderEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "EmailProviderEntity",
	},
}
var EMAIL_PROVIDER_ACTION_GET_ONE = fireback.Module3Action{
	Method: "GET",
	Url:    "/email-provider/:uniqueId",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_EMAIL_PROVIDER_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpGetEntity(c, EmailProviderActions.GetOne)
		},
	},
	Format:         "GET_ONE",
	Action:         EmailProviderActions.GetOne,
	ResponseEntity: &EmailProviderEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "EmailProviderEntity",
	},
}
var EMAIL_PROVIDER_ACTION_POST_ONE = fireback.Module3Action{
	Name:          "create",
	ActionAliases: []string{"c"},
	Description:   "Create new emailProvider",
	Flags:         EmailProviderCommonCliFlags,
	Method:        "POST",
	Url:           "/email-provider",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_EMAIL_PROVIDER_CREATE},
		AllowOnRoot:    true,
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpPostEntity(c, EmailProviderActions.Create)
		},
	},
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		result, err := fireback.CliPostEntity(c, EmailProviderActions.Create, security)
		fireback.HandleActionInCli(c, result, err, map[string]map[string]string{})
		return err
	},
	Action:         EmailProviderActions.Create,
	Format:         "POST_ONE",
	RequestEntity:  &EmailProviderEntity{},
	ResponseEntity: &EmailProviderEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "EmailProviderEntity",
	},
	In: &fireback.Module3ActionBody{
		Entity: "EmailProviderEntity",
	},
}
var EMAIL_PROVIDER_ACTION_PATCH = fireback.Module3Action{
	Name:          "update",
	ActionAliases: []string{"u"},
	Flags:         EmailProviderCommonCliFlagsOptional,
	Method:        "PATCH",
	Url:           "/email-provider",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_EMAIL_PROVIDER_UPDATE},
		AllowOnRoot:    true,
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpUpdateEntity(c, EmailProviderActions.Update)
		},
	},
	Action:         EmailProviderActions.Update,
	RequestEntity:  &EmailProviderEntity{},
	ResponseEntity: &EmailProviderEntity{},
	Format:         "PATCH_ONE",
	Out: &fireback.Module3ActionBody{
		Entity: "EmailProviderEntity",
	},
	In: &fireback.Module3ActionBody{
		Entity: "EmailProviderEntity",
	},
}
var EMAIL_PROVIDER_ACTION_PATCH_BULK = fireback.Module3Action{
	Method: "PATCH",
	Url:    "/email-providers",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_EMAIL_PROVIDER_UPDATE},
		AllowOnRoot:    true,
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpUpdateEntities(c, EmailProviderActionBulkUpdate)
		},
	},
	Action:         EmailProviderActionBulkUpdate,
	Format:         "PATCH_BULK",
	RequestEntity:  &fireback.BulkRecordRequest[EmailProviderEntity]{},
	ResponseEntity: &fireback.BulkRecordRequest[EmailProviderEntity]{},
	Out: &fireback.Module3ActionBody{
		Entity: "EmailProviderEntity",
	},
	In: &fireback.Module3ActionBody{
		Entity: "EmailProviderEntity",
	},
}
var EMAIL_PROVIDER_ACTION_DELETE = fireback.Module3Action{
	Method: "DELETE",
	Url:    "/email-provider",
	Format: "DELETE_DSL",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_EMAIL_PROVIDER_DELETE},
		AllowOnRoot:    true,
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpRemoveEntity(c, EmailProviderActions.Remove)
		},
	},
	Action:         EmailProviderActions.Remove,
	RequestEntity:  &fireback.DeleteRequest{},
	ResponseEntity: &fireback.DeleteResponse{},
	TargetEntity:   &EmailProviderEntity{},
}

/**
 *	Override this function on EmailProviderEntityHttp.go,
 *	In order to add your own http
 **/
var AppendEmailProviderRouter = func(r *[]fireback.Module3Action) {}

func GetEmailProviderModule3Actions() []fireback.Module3Action {
	routes := []fireback.Module3Action{
		EMAIL_PROVIDER_ACTION_QUERY,
		EMAIL_PROVIDER_ACTION_EXPORT,
		EMAIL_PROVIDER_ACTION_GET_ONE,
		EMAIL_PROVIDER_ACTION_POST_ONE,
		EMAIL_PROVIDER_ACTION_PATCH,
		EMAIL_PROVIDER_ACTION_PATCH_BULK,
		EMAIL_PROVIDER_ACTION_DELETE,
	}
	// Append user defined functions
	AppendEmailProviderRouter(&routes)
	return routes
}

var PERM_ROOT_EMAIL_PROVIDER = fireback.PermissionInfo{
	CompleteKey: "root.manage.abac.email-provider.*",
	Name:        "Entire email provider actions (*)",
	Description: "",
}
var PERM_ROOT_EMAIL_PROVIDER_DELETE = fireback.PermissionInfo{
	CompleteKey: "root.manage.abac.email-provider.delete",
	Name:        "Delete email provider",
	Description: "",
}
var PERM_ROOT_EMAIL_PROVIDER_CREATE = fireback.PermissionInfo{
	CompleteKey: "root.manage.abac.email-provider.create",
	Name:        "Create email provider",
	Description: "",
}
var PERM_ROOT_EMAIL_PROVIDER_UPDATE = fireback.PermissionInfo{
	CompleteKey: "root.manage.abac.email-provider.update",
	Name:        "Update email provider",
	Description: "",
}
var PERM_ROOT_EMAIL_PROVIDER_QUERY = fireback.PermissionInfo{
	CompleteKey: "root.manage.abac.email-provider.query",
	Name:        "Query email provider",
	Description: "",
}
var ALL_EMAIL_PROVIDER_PERMISSIONS = []fireback.PermissionInfo{
	PERM_ROOT_EMAIL_PROVIDER_DELETE,
	PERM_ROOT_EMAIL_PROVIDER_CREATE,
	PERM_ROOT_EMAIL_PROVIDER_UPDATE,
	PERM_ROOT_EMAIL_PROVIDER_QUERY,
	PERM_ROOT_EMAIL_PROVIDER,
}
var EmailProviderType = newEmailProviderType()

func newEmailProviderType() *xEmailProviderType {
	return &xEmailProviderType{
		Terminal: "terminal",
		Sendgrid: "sendgrid",
	}
}

type xEmailProviderType struct {
	Terminal string
	Sendgrid string
}

func NewEmailProviderCreatedEvent(
	payload *EmailProviderEntity,
	query *fireback.QueryDSL,
) (*fireback.Event, error) {
	event := &fireback.Event{
		Name:    "EmailProviderCreated",
		Payload: payload,
		Security: &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{
				PERM_ROOT_EMAIL_PROVIDER_QUERY,
			},
		},
		CacheKey: "*abac.EmailProviderEntity",
	}
	// Apply the source of the event based on querydsl
	fireback.ApplyQueryDslContextToEvent(event, *query)
	return event, nil
}
func NewEmailProviderUpdatedEvent(
	payload *EmailProviderEntity,
	query *fireback.QueryDSL,
) (*fireback.Event, error) {
	event := &fireback.Event{
		Name:    "EmailProviderUpdated",
		Payload: payload,
		Security: &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{
				PERM_ROOT_EMAIL_PROVIDER_QUERY,
			},
		},
		CacheKey: "*abac.EmailProviderEntity",
	}
	// Apply the source of the event based on querydsl
	fireback.ApplyQueryDslContextToEvent(event, *query)
	return event, nil
}

var EmailProviderEntityBundle = fireback.EntityBundle{
	Permissions: ALL_EMAIL_PROVIDER_PERMISSIONS,
	// Cli command has been exluded, since we use module to wrap all the entities
	// to be more easier to wrap up.
	// Create your own bundle if you need with Cli
	//CliCommands: []cli.Command{
	//	EmailProviderCliFn(),
	//},
	Actions:      GetEmailProviderModule3Actions(),
	MockProvider: EmailProviderImportMocks,
	AutoMigrationEntities: []interface{}{
		&EmailProviderEntity{},
	},
}
