package abac

/*
*	Generated by fireback 1.2.2
*	Written by Ali Torabi.
*	Checkout the repository for licenses and contribution: https://github.com/torabian/fireback
 */
import (
	"embed"
	"encoding/json"
	"fmt"
	"log"
	reflect "reflect"
	"strings"

	"github.com/gin-gonic/gin"
	jsoniter "github.com/json-iterator/go"
	"github.com/schollz/progressbar/v3"
	metas "github.com/torabian/fireback/modules/abac/metas"
	mocks "github.com/torabian/fireback/modules/abac/mocks/RegionalContent"
	seeders "github.com/torabian/fireback/modules/abac/seeders/RegionalContent"
	"github.com/torabian/fireback/modules/fireback"
	"github.com/urfave/cli"
	"gopkg.in/yaml.v2"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

var regionalContentSeedersFs = &seeders.ViewsFs

func ResetRegionalContentSeeders(fs *embed.FS) {
	regionalContentSeedersFs = fs
}

type RegionalContentEntityQs struct {
	Content    fireback.QueriableField `cli:"content" table:"regional_content" column:"content" qs:"content"`
	Region     fireback.QueriableField `cli:"region" table:"regional_content" column:"region" qs:"region"`
	Title      fireback.QueriableField `cli:"title" table:"regional_content" column:"title" qs:"title"`
	LanguageId fireback.QueriableField `cli:"language-id" table:"regional_content" column:"language_id" qs:"languageId"`
	KeyGroup   fireback.QueriableField `cli:"key-group" table:"regional_content" column:"key_group" qs:"keyGroup"`
}

func (x *RegionalContentEntityQs) GetQuery() string {
	return fireback.GenerateQueryStringStyle(reflect.ValueOf(x), "")
}

var RegionalContentQsFlags = []cli.Flag{
	&cli.StringFlag{
		Name:  "content",
		Usage: "",
	},
	&cli.StringFlag{
		Name:  "region",
		Usage: "",
	},
	&cli.StringFlag{
		Name:  "title",
		Usage: "",
	},
	&cli.StringFlag{
		Name:  "language-id",
		Usage: "",
	},
	&cli.StringFlag{
		Name:  "key-group",
		Usage: "",
	},
}

type RegionalContentEntity struct {
	// Defines the visibility of the record in the table.
	// Visibility is a detailed topic, you can check all of the visibility values in workspaces/visibility.go
	// by default, visibility of record are 0, means they are protected by the workspace
	// which are being created, and visible to every member of the workspace
	Visibility fireback.String `json:"visibility,omitempty" yaml:"visibility,omitempty" xml:"visibility,omitempty"`
	// The unique-id of the workspace which content belongs to. Upon creation this will be designated
	// to the selected workspace by user, if they have write access. You can change this value
	// or prevent changes to it manually (on root features for example modifying other workspace)
	WorkspaceId fireback.String `json:"workspaceId,omitempty" xml:"workspaceId,omitempty" yaml:"workspaceId,omitempty"`
	// The unique-id of the parent table, which this record is being linked to.
	// used internally for making relations in fireback, generally does not need manual changes
	// or modification by the developer or user. For example, if you have a object inside an object
	// the unique-id of the parent will be written in the child.
	LinkerId fireback.String `json:"linkerId,omitempty" xml:"linkerId,omitempty" yaml:"linkerId,omitempty"`
	// Used for recursive or parent-child operations. Some tables, are having nested relations,
	// and this field makes the table self refrenceing. ParentId needs to exist in the table before
	// creating of modifying a record.
	ParentId fireback.String `json:"parentId,omitempty" xml:"parentId,omitempty" yaml:"parentId,omitempty"`
	// Makes a field deletable. Some records should not be deletable at all.
	// default it's true.
	IsDeletable *bool `json:"isDeletable,omitempty" xml:"isDeletable,omitempty" yaml:"isDeletable,omitempty" gorm:"default:true"`
	// Makes a field updatable. Some records should not be updatable at all.
	// default it's true.
	IsUpdatable *bool `json:"isUpdatable,omitempty" xml:"isUpdatable,omitempty" yaml:"isUpdatable,omitempty" gorm:"default:true"`
	// The unique-id of the user which is creating the record, or the record belongs to.
	// Administration might want to change this to any user, by default Fireback fills
	// it to the current authenticated user.
	UserId fireback.String `json:"userId,omitempty" xml:"userId,omitempty" yaml:"userId,omitempty"`
	// General mechanism to rank the elements. From code perspective, it's just a number,
	// but you can sort it based on any logic for records to make a ranking, sorting.
	// they should not be unique across a table.
	Rank fireback.Int64 `json:"rank,omitempty" yaml:"rank,omitempty" xml:"rank,omitempty" gorm:"type:int;name:rank"`
	// Primary numeric key in the database. This value is not meant to be exported to public
	// or be used to access data at all. Rather a mechanism of indexing columns internally
	// or cursor pagination in future releases of fireback, or better search performance.
	ID uint `gorm:"primaryKey;autoIncrement" json:"-" yaml:"-" xml:"-"`
	// Unique id of the record across the table. This value will be accessed from public APIs,
	// and many other places intead of numeric ID property.
	// Upon generation, a UUID automatically is being assigned, and if user has specified the
	// Unique id in the post body, it will be used. This mechanism allows to manage unsaved
	// content on front-end much easier than requiring parent to exists first.
	UniqueId string `json:"uniqueId,omitempty" xml:"uniqueId,omitempty" gorm:"unique;not null;size:100;" yaml:"uniqueId,omitempty"`
	// The time that the record has been created in nano-seconds.
	// the field will be automatically populated by gorm orm.
	Created int64 `json:"created,omitempty" xml:"created,omitempty" yaml:"created,omitempty" gorm:"autoUpdateTime:nano"`
	// The time that the record has been updated in nano-seconds.
	// the field will be automatically populated by gorm orm.
	Updated int64 `json:"updated,omitempty" xml:"updated,omitempty" yaml:"updated,omitempty"`
	// The time that the record has been deleted softly (means the data still exists in database, but no longer visible to any feature) in nano seconds
	// you need to make sure check this field if writing custom sql queries.
	// the field will be automatically populated by gorm orm.
	Deleted int64 `json:"deleted,omitempty" xml:"deleted,omitempty" yaml:"deleted,omitempty"`
	// Record creation date time formatting based on locale of the headers, or other
	// possible factors.
	CreatedFormatted string `json:"createdFormatted,omitempty" xml:"createdFormatted,omitempty" yaml:"createdFormatted,omitempty" sql:"-" gorm:"-"`
	// Record update date time formatting based on locale of the headers, or other
	// possible factors.
	UpdatedFormatted string                   `json:"updatedFormatted,omitempty" xml:"updatedFormatted,omitempty" yaml:"updatedFormatted,omitempty" sql:"-" gorm:"-"`
	Content          string                   `json:"content" xml:"content" yaml:"content"  validate:"required"        `
	ContentExcerpt   *string                  `json:"contentExcerpt" yaml:"contentExcerpt" xml:"contentExcerpt"`
	Region           string                   `json:"region" xml:"region" yaml:"region"  validate:"required"        `
	Title            string                   `json:"title" xml:"title" yaml:"title"        `
	LanguageId       string                   `json:"languageId" xml:"languageId" yaml:"languageId"  validate:"required"    gorm:"index:regional_content_index,unique"      `
	KeyGroup         string                   `json:"keyGroup" xml:"keyGroup" yaml:"keyGroup"  validate:"required"    gorm:"index:regional_content_index,unique"      `
	Children         []*RegionalContentEntity `csv:"-" gorm:"-" sql:"-" json:"children,omitempty" xml:"children,omitempty"  yaml:"children,omitempty"`
	LinkedTo         *RegionalContentEntity   `csv:"-" yaml:"-" gorm:"-" json:"-" sql:"-" xml:"-"`
}

func RegionalContentEntityStream(q fireback.QueryDSL) (chan []*RegionalContentEntity, *fireback.QueryResultMeta, error) {
	cn := make(chan []*RegionalContentEntity)
	q.ItemsPerPage = 50
	q.StartIndex = 0
	_, qrm, err := RegionalContentActions.Query(q)
	if err != nil {
		return nil, nil, err
	}
	go func() {
		defer close(cn)
		for i := 0; i <= int(qrm.TotalAvailableItems)-1; i++ {
			items, _, _ := RegionalContentActions.Query(q)
			i += q.ItemsPerPage
			q.StartIndex = i
			cn <- items
		}
	}()
	return cn, qrm, nil
}

type RegionalContentEntityList struct {
	Items []*RegionalContentEntity
}

func NewRegionalContentEntityList(items []*RegionalContentEntity) *RegionalContentEntityList {
	return &RegionalContentEntityList{
		Items: items,
	}
}
func (x *RegionalContentEntityList) Json() string {
	if x != nil {
		str, _ := json.MarshalIndent(x, "", "  ")
		return (string(str))
	}
	return ""
}
func (x *RegionalContentEntityList) ToTree() *fireback.TreeOperation[RegionalContentEntity] {
	return fireback.NewTreeOperation(
		x.Items,
		func(t *RegionalContentEntity) string {
			if !t.ParentId.Valid {
				return ""
			}
			return t.ParentId.String
		},
		func(t *RegionalContentEntity) string {
			return t.UniqueId
		},
	)
}

var RegionalContentPreloadRelations []string = []string{}

type regionalContentActionsSig struct {
	Update         func(query fireback.QueryDSL, dto *RegionalContentEntity) (*RegionalContentEntity, *fireback.IError)
	Create         func(dto *RegionalContentEntity, query fireback.QueryDSL) (*RegionalContentEntity, *fireback.IError)
	Upsert         func(dto *RegionalContentEntity, query fireback.QueryDSL) (*RegionalContentEntity, *fireback.IError)
	SeederInit     func() *RegionalContentEntity
	Remove         func(query fireback.QueryDSL) (int64, *fireback.IError)
	MultiInsert    func(dtos []*RegionalContentEntity, query fireback.QueryDSL) ([]*RegionalContentEntity, *fireback.IError)
	GetOne         func(query fireback.QueryDSL) (*RegionalContentEntity, *fireback.IError)
	GetByWorkspace func(query fireback.QueryDSL) (*RegionalContentEntity, *fireback.IError)
	Query          func(query fireback.QueryDSL) ([]*RegionalContentEntity, *fireback.QueryResultMeta, error)
}

var RegionalContentActions regionalContentActionsSig = regionalContentActionsSig{
	Update:         RegionalContentActionUpdateFn,
	Create:         RegionalContentActionCreateFn,
	Upsert:         RegionalContentActionUpsertFn,
	Remove:         RegionalContentActionRemoveFn,
	SeederInit:     RegionalContentActionSeederInitFn,
	MultiInsert:    RegionalContentMultiInsertFn,
	GetOne:         RegionalContentActionGetOneFn,
	GetByWorkspace: RegionalContentActionGetByWorkspaceFn,
	Query:          RegionalContentActionQueryFn,
}

func RegionalContentActionUpsertFn(dto *RegionalContentEntity, query fireback.QueryDSL) (*RegionalContentEntity, *fireback.IError) {
	return nil, nil
}

var REGIONAL_CONTENT_EVENT_CREATED = "regionalContent.created"
var REGIONAL_CONTENT_EVENT_UPDATED = "regionalContent.updated"
var REGIONAL_CONTENT_EVENT_DELETED = "regionalContent.deleted"
var REGIONAL_CONTENT_EVENTS = []string{
	REGIONAL_CONTENT_EVENT_CREATED,
	REGIONAL_CONTENT_EVENT_UPDATED,
	REGIONAL_CONTENT_EVENT_DELETED,
}

type RegionalContentFieldMap struct {
	Content    fireback.TranslatedString `yaml:"content"`
	Region     fireback.TranslatedString `yaml:"region"`
	Title      fireback.TranslatedString `yaml:"title"`
	LanguageId fireback.TranslatedString `yaml:"languageId"`
	KeyGroup   fireback.TranslatedString `yaml:"keyGroup"`
}

var RegionalContentEntityMetaConfig map[string]int64 = map[string]int64{
	"ContentExcerptSize": 100,
}
var RegionalContentEntityJsonSchema = fireback.ExtractEntityFields(reflect.ValueOf(&RegionalContentEntity{}))

func entityRegionalContentFormatter(dto *RegionalContentEntity, query fireback.QueryDSL) {
	if dto == nil {
		return
	}
	if dto.Created > 0 {
		dto.CreatedFormatted = fireback.FormatDateBasedOnQuery(dto.Created, query)
	}
	if dto.Updated > 0 {
		dto.CreatedFormatted = fireback.FormatDateBasedOnQuery(dto.Updated, query)
	}
}
func RegionalContentActionSeederMultiple(query fireback.QueryDSL, count int) {
	successInsert := 0
	failureInsert := 0
	batchSize := 100
	bar := progressbar.Default(int64(count))
	// Collect entities in batches
	var entitiesBatch []*RegionalContentEntity
	for i := 1; i <= count; i++ {
		entity := RegionalContentActions.SeederInit()
		entitiesBatch = append(entitiesBatch, entity)
		// When batch size is reached, perform the batch insert
		if len(entitiesBatch) == batchSize || i == count {
			// Insert batch
			_, err := RegionalContentActions.MultiInsert(entitiesBatch, query)
			if err == nil {
				successInsert += len(entitiesBatch)
			} else {
				fmt.Println(err)
				failureInsert += len(entitiesBatch)
			}
			// Clear the batch after insert
			entitiesBatch = nil
		}
		bar.Add(1)
	}
	fmt.Println("Success", successInsert, "Failure", failureInsert)
}
func RegionalContentActionSeeder(query fireback.QueryDSL, count int) {
	successInsert := 0
	failureInsert := 0
	bar := progressbar.Default(int64(count))
	for i := 1; i <= count; i++ {
		entity := RegionalContentActions.SeederInit()
		_, err := RegionalContentActions.Create(entity, query)
		if err == nil {
			successInsert++
		} else {
			fmt.Println(err)
			failureInsert++
		}
		bar.Add(1)
	}
	fmt.Println("Success", successInsert, "Failure", failureInsert)
}
func (x *RegionalContentEntity) Seeder() string {
	obj := RegionalContentActions.SeederInit()
	v, _ := json.MarshalIndent(obj, "", "  ")
	return string(v)
}
func RegionalContentActionSeederInitFn() *RegionalContentEntity {
	entity := &RegionalContentEntity{}
	return entity
}
func RegionalContentAssociationCreate(dto *RegionalContentEntity, query fireback.QueryDSL) error {
	return nil
}

/**
* These kind of content are coming from another entity, which is indepndent module
* If we want to create them, we need to do it before. This is not association.
**/
func RegionalContentRelationContentCreate(dto *RegionalContentEntity, query fireback.QueryDSL) error {
	return nil
}
func RegionalContentRelationContentUpdate(dto *RegionalContentEntity, query fireback.QueryDSL) error {
	return nil
}
func RegionalContentPolyglotUpdateHandler(dto *RegionalContentEntity, query fireback.QueryDSL) {
	if dto == nil {
		return
	}
}

/**
 * This will be validating your entity fully. Important note is that, you add validate:* tag
 * in your entity, it will automatically work here. For slices inside entity, make sure you add
 * extra line of AppendSliceErrors, otherwise they won't be detected
 */
func RegionalContentValidator(dto *RegionalContentEntity, isPatch bool) *fireback.IError {
	err := fireback.CommonStructValidatorPointer(dto, isPatch)
	return err
}

// Creates a set of natural language queries, which can be used with
// AI tools to create content or help with some tasks
var RegionalContentAskCmd cli.Command = cli.Command{
	Name:  "nlp",
	Usage: "Set of natural language queries which helps creating content or data",
	Subcommands: []cli.Command{
		{
			Name:  "sample",
			Usage: "Asks for generating sample by giving an example data",
			Flags: []cli.Flag{
				&cli.StringFlag{
					Name:  "format",
					Usage: "Format of the export or import file. Can be 'yaml', 'yml', 'json'",
					Value: "yaml",
				},
				&cli.IntFlag{
					Name:  "count",
					Usage: "How many samples to ask",
					Value: 30,
				},
			},
			Action: func(c *cli.Context) error {
				v := &RegionalContentEntity{}
				format := c.String("format")
				request := "\033[1m" + `
I need you to create me an array of exact signature as the example given below,
with at least ` + fmt.Sprint(c.String("count")) + ` items, mock the content with few words, and guess the possible values
based on the common sense. I need the output to be a valid ` + format + ` file.
Make sure you wrap the entire array in 'items' field. Also before that, I provide some explanation of each field:
Content: (type: html) Description: 
Region: (type: string) Description: 
Title: (type: string) Description: 
LanguageId: (type: string) Description: 
KeyGroup: (type: enum) Description: 
And here is the actual object signature:
` + v.Seeder() + `
`
				fmt.Println(request)
				return nil
			},
		},
	},
}

func RegionalContentEntityPreSanitize(dto *RegionalContentEntity, query fireback.QueryDSL) {
	if dto.Content != "" {
		Content := dto.Content
		ContentExcerpt := fireback.StripPolicy.Sanitize(dto.Content)
		Content = fireback.UgcPolicy.Sanitize(Content)
		ContentExcerpt = fireback.StripPolicy.Sanitize(ContentExcerpt)
		ContentExcerptSize, ContentExcerptSizeExists := RegionalContentEntityMetaConfig["ContentExcerptSize"]
		if ContentExcerptSizeExists {
			ContentExcerpt = fireback.PickFirstNWords(ContentExcerpt, int(ContentExcerptSize))
		} else {
			ContentExcerpt = fireback.PickFirstNWords(ContentExcerpt, 30)
		}
		dto.ContentExcerpt = &ContentExcerpt
		dto.Content = Content
	}
}
func RegionalContentEntityBeforeCreateAppend(dto *RegionalContentEntity, query fireback.QueryDSL) {
	if dto.UniqueId == "" {
		dto.UniqueId = fireback.UUID()
	}
	dto.WorkspaceId = fireback.NewString(query.WorkspaceId)
	dto.UserId = fireback.NewString(query.UserId)
	RegionalContentRecursiveAddUniqueId(dto, query)
}
func RegionalContentRecursiveAddUniqueId(dto *RegionalContentEntity, query fireback.QueryDSL) {
}

/*
*

		Batch inserts, do not have all features that create
		operation does. Use it with unnormalized content,
		or read the source code carefully.
	  This is not marked as an action, because it should not be available publicly
	  at this moment.

*
*/
func RegionalContentMultiInsertFn(dtos []*RegionalContentEntity, query fireback.QueryDSL) ([]*RegionalContentEntity, *fireback.IError) {
	if len(dtos) > 0 {
		for index := range dtos {
			RegionalContentEntityPreSanitize(dtos[index], query)
			RegionalContentEntityBeforeCreateAppend(dtos[index], query)
		}
		var dbref *gorm.DB = nil
		if query.Tx == nil {
			dbref = fireback.GetDbRef()
		} else {
			dbref = query.Tx
		}
		query.Tx = dbref
		err := dbref.Create(&dtos).Error
		if err != nil {
			return nil, fireback.GormErrorToIError(err)
		}
	}
	return dtos, nil
}
func RegionalContentActionBatchCreateFn(dtos []*RegionalContentEntity, query fireback.QueryDSL) ([]*RegionalContentEntity, *fireback.IError) {
	if dtos != nil && len(dtos) > 0 {
		items := []*RegionalContentEntity{}
		for _, item := range dtos {
			s, err := RegionalContentActions.Create(item, query)
			if err != nil {
				return nil, err
			}
			items = append(items, s)
		}
		return items, nil
	}
	return dtos, nil
}
func RegionalContentDeleteEntireChildren(query fireback.QueryDSL, dto *RegionalContentEntity) *fireback.IError {
	// intentionally removed this. It's hard to implement it, and probably wrong without
	// proper on delete cascade
	return nil
}
func RegionalContentActionCreateFn(dto *RegionalContentEntity, query fireback.QueryDSL) (*RegionalContentEntity, *fireback.IError) {
	// 1. Validate always
	if iError := RegionalContentValidator(dto, false); iError != nil {
		return nil, iError
	}
	// 1.5 Sanitize the content coming of the front-end
	RegionalContentEntityPreSanitize(dto, query)
	// 2. Append the necessary information about user, workspace
	RegionalContentEntityBeforeCreateAppend(dto, query)
	// 3. Create other entities if we want select from them
	RegionalContentRelationContentCreate(dto, query)
	// 4. Create the entity
	var dbref *gorm.DB = nil
	if query.Tx == nil {
		dbref = fireback.GetDbRef()
	} else {
		dbref = query.Tx
	}
	query.Tx = dbref
	err := dbref.Create(&dto).Error
	if err != nil {
		err := fireback.GormErrorToIError(err)
		return nil, err
	}
	// 5. Create sub entities, objects or arrays, association to other entities
	RegionalContentAssociationCreate(dto, query)
	// 6. Fire the event into system
	actionEvent, eventErr := NewRegionalContentCreatedEvent(dto, &query)
	if actionEvent != nil && eventErr == nil {
		fireback.GetEventBusInstance().FireEvent(query, *actionEvent)
	} else {
		log.Default().Panicln("Creating event has failed for %v", dto)
	}
	/*
		event.MustFire(REGIONAL_CONTENT_EVENT_CREATED, event.M{
			"entity":   dto,
			"entityKey": fireback.GetTypeString(&RegionalContentEntity{}),
			"target":   "workspace",
			"unqiueId": query.WorkspaceId,
		})
	*/
	return dto, nil
}
func RegionalContentActionGetOneFn(query fireback.QueryDSL) (*RegionalContentEntity, *fireback.IError) {
	refl := reflect.ValueOf(&RegionalContentEntity{})
	item, err := fireback.GetOneEntity[RegionalContentEntity](query, refl)
	entityRegionalContentFormatter(item, query)
	return item, err
}
func RegionalContentActionGetByWorkspaceFn(query fireback.QueryDSL) (*RegionalContentEntity, *fireback.IError) {
	refl := reflect.ValueOf(&RegionalContentEntity{})
	item, err := fireback.GetOneByWorkspaceEntity[RegionalContentEntity](query, refl)
	entityRegionalContentFormatter(item, query)
	return item, err
}
func RegionalContentActionQueryFn(query fireback.QueryDSL) ([]*RegionalContentEntity, *fireback.QueryResultMeta, error) {
	refl := reflect.ValueOf(&RegionalContentEntity{})
	items, meta, err := fireback.QueryEntitiesPointer[RegionalContentEntity](query, refl)
	for _, item := range items {
		entityRegionalContentFormatter(item, query)
	}
	return items, meta, err
}

var regionalContentMemoryItems []*RegionalContentEntity = []*RegionalContentEntity{}

func RegionalContentEntityIntoMemory() {
	q := fireback.QueryDSL{
		ItemsPerPage: 500,
		StartIndex:   0,
	}
	_, qrm, _ := RegionalContentActions.Query(q)
	for i := 0; i <= int(qrm.TotalAvailableItems)-1; i++ {
		items, _, _ := RegionalContentActions.Query(q)
		regionalContentMemoryItems = append(regionalContentMemoryItems, items...)
		i += q.ItemsPerPage
		q.StartIndex = i
	}
}
func RegionalContentMemGet(id uint) *RegionalContentEntity {
	for _, item := range regionalContentMemoryItems {
		if item.ID == id {
			return item
		}
	}
	return nil
}
func RegionalContentMemJoin(items []uint) []*RegionalContentEntity {
	res := []*RegionalContentEntity{}
	for _, item := range items {
		v := RegionalContentMemGet(item)
		if v != nil {
			res = append(res, v)
		}
	}
	return res
}
func RegionalContentUpdateExec(dbref *gorm.DB, query fireback.QueryDSL, fields *RegionalContentEntity) (*RegionalContentEntity, *fireback.IError) {
	uniqueId := fields.UniqueId
	query.TriggerEventName = REGIONAL_CONTENT_EVENT_UPDATED
	RegionalContentEntityPreSanitize(fields, query)
	var item RegionalContentEntity
	var itemRefetched RegionalContentEntity
	// If the entity is distinct by workspace, then the Query.WorkspaceId
	// which is selected is being used as the condition for create or update
	// if not, the unique Id is being used
	cond2 := &RegionalContentEntity{UniqueId: uniqueId}
	q := dbref.
		Where(cond2).
		FirstOrCreate(&item)
	err := q.UpdateColumns(fields).Error
	if err != nil {
		return nil, fireback.GormErrorToIError(err)
	}
	query.Tx = dbref
	RegionalContentRelationContentUpdate(fields, query)
	RegionalContentPolyglotUpdateHandler(fields, query)
	if ero := RegionalContentDeleteEntireChildren(query, fields); ero != nil {
		return nil, ero
	}
	// @meta(update has many)
	err = dbref.
		Preload(clause.Associations).
		Where(&RegionalContentEntity{UniqueId: uniqueId}).
		First(&itemRefetched).Error
	if err != nil {
		return nil, fireback.GormErrorToIError(err)
	}
	actionEvent, eventErr := NewRegionalContentUpdatedEvent(fields, &query)
	if actionEvent != nil && eventErr == nil {
		fireback.GetEventBusInstance().FireEvent(query, *actionEvent)
	} else {
		log.Default().Panicln("Updating event has failed for %v", fields)
	}
	/*
	   event.MustFire(query.TriggerEventName, event.M{
	     "entity":   &item,
	     "target":   "workspace",
	     "unqiueId": query.WorkspaceId,
	   })*/
	return &itemRefetched, nil
}
func RegionalContentActionUpdateFn(query fireback.QueryDSL, fields *RegionalContentEntity) (*RegionalContentEntity, *fireback.IError) {
	if fields == nil {
		return nil, fireback.Create401Error(&fireback.WorkspacesMessages.BodyIsMissing, []string{})
	}
	// 1. Validate always
	if iError := RegionalContentValidator(fields, true); iError != nil {
		return nil, iError
	}
	// Let's not add this. I am not sure of the consequences
	// RegionalContentRecursiveAddUniqueId(fields, query)
	var dbref *gorm.DB = nil
	if query.Tx == nil {
		dbref = fireback.GetDbRef()
		var item *RegionalContentEntity
		vf := dbref.Transaction(func(tx *gorm.DB) error {
			dbref = tx
			var err *fireback.IError
			item, err = RegionalContentUpdateExec(dbref, query, fields)
			if err == nil {
				return nil
			} else {
				return err
			}
		})
		return item, fireback.CastToIError(vf)
	} else {
		dbref = query.Tx
		return RegionalContentUpdateExec(dbref, query, fields)
	}
}

var RegionalContentWipeCmd cli.Command = cli.Command{
	Name:  "wipe",
	Usage: "Wipes entire regionalcontents ",
	Action: func(c *cli.Context) error {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{PERM_ROOT_REGIONAL_CONTENT_DELETE},
			AllowOnRoot:    true,
		})
		count, _ := RegionalContentActionWipeClean(query)
		fmt.Println("Removed", count, "of entities")
		return nil
	},
}

func RegionalContentActionRemoveFn(query fireback.QueryDSL) (int64, *fireback.IError) {
	refl := reflect.ValueOf(&RegionalContentEntity{})
	query.ActionRequires = []fireback.PermissionInfo{PERM_ROOT_REGIONAL_CONTENT_DELETE}
	return fireback.RemoveEntity[RegionalContentEntity](query, refl)
}
func RegionalContentActionWipeClean(query fireback.QueryDSL) (int64, error) {
	var err error
	var count int64 = 0
	{
		subCount, subErr := fireback.WipeCleanEntity[RegionalContentEntity]()
		if subErr != nil {
			fmt.Println("Error while wiping 'RegionalContentEntity'", subErr)
			return count, subErr
		} else {
			count += subCount
		}
	}
	return count, err
}
func RegionalContentActionBulkUpdate(
	query fireback.QueryDSL, dto *fireback.BulkRecordRequest[RegionalContentEntity]) (
	*fireback.BulkRecordRequest[RegionalContentEntity], *fireback.IError,
) {
	result := []*RegionalContentEntity{}
	err := fireback.GetDbRef().Transaction(func(tx *gorm.DB) error {
		query.Tx = tx
		for _, record := range dto.Records {
			item, err := RegionalContentActions.Update(query, record)
			if err != nil {
				return err
			} else {
				result = append(result, item)
			}
		}
		return nil
	})
	if err == nil {
		return dto, nil
	}
	return nil, err.(*fireback.IError)
}
func (x *RegionalContentEntity) Json() string {
	if x != nil {
		str, _ := json.MarshalIndent(x, "", "  ")
		return (string(str))
	}
	return ""
}

var RegionalContentEntityMeta = fireback.TableMetaData{
	EntityName:    "RegionalContent",
	ExportKey:     "regional-contents",
	TableNameInDb: "regional-content_entities",
	EntityObject:  &RegionalContentEntity{},
	ExportStream:  RegionalContentActionExportT,
	ImportQuery:   RegionalContentActionImport,
}

func RegionalContentActionExport(
	query fireback.QueryDSL,
) (chan []byte, *fireback.IError) {
	return fireback.YamlExporterChannel[RegionalContentEntity](query, RegionalContentActions.Query, RegionalContentPreloadRelations)
}
func RegionalContentActionExportT(
	query fireback.QueryDSL,
) (chan []interface{}, *fireback.IError) {
	return fireback.YamlExporterChannelT[RegionalContentEntity](query, RegionalContentActions.Query, RegionalContentPreloadRelations)
}
func RegionalContentActionImport(
	dto interface{}, query fireback.QueryDSL,
) *fireback.IError {
	var json = jsoniter.ConfigCompatibleWithStandardLibrary
	var content RegionalContentEntity
	cx, err2 := json.Marshal(dto)
	if err2 != nil {
		return fireback.Create401Error(&fireback.WorkspacesMessages.InvalidContent, []string{})
	}
	json.Unmarshal(cx, &content)
	_, err := RegionalContentActions.Create(&content, query)
	return err
}

var RegionalContentCommonCliFlags = []cli.Flag{
	&cli.StringFlag{
		Name:     "wid",
		Required: false,
		Usage:    "Provide workspace id, if you want to change the data workspace",
	},
	&cli.StringFlag{
		Name:     "uid",
		Required: false,
		Usage:    "Unique Id - external unique hash to query entity",
	},
	&cli.StringFlag{
		Name:     "pid",
		Required: false,
		Usage:    " Parent record id of the same type",
	},
	&cli.StringFlag{
		Name:     "content",
		Required: true,
		Usage:    `content (html)`,
	},
	&cli.StringFlag{
		Name:     "region",
		Required: true,
		Usage:    `region (string)`,
	},
	&cli.StringFlag{
		Name:     "title",
		Required: false,
		Usage:    `title (string)`,
	},
	&cli.StringFlag{
		Name:     "language-id",
		Required: true,
		Usage:    `languageId (string)`,
	},
	&cli.StringFlag{
		Name:     "key-group",
		Required: true,
		Usage:    `One of: 'SMS_OTP', 'EMAIL_OTP' (enum)`,
	},
}
var RegionalContentCommonInteractiveCliFlags = []fireback.CliInteractiveFlag{
	{
		Name:        "region",
		StructField: "Region",
		Required:    true,
		Recommended: false,
		Usage:       `region`,
		Type:        "string",
	},
	{
		Name:        "title",
		StructField: "Title",
		Required:    false,
		Recommended: false,
		Usage:       `title`,
		Type:        "string",
	},
	{
		Name:        "languageId",
		StructField: "LanguageId",
		Required:    true,
		Recommended: false,
		Usage:       `languageId`,
		Type:        "string",
	},
	{
		Name:        "keyGroup",
		StructField: "KeyGroup",
		Required:    true,
		Recommended: false,
		Usage:       `One of: 'SMS_OTP', 'EMAIL_OTP'`,
		Type:        "string",
	},
}
var RegionalContentCommonCliFlagsOptional = []cli.Flag{
	&cli.StringFlag{
		Name:     "wid",
		Required: false,
		Usage:    "Provide workspace id, if you want to change the data workspace",
	},
	&cli.StringFlag{
		Name:     "uid",
		Required: false,
		Usage:    "Unique Id - external unique hash to query entity",
	},
	&cli.StringFlag{
		Name:     "pid",
		Required: false,
		Usage:    " Parent record id of the same type",
	},
	&cli.StringFlag{
		Name:     "content",
		Required: true,
		Usage:    `content (html)`,
	},
	&cli.StringFlag{
		Name:     "region",
		Required: true,
		Usage:    `region (string)`,
	},
	&cli.StringFlag{
		Name:     "title",
		Required: false,
		Usage:    `title (string)`,
	},
	&cli.StringFlag{
		Name:     "language-id",
		Required: true,
		Usage:    `languageId (string)`,
	},
	&cli.StringFlag{
		Name:     "key-group",
		Required: true,
		Usage:    `One of: 'SMS_OTP', 'EMAIL_OTP' (enum)`,
	},
}
var RegionalContentCreateCmd cli.Command = REGIONAL_CONTENT_ACTION_POST_ONE.ToCli()
var RegionalContentCreateInteractiveCmd cli.Command = cli.Command{
	Name:  "ic",
	Usage: "Creates a new entity, using requied fields in an interactive name",
	Flags: []cli.Flag{
		&cli.BoolFlag{
			Name:  "all",
			Usage: "Interactively asks for all inputs, not only required ones",
		},
	},
	Action: func(c *cli.Context) {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{PERM_ROOT_REGIONAL_CONTENT_CREATE},
			AllowOnRoot:    true,
		})
		entity := &RegionalContentEntity{}
		fireback.PopulateInteractively(entity, c, RegionalContentCommonInteractiveCliFlags)
		if entity, err := RegionalContentActions.Create(entity, query); err != nil {
			fmt.Println(err.Error())
		} else {
			f, _ := yaml.Marshal(entity)
			fmt.Println(fireback.FormatYamlKeys(string(f)))
		}
	},
}
var RegionalContentUpdateCmd cli.Command = cli.Command{
	Name:    "update",
	Aliases: []string{"u"},
	Flags:   RegionalContentCommonCliFlagsOptional,
	Usage:   "Updates entity by passing the parameters",
	Action: func(c *cli.Context) error {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{PERM_ROOT_REGIONAL_CONTENT_UPDATE},
			AllowOnRoot:    true,
		})
		entity := CastRegionalContentFromCli(c)
		if entity, err := RegionalContentActions.Update(query, entity); err != nil {
			fmt.Println(err.Error())
		} else {
			f, _ := json.MarshalIndent(entity, "", "  ")
			fmt.Println(string(f))
		}
		return nil
	},
}

func (x *RegionalContentEntity) FromCli(c *cli.Context) *RegionalContentEntity {
	return CastRegionalContentFromCli(c)
}
func CastRegionalContentFromCli(c *cli.Context) *RegionalContentEntity {
	template := &RegionalContentEntity{}
	if c.IsSet("uid") {
		template.UniqueId = c.String("uid")
	}
	if c.IsSet("pid") {
		template.ParentId = fireback.NewStringAutoNull(c.String("pid"))
	}
	if c.IsSet("content") {
		template.Content = c.String("content")
	}
	if c.IsSet("region") {
		template.Region = c.String("region")
	}
	if c.IsSet("title") {
		template.Title = c.String("title")
	}
	if c.IsSet("language-id") {
		template.LanguageId = c.String("language-id")
	}
	if c.IsSet("key-group") {
		template.KeyGroup = c.String("key-group")
	}
	return template
}
func RegionalContentSyncSeederFromFs(fsRef *embed.FS, fileNames []string, q fireback.QueryDSL) {
	fireback.SeederFromFSImport(
		q,
		RegionalContentActions.Create,
		reflect.ValueOf(&RegionalContentEntity{}).Elem(),
		fsRef,
		fileNames,
		true,
	)
}
func RegionalContentSyncSeeders() {
	fireback.SeederFromFSImport(
		fireback.QueryDSL{WorkspaceId: fireback.USER_SYSTEM},
		RegionalContentActions.Create,
		reflect.ValueOf(&RegionalContentEntity{}).Elem(),
		regionalContentSeedersFs,
		[]string{},
		true,
	)
}
func RegionalContentImportMocks() {
	fireback.SeederFromFSImport(
		fireback.QueryDSL{},
		RegionalContentActions.Create,
		reflect.ValueOf(&RegionalContentEntity{}).Elem(),
		&mocks.ViewsFs,
		[]string{},
		false,
	)
}
func RegionalContentWriteQueryMock(ctx fireback.MockQueryContext) {
	for _, lang := range ctx.Languages {
		itemsPerPage := 9999
		if ctx.ItemsPerPage > 0 {
			itemsPerPage = ctx.ItemsPerPage
		}
		f := fireback.QueryDSL{ItemsPerPage: itemsPerPage, Language: lang, WithPreloads: ctx.WithPreloads, Deep: true}
		items, count, _ := RegionalContentActions.Query(f)
		result := fireback.QueryEntitySuccessResult(f, items, count)
		fireback.WriteMockDataToFile(lang, "", "RegionalContent", result)
	}
}
func RegionalContentsActionQueryString(keyword string, page int) ([]string, *fireback.QueryResultMeta, error) {
	searchFields := []string{
		`unique_id %"{keyword}"%`,
		`name %"{keyword}"%`,
	}
	m := func(item *RegionalContentEntity) string {
		label := item.UniqueId
		// if item.Name != nil {
		// 	label += " >>> " + *item.Name
		// }
		return label
	}
	query := fireback.QueryStringCastCli(searchFields, keyword, page)
	items, meta, err := RegionalContentActions.Query(query)
	stringItems := []string{}
	for _, item := range items {
		label := m(item)
		stringItems = append(stringItems, label)
	}
	return stringItems, meta, err
}

var RegionalContentDevCommands = []cli.Command{
	RegionalContentWipeCmd,
	{
		Name:  "mock",
		Usage: "Generates mock records based on the entity definition",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:  "count",
				Usage: "how many activation key do you need to be generated and stored in database",
				Value: 10,
			},
			&cli.BoolFlag{
				Name:  "batch",
				Usage: "Multiple insert into database mode. Might miss children and relations at the moment",
			},
		},
		Action: func(c *cli.Context) error {
			query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
				ActionRequires: []fireback.PermissionInfo{PERM_ROOT_REGIONAL_CONTENT_CREATE},
				AllowOnRoot:    true,
			})
			if c.Bool("batch") {
				RegionalContentActionSeederMultiple(query, c.Int("count"))
			} else {
				RegionalContentActionSeeder(query, c.Int("count"))
			}
			return nil
		},
	},
	{
		Name:    "init",
		Aliases: []string{"i"},
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "format",
				Usage: "Format of the export or import file. Can be 'yaml', 'yml', 'json'",
				Value: "yaml",
			},
		},
		Usage: "Creates a basic seeder file for you, based on the definition module we have. You can populate this file as an example",
		Action: func(c *cli.Context) error {
			seed := RegionalContentActions.SeederInit()
			fireback.CommonInitSeeder(strings.TrimSpace(c.String("format")), seed)
			return nil
		},
	},
	cli.Command{
		Name:  "mlist",
		Usage: "Prints the list of embedded mocks into the app",
		Action: func(c *cli.Context) error {
			if entity, err := fireback.GetSeederFilenames(&mocks.ViewsFs, ""); err != nil {
				fmt.Println(err.Error())
			} else {
				f, _ := json.MarshalIndent(entity, "", "  ")
				fmt.Println(string(f))
			}
			return nil
		},
	},
	cli.Command{
		Name:  "msync",
		Usage: "Tries to sync mocks into the system",
		Action: func(c *cli.Context) error {
			fireback.CommonCliImportEmbedCmd(c,
				RegionalContentActions.Create,
				reflect.ValueOf(&RegionalContentEntity{}).Elem(),
				&mocks.ViewsFs,
			)
			return nil
		},
	},
}
var RegionalContentImportExportCommands = []cli.Command{
	{
		Name:    "validate",
		Aliases: []string{"v"},
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "file",
				Usage: "Validates an import file, such as yaml, json, csv, and gives some insights how the after import it would look like",
				Value: "regional-content-seeder-regional-content.yml",
				// Uncomment before publish, they need to specify
				// Required: true,
			},
			&cli.StringFlag{
				Name:  "format",
				Usage: "Format of the export or import file. Can be 'yaml', 'yml', 'json'",
				Value: "yaml",
			},
		},
		Usage: "Reads a yaml file containing an array of regional-contents, you can run this to validate if your import file is correct, and how it would look like after import",
		Action: func(c *cli.Context) error {
			data := &[]RegionalContentEntity{}
			fireback.ReadYamlFile(c.String("file"), data)
			fmt.Println(data)
			return nil
		},
	},
	cli.Command{
		Name:  "slist",
		Usage: "Prints the list of files attached to this module for syncing or bootstrapping project",
		Action: func(c *cli.Context) error {
			if entity, err := fireback.GetSeederFilenames(regionalContentSeedersFs, ""); err != nil {
				fmt.Println(err.Error())
			} else {
				f, _ := json.MarshalIndent(entity, "", "  ")
				fmt.Println(string(f))
			}
			return nil
		},
	},
	cli.Command{
		Name:  "ssync",
		Usage: "Tries to sync the embedded content into the database, the list could be seen by 'slist' command",
		Action: func(c *cli.Context) error {
			fireback.CommonCliImportEmbedCmd(c,
				RegionalContentActions.Create,
				reflect.ValueOf(&RegionalContentEntity{}).Elem(),
				regionalContentSeedersFs,
			)
			return nil
		},
	},
	cli.Command{
		Name:    "export",
		Aliases: []string{"e"},
		Flags: append(fireback.CommonQueryFlags,
			&cli.StringFlag{
				Name:     "file",
				Usage:    "The address of file you want the csv/yaml/json be exported to",
				Required: true,
			}),
		Usage: "Exports a query results into the csv/yaml/json format",
		Action: func(c *cli.Context) error {
			return fireback.CommonCliExportCmd2(c,
				RegionalContentEntityStream,
				reflect.ValueOf(&RegionalContentEntity{}).Elem(),
				c.String("file"),
				&metas.MetaFs,
				"RegionalContentFieldMap.yml",
				RegionalContentPreloadRelations,
			)
		},
	},
	cli.Command{
		Name: "import",
		Flags: append(
			append(
				fireback.CommonQueryFlags,
				&cli.StringFlag{
					Name:     "file",
					Usage:    "The address of file you want the csv be imported from",
					Required: true,
				}),
			RegionalContentCommonCliFlagsOptional...,
		),
		Usage: "imports csv/yaml/json file and place it and its children into database",
		Action: func(c *cli.Context) error {
			fireback.CommonCliImportCmdAuthorized(c,
				RegionalContentActions.Create,
				reflect.ValueOf(&RegionalContentEntity{}).Elem(),
				c.String("file"),
				&fireback.SecurityModel{
					ActionRequires: []fireback.PermissionInfo{PERM_ROOT_REGIONAL_CONTENT_CREATE},
					AllowOnRoot:    true,
				},
				func() RegionalContentEntity {
					v := CastRegionalContentFromCli(c)
					return *v
				},
			)
			return nil
		},
	},
}
var RegionalContentCliCommands []cli.Command = []cli.Command{
	REGIONAL_CONTENT_ACTION_QUERY.ToCli(),
	REGIONAL_CONTENT_ACTION_TABLE.ToCli(),
	RegionalContentCreateCmd,
	RegionalContentUpdateCmd,
	RegionalContentAskCmd,
	RegionalContentCreateInteractiveCmd,
	fireback.GetCommonRemoveQuery(
		reflect.ValueOf(&RegionalContentEntity{}).Elem(),
		RegionalContentActions.Remove,
	),
}

func RegionalContentCliFn() cli.Command {
	commands := append(RegionalContentImportExportCommands, RegionalContentCliCommands...)
	if !fireback.GetConfig().Production {
		commands = append(commands, RegionalContentDevCommands...)
	}
	return cli.Command{
		Name:        "regionalcontent",
		ShortName:   "rc",
		Description: "RegionalContents module actions",
		Usage:       `Email templates, sms templates or other textual content which can be accessed.`,
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "language",
				Value: "en",
			},
		},
		Subcommands: commands,
	}
}

var REGIONAL_CONTENT_ACTION_TABLE = fireback.Module3Action{
	Name:          "table",
	ActionAliases: []string{"t"},
	Flags:         fireback.CommonQueryFlags,
	Description:   "Table formatted queries all of the entities in database based on the standard query format",
	Action:        RegionalContentActions.Query,
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		fireback.CommonCliTableCmd2(c,
			RegionalContentActions.Query,
			security,
			reflect.ValueOf(&RegionalContentEntity{}).Elem(),
		)
		return nil
	},
}
var REGIONAL_CONTENT_ACTION_QUERY = fireback.Module3Action{
	Method: "GET",
	Url:    "/regional-contents",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_REGIONAL_CONTENT_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			qs := &RegionalContentEntityQs{}
			fireback.HttpQueryEntity(c, RegionalContentActions.Query, qs)
		},
	},
	Format:         "QUERY",
	Action:         RegionalContentActions.Query,
	ResponseEntity: &[]RegionalContentEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "RegionalContentEntity",
	},
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		qs := &RegionalContentEntityQs{}
		fireback.CommonCliQueryCmd3(
			c,
			RegionalContentActions.Query,
			security,
			qs,
		)
		return nil
	},
	CliName:       "query",
	Name:          "query",
	ActionAliases: []string{"q"},
	Flags:         append(fireback.CommonQueryFlags, RegionalContentQsFlags...),
	Description:   "Queries all of the entities in database based on the standard query format (s+)",
}
var REGIONAL_CONTENT_ACTION_EXPORT = fireback.Module3Action{
	Method: "GET",
	Url:    "/regional-contents/export",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_REGIONAL_CONTENT_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpStreamFileChannel(c, RegionalContentActionExport)
		},
	},
	Format:         "QUERY",
	Action:         RegionalContentActionExport,
	ResponseEntity: &[]RegionalContentEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "RegionalContentEntity",
	},
}
var REGIONAL_CONTENT_ACTION_GET_ONE = fireback.Module3Action{
	Method: "GET",
	Url:    "/regional-content/:uniqueId",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_REGIONAL_CONTENT_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpGetEntity(c, RegionalContentActions.GetOne)
		},
	},
	Format:         "GET_ONE",
	Action:         RegionalContentActions.GetOne,
	ResponseEntity: &RegionalContentEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "RegionalContentEntity",
	},
}
var REGIONAL_CONTENT_ACTION_POST_ONE = fireback.Module3Action{
	Name:          "create",
	ActionAliases: []string{"c"},
	Description:   "Create new regionalContent",
	Flags:         RegionalContentCommonCliFlags,
	Method:        "POST",
	Url:           "/regional-content",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_REGIONAL_CONTENT_CREATE},
		AllowOnRoot:    true,
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpPostEntity(c, RegionalContentActions.Create)
		},
	},
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		result, err := fireback.CliPostEntity(c, RegionalContentActions.Create, security)
		fireback.HandleActionInCli(c, result, err, map[string]map[string]string{})
		return err
	},
	Action:         RegionalContentActions.Create,
	Format:         "POST_ONE",
	RequestEntity:  &RegionalContentEntity{},
	ResponseEntity: &RegionalContentEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "RegionalContentEntity",
	},
	In: &fireback.Module3ActionBody{
		Entity: "RegionalContentEntity",
	},
}
var REGIONAL_CONTENT_ACTION_PATCH = fireback.Module3Action{
	Name:          "update",
	ActionAliases: []string{"u"},
	Flags:         RegionalContentCommonCliFlagsOptional,
	Method:        "PATCH",
	Url:           "/regional-content",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_REGIONAL_CONTENT_UPDATE},
		AllowOnRoot:    true,
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpUpdateEntity(c, RegionalContentActions.Update)
		},
	},
	Action:         RegionalContentActions.Update,
	RequestEntity:  &RegionalContentEntity{},
	ResponseEntity: &RegionalContentEntity{},
	Format:         "PATCH_ONE",
	Out: &fireback.Module3ActionBody{
		Entity: "RegionalContentEntity",
	},
	In: &fireback.Module3ActionBody{
		Entity: "RegionalContentEntity",
	},
}
var REGIONAL_CONTENT_ACTION_PATCH_BULK = fireback.Module3Action{
	Method: "PATCH",
	Url:    "/regional-contents",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_REGIONAL_CONTENT_UPDATE},
		AllowOnRoot:    true,
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpUpdateEntities(c, RegionalContentActionBulkUpdate)
		},
	},
	Action:         RegionalContentActionBulkUpdate,
	Format:         "PATCH_BULK",
	RequestEntity:  &fireback.BulkRecordRequest[RegionalContentEntity]{},
	ResponseEntity: &fireback.BulkRecordRequest[RegionalContentEntity]{},
	Out: &fireback.Module3ActionBody{
		Entity: "RegionalContentEntity",
	},
	In: &fireback.Module3ActionBody{
		Entity: "RegionalContentEntity",
	},
}
var REGIONAL_CONTENT_ACTION_DELETE = fireback.Module3Action{
	Method: "DELETE",
	Url:    "/regional-content",
	Format: "DELETE_DSL",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_REGIONAL_CONTENT_DELETE},
		AllowOnRoot:    true,
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpRemoveEntity(c, RegionalContentActions.Remove)
		},
	},
	Action:         RegionalContentActions.Remove,
	RequestEntity:  &fireback.DeleteRequest{},
	ResponseEntity: &fireback.DeleteResponse{},
	TargetEntity:   &RegionalContentEntity{},
}

/**
 *	Override this function on RegionalContentEntityHttp.go,
 *	In order to add your own http
 **/
var AppendRegionalContentRouter = func(r *[]fireback.Module3Action) {}

func GetRegionalContentModule3Actions() []fireback.Module3Action {
	routes := []fireback.Module3Action{
		REGIONAL_CONTENT_ACTION_QUERY,
		REGIONAL_CONTENT_ACTION_EXPORT,
		REGIONAL_CONTENT_ACTION_GET_ONE,
		REGIONAL_CONTENT_ACTION_POST_ONE,
		REGIONAL_CONTENT_ACTION_PATCH,
		REGIONAL_CONTENT_ACTION_PATCH_BULK,
		REGIONAL_CONTENT_ACTION_DELETE,
	}
	// Append user defined functions
	AppendRegionalContentRouter(&routes)
	return routes
}

var PERM_ROOT_REGIONAL_CONTENT = fireback.PermissionInfo{
	CompleteKey: "root.manage.abac.regional-content.*",
	Name:        "Entire regional content actions (*)",
	Description: "",
}
var PERM_ROOT_REGIONAL_CONTENT_DELETE = fireback.PermissionInfo{
	CompleteKey: "root.manage.abac.regional-content.delete",
	Name:        "Delete regional content",
	Description: "",
}
var PERM_ROOT_REGIONAL_CONTENT_CREATE = fireback.PermissionInfo{
	CompleteKey: "root.manage.abac.regional-content.create",
	Name:        "Create regional content",
	Description: "",
}
var PERM_ROOT_REGIONAL_CONTENT_UPDATE = fireback.PermissionInfo{
	CompleteKey: "root.manage.abac.regional-content.update",
	Name:        "Update regional content",
	Description: "",
}
var PERM_ROOT_REGIONAL_CONTENT_QUERY = fireback.PermissionInfo{
	CompleteKey: "root.manage.abac.regional-content.query",
	Name:        "Query regional content",
	Description: "",
}
var ALL_REGIONAL_CONTENT_PERMISSIONS = []fireback.PermissionInfo{
	PERM_ROOT_REGIONAL_CONTENT_DELETE,
	PERM_ROOT_REGIONAL_CONTENT_CREATE,
	PERM_ROOT_REGIONAL_CONTENT_UPDATE,
	PERM_ROOT_REGIONAL_CONTENT_QUERY,
	PERM_ROOT_REGIONAL_CONTENT,
}
var RegionalContentKeyGroup = newRegionalContentKeyGroup()

func newRegionalContentKeyGroup() *xRegionalContentKeyGroup {
	return &xRegionalContentKeyGroup{
		SMS_OTP:   "SMS_OTP",
		EMAIL_OTP: "EMAIL_OTP",
	}
}

type xRegionalContentKeyGroup struct {
	SMS_OTP   string
	EMAIL_OTP string
}

func NewRegionalContentCreatedEvent(
	payload *RegionalContentEntity,
	query *fireback.QueryDSL,
) (*fireback.Event, error) {
	event := &fireback.Event{
		Name:    "RegionalContentCreated",
		Payload: payload,
		Security: &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{
				PERM_ROOT_REGIONAL_CONTENT_QUERY,
			},
		},
		CacheKey: "*abac.RegionalContentEntity",
	}
	// Apply the source of the event based on querydsl
	fireback.ApplyQueryDslContextToEvent(event, *query)
	return event, nil
}
func NewRegionalContentUpdatedEvent(
	payload *RegionalContentEntity,
	query *fireback.QueryDSL,
) (*fireback.Event, error) {
	event := &fireback.Event{
		Name:    "RegionalContentUpdated",
		Payload: payload,
		Security: &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{
				PERM_ROOT_REGIONAL_CONTENT_QUERY,
			},
		},
		CacheKey: "*abac.RegionalContentEntity",
	}
	// Apply the source of the event based on querydsl
	fireback.ApplyQueryDslContextToEvent(event, *query)
	return event, nil
}

var RegionalContentEntityBundle = fireback.EntityBundle{
	Permissions: ALL_REGIONAL_CONTENT_PERMISSIONS,
	// Cli command has been exluded, since we use module to wrap all the entities
	// to be more easier to wrap up.
	// Create your own bundle if you need with Cli
	//CliCommands: []cli.Command{
	//	RegionalContentCliFn(),
	//},
	Actions:      GetRegionalContentModule3Actions(),
	MockProvider: RegionalContentImportMocks,
	AutoMigrationEntities: []interface{}{
		&RegionalContentEntity{},
	},
}
