package abac

/*
*	Generated by fireback 1.2.2
*	Written by Ali Torabi.
*	Checkout the repository for licenses and contribution: https://github.com/torabian/fireback
 */
import (
	"embed"
	"encoding/json"
	"fmt"
	"github.com/gin-gonic/gin"
	jsoniter "github.com/json-iterator/go"
	"github.com/schollz/progressbar/v3"
	metas "github.com/torabian/fireback/modules/abac/metas"
	mocks "github.com/torabian/fireback/modules/abac/mocks/User"
	seeders "github.com/torabian/fireback/modules/abac/seeders/User"
	"github.com/torabian/fireback/modules/fireback"
	"github.com/urfave/cli"
	"gopkg.in/yaml.v2"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"log"
	reflect "reflect"
	"strings"
	"time"
)

var userSeedersFs = &seeders.ViewsFs

func ResetUserSeeders(fs *embed.FS) {
	userSeedersFs = fs
}

type UserPrimaryAddress struct {
	// Street address, building number
	AddressLine1 string `json:"addressLine1" xml:"addressLine1" yaml:"addressLine1"        `
	// Apartment, suite, floor (optional)
	AddressLine2 fireback.String `json:"addressLine2" xml:"addressLine2" yaml:"addressLine2"        `
	// City or locality
	City fireback.String `json:"city" xml:"city" yaml:"city"        `
	// State, region, or province
	StateOrProvince fireback.String `json:"stateOrProvince" xml:"stateOrProvince" yaml:"stateOrProvince"        `
	// ZIP or postal code
	PostalCode fireback.String `json:"postalCode" xml:"postalCode" yaml:"postalCode"        `
	// ISO 3166-1 alpha-2 (e.g., \"US\", \"DE\")
	CountryCode fireback.String `json:"countryCode" xml:"countryCode" yaml:"countryCode"        `
	LinkedTo    *UserEntity     `yaml:"-" gorm:"-" json:"-" sql:"-" xml:"-"`
}

func (x *UserPrimaryAddress) RootObjectName() string {
	return "UserEntity"
}

type UserEntityQs struct {
	FirstName      fireback.QueriableField `cli:"first-name" table:"user" column:"first_name" qs:"firstName"`
	LastName       fireback.QueriableField `cli:"last-name" table:"user" column:"last_name" qs:"lastName"`
	Photo          fireback.QueriableField `cli:"photo" table:"user" column:"photo" qs:"photo"`
	Gender         fireback.QueriableField `cli:"gender" table:"user" column:"gender" qs:"gender"`
	Title          fireback.QueriableField `cli:"title" table:"user" column:"title" qs:"title"`
	BirthDate      fireback.QueriableField `cli:"birth-date" table:"user" column:"birth_date" qs:"birthDate"`
	Avatar         fireback.QueriableField `cli:"avatar" table:"user" column:"avatar" qs:"avatar"`
	LastIpAddress  fireback.QueriableField `cli:"last-ip-address" table:"user" column:"last_ip_address" qs:"lastIpAddress"`
	PrimaryAddress struct {
		AddressLine1    fireback.QueriableField `cli:"primary-address.address-line1" table:"user" column:"address_line1" qs:"addressLine1"`
		AddressLine2    fireback.QueriableField `cli:"primary-address.address-line2" table:"user" column:"address_line2" qs:"addressLine2"`
		City            fireback.QueriableField `cli:"primary-address.city" table:"user" column:"city" qs:"city"`
		StateOrProvince fireback.QueriableField `cli:"primary-address.state-or-province" table:"user" column:"state_or_province" qs:"stateOrProvince"`
		PostalCode      fireback.QueriableField `cli:"primary-address.postal-code" table:"user" column:"postal_code" qs:"postalCode"`
		CountryCode     fireback.QueriableField `cli:"primary-address.country-code" table:"user" column:"country_code" qs:"countryCode"`
	}
}

func (x *UserEntityQs) GetQuery() string {
	return fireback.GenerateQueryStringStyle(reflect.ValueOf(x), "")
}

var UserQsFlags = []cli.Flag{
	&cli.StringFlag{
		Name:  "first-name",
		Usage: "",
	},
	&cli.StringFlag{
		Name:  "last-name",
		Usage: "",
	},
	&cli.StringFlag{
		Name:  "photo",
		Usage: "",
	},
	&cli.StringFlag{
		Name:  "gender",
		Usage: "",
	},
	&cli.StringFlag{
		Name:  "title",
		Usage: "",
	},
	&cli.StringFlag{
		Name:  "birth-date",
		Usage: "",
	},
	&cli.StringFlag{
		Name:  "avatar",
		Usage: "",
	},
	&cli.StringFlag{
		Name:  "last-ip-address",
		Usage: "User last connecting ip address",
	},
	&cli.StringFlag{
		Name:  "primary-address-address-line1",
		Usage: "Street address, building number",
	},
	&cli.StringFlag{
		Name:  "primary-address-address-line2",
		Usage: "Apartment, suite, floor (optional)",
	},
	&cli.StringFlag{
		Name:  "primary-address-city",
		Usage: "City or locality",
	},
	&cli.StringFlag{
		Name:  "primary-address-state-or-province",
		Usage: "State, region, or province",
	},
	&cli.StringFlag{
		Name:  "primary-address-postal-code",
		Usage: "ZIP or postal code",
	},
	&cli.StringFlag{
		Name:  "primary-address-country-code",
		Usage: "ISO 3166-1 alpha-2 (e.g., \"US\", \"DE\")",
	},
}

type UserEntity struct {
	// Defines the visibility of the record in the table.
	// Visibility is a detailed topic, you can check all of the visibility values in fireback/visibility.go
	// by default, visibility of record are 0, means they are protected by the workspace
	// which are being created, and visible to every member of the workspace
	Visibility fireback.String `json:"visibility,omitempty" yaml:"visibility,omitempty" xml:"visibility,omitempty"`
	// The unique-id of the workspace which content belongs to. Upon creation this will be designated
	// to the selected workspace by user, if they have write access. You can change this value
	// or prevent changes to it manually (on root features for example modifying other workspace)
	WorkspaceId fireback.String `json:"workspaceId,omitempty" xml:"workspaceId,omitempty" yaml:"workspaceId,omitempty"`
	// The unique-id of the parent table, which this record is being linked to.
	// used internally for making relations in fireback, generally does not need manual changes
	// or modification by the developer or user. For example, if you have a object inside an object
	// the unique-id of the parent will be written in the child.
	LinkerId fireback.String `json:"linkerId,omitempty" xml:"linkerId,omitempty" yaml:"linkerId,omitempty"`
	// Used for recursive or parent-child operations. Some tables, are having nested relations,
	// and this field makes the table self refrenceing. ParentId needs to exist in the table before
	// creating of modifying a record.
	ParentId fireback.String `json:"parentId,omitempty" xml:"parentId,omitempty" yaml:"parentId,omitempty"`
	// Makes a field deletable. Some records should not be deletable at all.
	// default it's true.
	IsDeletable *bool `json:"isDeletable,omitempty" xml:"isDeletable,omitempty" yaml:"isDeletable,omitempty" gorm:"default:true"`
	// Makes a field updatable. Some records should not be updatable at all.
	// default it's true.
	IsUpdatable *bool `json:"isUpdatable,omitempty" xml:"isUpdatable,omitempty" yaml:"isUpdatable,omitempty" gorm:"default:true"`
	// The unique-id of the user which is creating the record, or the record belongs to.
	// Administration might want to change this to any user, by default Fireback fills
	// it to the current authenticated user.
	UserId fireback.String `json:"userId,omitempty" xml:"userId,omitempty" yaml:"userId,omitempty"`
	// General mechanism to rank the elements. From code perspective, it's just a number,
	// but you can sort it based on any logic for records to make a ranking, sorting.
	// they should not be unique across a table.
	Rank fireback.Int64 `json:"rank,omitempty" yaml:"rank,omitempty" xml:"rank,omitempty" gorm:"type:int;name:rank"`
	// Primary numeric key in the database. This value is not meant to be exported to public
	// or be used to access data at all. Rather a mechanism of indexing columns internally
	// or cursor pagination in future releases of fireback, or better search performance.
	ID uint `gorm:"primaryKey;autoIncrement" json:"-" yaml:"-" xml:"-"`
	// Unique id of the record across the table. This value will be accessed from public APIs,
	// and many other places intead of numeric ID property.
	// Upon generation, a UUID automatically is being assigned, and if user has specified the
	// Unique id in the post body, it will be used. This mechanism allows to manage unsaved
	// content on front-end much easier than requiring parent to exists first.
	UniqueId string `json:"uniqueId,omitempty" xml:"uniqueId,omitempty" gorm:"unique;not null;size:100;" yaml:"uniqueId,omitempty"`
	// The time that the record has been updated in datetime.
	// the field will be automatically populated by gorm orm.
	UpdatedAt *time.Time `json:"updatedAt,omitempty" xml:"updatedAt,omitempty" yaml:"updatedAt,omitempty"`
	// The time that the record has been created in datetime.
	// the field will be automatically populated by gorm orm.
	CreatedAt *time.Time `json:"createdAt,omitempty" xml:"createdAt,omitempty" yaml:"createdAt,omitempty"`
	// The time that the record has been deleted softly (means the data still exists in database, but no longer visible to any feature) in nano datatime
	// you need to make sure check this field if writing custom sql queries.
	// the field will be automatically populated by gorm orm.
	DeletedAt *time.Time `json:"deletedAt,omitempty" xml:"deletedAt,omitempty" yaml:"deletedAt,omitempty"`
	// Record creation date time formatting based on locale of the headers, or other
	// possible factors.
	CreatedFormatted string `json:"createdFormatted,omitempty" xml:"createdFormatted,omitempty" yaml:"createdFormatted,omitempty" sql:"-" gorm:"-"`
	// Record update date time formatting based on locale of the headers, or other
	// possible factors.
	UpdatedFormatted string         `json:"updatedFormatted,omitempty" xml:"updatedFormatted,omitempty" yaml:"updatedFormatted,omitempty" sql:"-" gorm:"-"`
	FirstName        string         `json:"firstName" xml:"firstName" yaml:"firstName"  validate:"required"        `
	LastName         string         `json:"lastName" xml:"lastName" yaml:"lastName"  validate:"required"        `
	Photo            string         `json:"photo" xml:"photo" yaml:"photo"        `
	Gender           fireback.Int   `json:"gender" xml:"gender" yaml:"gender"        `
	Title            string         `json:"title" xml:"title" yaml:"title"        `
	BirthDate        fireback.XDate `json:"birthDate" xml:"birthDate" yaml:"birthDate"        `
	// Date range is a complex date storage
	BirthDateDateInfo fireback.XDateMetaData `json:"birthDateDateInfo" yaml:"birthDateDateInfo" xml:"birthDateDateInfo" sql:"-" gorm:"-"`
	Avatar            string                 `json:"avatar" xml:"avatar" yaml:"avatar"        `
	// User last connecting ip address
	LastIpAddress string `json:"lastIpAddress" xml:"lastIpAddress" yaml:"lastIpAddress"        `
	// User primary address location. Can be useful for simple projects that a user is associated with a single address.
	PrimaryAddress *UserPrimaryAddress `json:"primaryAddress" xml:"primaryAddress" yaml:"primaryAddress"    gorm:"embedded"      `
	Children       []*UserEntity       `csv:"-" gorm:"-" sql:"-" json:"children,omitempty" xml:"children,omitempty"  yaml:"children,omitempty"`
	LinkedTo       *UserEntity         `csv:"-" yaml:"-" gorm:"-" json:"-" sql:"-" xml:"-"`
}

func UserEntityStream(q fireback.QueryDSL) (chan []*UserEntity, *fireback.QueryResultMeta, error) {
	cn := make(chan []*UserEntity)
	q.ItemsPerPage = 50
	q.StartIndex = 0
	_, qrm, err := UserActions.Query(q)
	if err != nil {
		return nil, nil, err
	}
	go func() {
		defer close(cn)
		for i := 0; i <= int(qrm.TotalAvailableItems)-1; i++ {
			items, _, _ := UserActions.Query(q)
			i += q.ItemsPerPage
			q.StartIndex = i
			cn <- items
		}
	}()
	return cn, qrm, nil
}

type UserEntityList struct {
	Items []*UserEntity
}

func NewUserEntityList(items []*UserEntity) *UserEntityList {
	return &UserEntityList{
		Items: items,
	}
}
func (x *UserEntityList) Json() string {
	if x != nil {
		str, _ := json.MarshalIndent(x, "", "  ")
		return (string(str))
	}
	return ""
}
func (x *UserEntityList) ToTree() *fireback.TreeOperation[UserEntity] {
	return fireback.NewTreeOperation(
		x.Items,
		func(t *UserEntity) string {
			if !t.ParentId.Valid {
				return ""
			}
			return t.ParentId.String
		},
		func(t *UserEntity) string {
			return t.UniqueId
		},
	)
}

var UserPreloadRelations []string = []string{}

type userActionsSig struct {
	Update         func(query fireback.QueryDSL, dto *UserEntity) (*UserEntity, *fireback.IError)
	Create         func(dto *UserEntity, query fireback.QueryDSL) (*UserEntity, *fireback.IError)
	Upsert         func(dto *UserEntity, query fireback.QueryDSL) (*UserEntity, *fireback.IError)
	SeederInit     func() *UserEntity
	Remove         func(query fireback.QueryDSL) (int64, *fireback.IError)
	MultiInsert    func(dtos []*UserEntity, query fireback.QueryDSL) ([]*UserEntity, *fireback.IError)
	GetOne         func(query fireback.QueryDSL) (*UserEntity, *fireback.IError)
	GetByWorkspace func(query fireback.QueryDSL) (*UserEntity, *fireback.IError)
	Query          func(query fireback.QueryDSL) ([]*UserEntity, *fireback.QueryResultMeta, error)
}

var UserActions userActionsSig = userActionsSig{
	Update:         UserActionUpdateFn,
	Create:         UserActionCreateFn,
	Upsert:         UserActionUpsertFn,
	Remove:         UserActionRemoveFn,
	SeederInit:     UserActionSeederInitFn,
	MultiInsert:    UserMultiInsertFn,
	GetOne:         UserActionGetOneFn,
	GetByWorkspace: UserActionGetByWorkspaceFn,
	Query:          UserActionQueryFn,
}

func UserActionUpsertFn(dto *UserEntity, query fireback.QueryDSL) (*UserEntity, *fireback.IError) {
	return nil, nil
}

var USER_EVENT_CREATED = "user.created"
var USER_EVENT_UPDATED = "user.updated"
var USER_EVENT_DELETED = "user.deleted"
var USER_EVENTS = []string{
	USER_EVENT_CREATED,
	USER_EVENT_UPDATED,
	USER_EVENT_DELETED,
}

type UserFieldMap struct {
	FirstName      fireback.TranslatedString `yaml:"firstName"`
	LastName       fireback.TranslatedString `yaml:"lastName"`
	Photo          fireback.TranslatedString `yaml:"photo"`
	Gender         fireback.TranslatedString `yaml:"gender"`
	Title          fireback.TranslatedString `yaml:"title"`
	BirthDate      fireback.TranslatedString `yaml:"birthDate"`
	Avatar         fireback.TranslatedString `yaml:"avatar"`
	LastIpAddress  fireback.TranslatedString `yaml:"lastIpAddress"`
	PrimaryAddress fireback.TranslatedString `yaml:"primaryAddress"`
}

var UserEntityMetaConfig map[string]int64 = map[string]int64{}
var UserEntityJsonSchema = fireback.ExtractEntityFields(reflect.ValueOf(&UserEntity{}))

func entityUserFormatter(dto *UserEntity, query fireback.QueryDSL) {
	if dto == nil {
		return
	}
	dto.BirthDateDateInfo = fireback.ComputeXDateMetaData(&dto.BirthDate, query)
}
func UserActionSeederMultiple(query fireback.QueryDSL, count int) {
	successInsert := 0
	failureInsert := 0
	batchSize := 100
	bar := progressbar.Default(int64(count))
	// Collect entities in batches
	var entitiesBatch []*UserEntity
	for i := 1; i <= count; i++ {
		entity := UserActions.SeederInit()
		entitiesBatch = append(entitiesBatch, entity)
		// When batch size is reached, perform the batch insert
		if len(entitiesBatch) == batchSize || i == count {
			// Insert batch
			_, err := UserActions.MultiInsert(entitiesBatch, query)
			if err == nil {
				successInsert += len(entitiesBatch)
			} else {
				fmt.Println(err)
				failureInsert += len(entitiesBatch)
			}
			// Clear the batch after insert
			entitiesBatch = nil
		}
		bar.Add(1)
	}
	fmt.Println("Success", successInsert, "Failure", failureInsert)
}
func UserActionSeeder(query fireback.QueryDSL, count int) {
	successInsert := 0
	failureInsert := 0
	bar := progressbar.Default(int64(count))
	for i := 1; i <= count; i++ {
		entity := UserActions.SeederInit()
		_, err := UserActions.Create(entity, query)
		if err == nil {
			successInsert++
		} else {
			fmt.Println(err)
			failureInsert++
		}
		bar.Add(1)
	}
	fmt.Println("Success", successInsert, "Failure", failureInsert)
}
func (x *UserEntity) Seeder() string {
	obj := UserActions.SeederInit()
	v, _ := json.MarshalIndent(obj, "", "  ")
	return string(v)
}
func UserActionSeederInitFn() *UserEntity {
	entity := &UserEntity{
		PrimaryAddress: &UserPrimaryAddress{},
	}
	return entity
}
func UserAssociationCreate(dto *UserEntity, query fireback.QueryDSL) error {
	return nil
}

/**
* These kind of content are coming from another entity, which is indepndent module
* If we want to create them, we need to do it before. This is not association.
**/
func UserRelationContentCreate(dto *UserEntity, query fireback.QueryDSL) error {
	return nil
}
func UserRelationContentUpdate(dto *UserEntity, query fireback.QueryDSL) error {
	return nil
}
func UserPolyglotUpdateHandler(dto *UserEntity, query fireback.QueryDSL) {
	if dto == nil {
		return
	}
}

/**
 * This will be validating your entity fully. Important note is that, you add validate:* tag
 * in your entity, it will automatically work here. For slices inside entity, make sure you add
 * extra line of AppendSliceErrors, otherwise they won't be detected
 */
func UserValidator(dto *UserEntity, isPatch bool) *fireback.IError {
	err := fireback.CommonStructValidatorPointer(dto, isPatch)
	return err
}

// Creates a set of natural language queries, which can be used with
// AI tools to create content or help with some tasks
var UserAskCmd cli.Command = cli.Command{
	Name:  "nlp",
	Usage: "Set of natural language queries which helps creating content or data",
	Subcommands: []cli.Command{
		{
			Name:  "sample",
			Usage: "Asks for generating sample by giving an example data",
			Flags: []cli.Flag{
				&cli.StringFlag{
					Name:  "format",
					Usage: "Format of the export or import file. Can be 'yaml', 'yml', 'json'",
					Value: "yaml",
				},
				&cli.IntFlag{
					Name:  "count",
					Usage: "How many samples to ask",
					Value: 30,
				},
			},
			Action: func(c *cli.Context) error {
				v := &UserEntity{}
				format := c.String("format")
				request := "\033[1m" + `
I need you to create me an array of exact signature as the example given below,
with at least ` + fmt.Sprint(c.String("count")) + ` items, mock the content with few words, and guess the possible values
based on the common sense. I need the output to be a valid ` + format + ` file.
Make sure you wrap the entire array in 'items' field. Also before that, I provide some explanation of each field:
FirstName: (type: string) Description: 
LastName: (type: string) Description: 
Photo: (type: string) Description: 
Gender: (type: int?) Description: 
Title: (type: string) Description: 
BirthDate: (type: date) Description: 
Avatar: (type: string) Description: 
LastIpAddress: (type: string) Description: User last connecting ip address
PrimaryAddress: (type: embed) Description: User primary address location. Can be useful for simple projects that a user is associated with a single address.
And here is the actual object signature:
` + v.Seeder() + `
`
				fmt.Println(request)
				return nil
			},
		},
	},
}

func UserEntityPreSanitize(dto *UserEntity, query fireback.QueryDSL) {
}
func UserEntityBeforeCreateAppend(dto *UserEntity, query fireback.QueryDSL) {
	if dto.UniqueId == "" {
		dto.UniqueId = fireback.UUID()
	}
	dto.WorkspaceId = fireback.NewString(query.WorkspaceId)
	dto.UserId = fireback.NewString(query.UserId)
	UserRecursiveAddUniqueId(dto, query)
}
func UserRecursiveAddUniqueId(dto *UserEntity, query fireback.QueryDSL) {
}

/*
*
	Batch inserts, do not have all features that create
	operation does. Use it with unnormalized content,
	or read the source code carefully.
  This is not marked as an action, because it should not be available publicly
  at this moment.
*
*/
func UserMultiInsertFn(dtos []*UserEntity, query fireback.QueryDSL) ([]*UserEntity, *fireback.IError) {
	if len(dtos) > 0 {
		for index := range dtos {
			UserEntityPreSanitize(dtos[index], query)
			UserEntityBeforeCreateAppend(dtos[index], query)
		}
		var dbref *gorm.DB = nil
		if query.Tx == nil {
			dbref = fireback.GetDbRef()
		} else {
			dbref = query.Tx
		}
		query.Tx = dbref
		err := dbref.Create(&dtos).Error
		if err != nil {
			return nil, fireback.GormErrorToIError(err)
		}
	}
	return dtos, nil
}
func UserActionBatchCreateFn(dtos []*UserEntity, query fireback.QueryDSL) ([]*UserEntity, *fireback.IError) {
	if dtos != nil && len(dtos) > 0 {
		items := []*UserEntity{}
		for _, item := range dtos {
			s, err := UserActions.Create(item, query)
			if err != nil {
				return nil, err
			}
			items = append(items, s)
		}
		return items, nil
	}
	return dtos, nil
}
func UserDeleteEntireChildren(query fireback.QueryDSL, dto *UserEntity) *fireback.IError {
	// intentionally removed this. It's hard to implement it, and probably wrong without
	// proper on delete cascade
	return nil
}
func UserActionCreateFn(dto *UserEntity, query fireback.QueryDSL) (*UserEntity, *fireback.IError) {
	// 1. Validate always
	if iError := UserValidator(dto, false); iError != nil {
		return nil, iError
	}
	// 1.5 Sanitize the content coming of the front-end
	UserEntityPreSanitize(dto, query)
	// 2. Append the necessary information about user, workspace
	UserEntityBeforeCreateAppend(dto, query)
	// 3. Create other entities if we want select from them
	UserRelationContentCreate(dto, query)
	// 4. Create the entity
	var dbref *gorm.DB = nil
	if query.Tx == nil {
		dbref = fireback.GetDbRef()
	} else {
		dbref = query.Tx
	}
	query.Tx = dbref
	err := dbref.Create(&dto).Error
	if err != nil {
		err := fireback.GormErrorToIError(err)
		return nil, err
	}
	// 5. Create sub entities, objects or arrays, association to other entities
	UserAssociationCreate(dto, query)
	// 6. Fire the event into system
	actionEvent, eventErr := NewUserCreatedEvent(dto, &query)
	if actionEvent != nil && eventErr == nil {
		fireback.GetEventBusInstance().FireEvent(query, *actionEvent)
	} else {
		log.Default().Panicln("Creating event has failed for %v", dto)
	}
	/*
		event.MustFire(USER_EVENT_CREATED, event.M{
			"entity":   dto,
			"entityKey": fireback.GetTypeString(&UserEntity{}),
			"target":   "workspace",
			"unqiueId": query.WorkspaceId,
		})
	*/
	return dto, nil
}
func UserActionGetOneFn(query fireback.QueryDSL) (*UserEntity, *fireback.IError) {
	refl := reflect.ValueOf(&UserEntity{})
	item, err := fireback.GetOneEntity[UserEntity](query, refl)
	entityUserFormatter(item, query)
	return item, err
}
func UserActionGetByWorkspaceFn(query fireback.QueryDSL) (*UserEntity, *fireback.IError) {
	refl := reflect.ValueOf(&UserEntity{})
	item, err := fireback.GetOneByWorkspaceEntity[UserEntity](query, refl)
	entityUserFormatter(item, query)
	return item, err
}
func UserActionQueryFn(query fireback.QueryDSL) ([]*UserEntity, *fireback.QueryResultMeta, error) {
	refl := reflect.ValueOf(&UserEntity{})
	items, meta, err := fireback.QueryEntitiesPointer[UserEntity](query, refl)
	for _, item := range items {
		entityUserFormatter(item, query)
	}
	return items, meta, err
}

var userMemoryItems []*UserEntity = []*UserEntity{}

func UserEntityIntoMemory() {
	q := fireback.QueryDSL{
		ItemsPerPage: 500,
		StartIndex:   0,
	}
	_, qrm, _ := UserActions.Query(q)
	for i := 0; i <= int(qrm.TotalAvailableItems)-1; i++ {
		items, _, _ := UserActions.Query(q)
		userMemoryItems = append(userMemoryItems, items...)
		i += q.ItemsPerPage
		q.StartIndex = i
	}
}
func UserMemGet(id uint) *UserEntity {
	for _, item := range userMemoryItems {
		if item.ID == id {
			return item
		}
	}
	return nil
}
func UserMemJoin(items []uint) []*UserEntity {
	res := []*UserEntity{}
	for _, item := range items {
		v := UserMemGet(item)
		if v != nil {
			res = append(res, v)
		}
	}
	return res
}
func UserUpdateExec(dbref *gorm.DB, query fireback.QueryDSL, fields *UserEntity) (*UserEntity, *fireback.IError) {
	uniqueId := fields.UniqueId
	query.TriggerEventName = USER_EVENT_UPDATED
	UserEntityPreSanitize(fields, query)
	var item UserEntity
	var itemRefetched UserEntity
	// If the entity is distinct by workspace, then the Query.WorkspaceId
	// which is selected is being used as the condition for create or update
	// if not, the unique Id is being used
	cond2 := &UserEntity{UniqueId: uniqueId}
	q := dbref.
		Where(cond2).
		FirstOrCreate(&item)
	err := q.UpdateColumns(fields).Error
	if err != nil {
		return nil, fireback.GormErrorToIError(err)
	}
	query.Tx = dbref
	UserRelationContentUpdate(fields, query)
	UserPolyglotUpdateHandler(fields, query)
	if ero := UserDeleteEntireChildren(query, fields); ero != nil {
		return nil, ero
	}
	// @meta(update has many)
	err = dbref.
		Preload(clause.Associations).
		Where(&UserEntity{UniqueId: uniqueId}).
		First(&itemRefetched).Error
	if err != nil {
		return nil, fireback.GormErrorToIError(err)
	}
	actionEvent, eventErr := NewUserUpdatedEvent(fields, &query)
	if actionEvent != nil && eventErr == nil {
		fireback.GetEventBusInstance().FireEvent(query, *actionEvent)
	} else {
		log.Default().Panicln("Updating event has failed for %v", fields)
	}
	/*
	   event.MustFire(query.TriggerEventName, event.M{
	     "entity":   &item,
	     "target":   "workspace",
	     "unqiueId": query.WorkspaceId,
	   })*/
	return &itemRefetched, nil
}
func UserActionUpdateFn(query fireback.QueryDSL, fields *UserEntity) (*UserEntity, *fireback.IError) {
	if fields == nil {
		return nil, fireback.Create401Error(&fireback.FirebackMessages.BodyIsMissing, []string{})
	}
	// 1. Validate always
	if iError := UserValidator(fields, true); iError != nil {
		return nil, iError
	}
	// Let's not add this. I am not sure of the consequences
	// UserRecursiveAddUniqueId(fields, query)
	var dbref *gorm.DB = nil
	if query.Tx == nil {
		dbref = fireback.GetDbRef()
		var item *UserEntity
		vf := dbref.Transaction(func(tx *gorm.DB) error {
			dbref = tx
			var err *fireback.IError
			item, err = UserUpdateExec(dbref, query, fields)
			if err == nil {
				return nil
			} else {
				return err
			}
		})
		return item, fireback.CastToIError(vf)
	} else {
		dbref = query.Tx
		return UserUpdateExec(dbref, query, fields)
	}
}

var UserWipeCmd cli.Command = cli.Command{
	Name:  "wipe",
	Usage: "Wipes entire users ",
	Action: func(c *cli.Context) error {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{PERM_ROOT_USER_DELETE},
			AllowOnRoot:    true,
		})
		count, _ := UserActionWipeClean(query)
		fmt.Println("Removed", count, "of entities")
		return nil
	},
}

func UserActionRemoveFn(query fireback.QueryDSL) (int64, *fireback.IError) {
	refl := reflect.ValueOf(&UserEntity{})
	query.ActionRequires = []fireback.PermissionInfo{PERM_ROOT_USER_DELETE}
	return fireback.RemoveEntity[UserEntity](query, refl)
}
func UserActionWipeClean(query fireback.QueryDSL) (int64, error) {
	var err error
	var count int64 = 0
	{
		subCount, subErr := fireback.WipeCleanEntity[UserEntity]()
		if subErr != nil {
			fmt.Println("Error while wiping 'UserEntity'", subErr)
			return count, subErr
		} else {
			count += subCount
		}
	}
	return count, err
}
func UserActionBulkUpdate(
	query fireback.QueryDSL, dto *fireback.BulkRecordRequest[UserEntity]) (
	*fireback.BulkRecordRequest[UserEntity], *fireback.IError,
) {
	result := []*UserEntity{}
	err := fireback.GetDbRef().Transaction(func(tx *gorm.DB) error {
		query.Tx = tx
		for _, record := range dto.Records {
			item, err := UserActions.Update(query, record)
			if err != nil {
				return err
			} else {
				result = append(result, item)
			}
		}
		return nil
	})
	if err == nil {
		return dto, nil
	}
	return nil, err.(*fireback.IError)
}
func (x *UserEntity) Json() string {
	if x != nil {
		str, _ := json.MarshalIndent(x, "", "  ")
		return (string(str))
	}
	return ""
}

var UserEntityMeta = fireback.TableMetaData{
	EntityName:    "User",
	ExportKey:     "users",
	TableNameInDb: "user_entities",
	EntityObject:  &UserEntity{},
	ExportStream:  UserActionExportT,
	ImportQuery:   UserActionImport,
}

func UserActionExport(
	query fireback.QueryDSL,
) (chan []byte, *fireback.IError) {
	return fireback.YamlExporterChannel[UserEntity](query, UserActions.Query, UserPreloadRelations)
}
func UserActionExportT(
	query fireback.QueryDSL,
) (chan []interface{}, *fireback.IError) {
	return fireback.YamlExporterChannelT[UserEntity](query, UserActions.Query, UserPreloadRelations)
}
func UserActionImport(
	dto interface{}, query fireback.QueryDSL,
) *fireback.IError {
	var json = jsoniter.ConfigCompatibleWithStandardLibrary
	var content UserEntity
	cx, err2 := json.Marshal(dto)
	if err2 != nil {
		return fireback.Create401Error(&fireback.FirebackMessages.InvalidContent, []string{})
	}
	json.Unmarshal(cx, &content)
	_, err := UserActions.Create(&content, query)
	return err
}

var UserCommonCliFlags = []cli.Flag{
	&cli.StringFlag{
		Name:     "wid",
		Required: false,
		Usage:    "Provide workspace id, if you want to change the data workspace",
	},
	&cli.StringFlag{
		Name:     "uid",
		Required: false,
		Usage:    "Unique Id - external unique hash to query entity",
	},
	&cli.StringFlag{
		Name:     "pid",
		Required: false,
		Usage:    " Parent record id of the same type",
	},
	&cli.StringFlag{
		Name:     "first-name",
		Required: true,
		Usage:    `firstName (string)`,
	},
	&cli.StringFlag{
		Name:     "last-name",
		Required: true,
		Usage:    `lastName (string)`,
	},
	&cli.StringFlag{
		Name:     "photo",
		Required: false,
		Usage:    `photo (string)`,
	},
	&cli.StringFlag{
		Name:     "gender",
		Required: false,
		Usage:    `gender (int?)`,
	},
	&cli.StringFlag{
		Name:     "title",
		Required: false,
		Usage:    `title (string)`,
	},
	&cli.StringFlag{
		Name:     "birth-date",
		Required: false,
		Usage:    `birthDate (date)`,
	},
	&cli.StringFlag{
		Name:     "avatar",
		Required: false,
		Usage:    `avatar (string)`,
	},
	&cli.StringFlag{
		Name:     "last-ip-address",
		Required: false,
		Usage:    `User last connecting ip address (string)`,
	},
	&cli.StringFlag{
		Name:     "primaryAddress-wid",
		Required: false,
		Usage:    "Provide workspace id, if you want to change the data workspace",
	},
	&cli.StringFlag{
		Name:     "primaryAddress-uid",
		Required: false,
		Usage:    "Unique Id - external unique hash to query entity",
	},
	&cli.StringFlag{
		Name:     "primaryAddress-pid",
		Required: false,
		Usage:    " Parent record id of the same type",
	},
	&cli.StringFlag{
		Name:     "primaryAddress-address-line1",
		Required: false,
		Usage:    `Street address, building number (string)`,
	},
	&cli.StringFlag{
		Name:     "primaryAddress-address-line2",
		Required: false,
		Usage:    `Apartment, suite, floor (optional) (string?)`,
	},
	&cli.StringFlag{
		Name:     "primaryAddress-city",
		Required: false,
		Usage:    `City or locality (string?)`,
	},
	&cli.StringFlag{
		Name:     "primaryAddress-state-or-province",
		Required: false,
		Usage:    `State, region, or province (string?)`,
	},
	&cli.StringFlag{
		Name:     "primaryAddress-postal-code",
		Required: false,
		Usage:    `ZIP or postal code (string?)`,
	},
	&cli.StringFlag{
		Name:     "primaryAddress-country-code",
		Required: false,
		Usage:    `ISO 3166-1 alpha-2 (e.g., \"US\", \"DE\") (string?)`,
	},
}
var UserCommonInteractiveCliFlags = []fireback.CliInteractiveFlag{
	{
		Name:        "firstName",
		StructField: "FirstName",
		Required:    true,
		Recommended: false,
		Usage:       `firstName`,
		Type:        "string",
	},
	{
		Name:        "lastName",
		StructField: "LastName",
		Required:    true,
		Recommended: false,
		Usage:       `lastName`,
		Type:        "string",
	},
	{
		Name:        "photo",
		StructField: "Photo",
		Required:    false,
		Recommended: false,
		Usage:       `photo`,
		Type:        "string",
	},
	{
		Name:        "title",
		StructField: "Title",
		Required:    false,
		Recommended: false,
		Usage:       `title`,
		Type:        "string",
	},
	{
		Name:        "avatar",
		StructField: "Avatar",
		Required:    false,
		Recommended: false,
		Usage:       `avatar`,
		Type:        "string",
	},
	{
		Name:        "lastIpAddress",
		StructField: "LastIpAddress",
		Required:    false,
		Recommended: false,
		Usage:       `User last connecting ip address`,
		Type:        "string",
	},
}
var UserCommonCliFlagsOptional = []cli.Flag{
	&cli.StringFlag{
		Name:     "wid",
		Required: false,
		Usage:    "Provide workspace id, if you want to change the data workspace",
	},
	&cli.StringFlag{
		Name:     "uid",
		Required: false,
		Usage:    "Unique Id - external unique hash to query entity",
	},
	&cli.StringFlag{
		Name:     "pid",
		Required: false,
		Usage:    " Parent record id of the same type",
	},
	&cli.StringFlag{
		Name:     "first-name",
		Required: true,
		Usage:    `firstName (string)`,
	},
	&cli.StringFlag{
		Name:     "last-name",
		Required: true,
		Usage:    `lastName (string)`,
	},
	&cli.StringFlag{
		Name:     "photo",
		Required: false,
		Usage:    `photo (string)`,
	},
	&cli.StringFlag{
		Name:     "gender",
		Required: false,
		Usage:    `gender (int?)`,
	},
	&cli.StringFlag{
		Name:     "title",
		Required: false,
		Usage:    `title (string)`,
	},
	&cli.StringFlag{
		Name:     "birth-date",
		Required: false,
		Usage:    `birthDate (date)`,
	},
	&cli.StringFlag{
		Name:     "avatar",
		Required: false,
		Usage:    `avatar (string)`,
	},
	&cli.StringFlag{
		Name:     "last-ip-address",
		Required: false,
		Usage:    `User last connecting ip address (string)`,
	},
	&cli.StringFlag{
		Name:     "primaryAddress-wid",
		Required: false,
		Usage:    "Provide workspace id, if you want to change the data workspace",
	},
	&cli.StringFlag{
		Name:     "primaryAddress-uid",
		Required: false,
		Usage:    "Unique Id - external unique hash to query entity",
	},
	&cli.StringFlag{
		Name:     "primaryAddress-pid",
		Required: false,
		Usage:    " Parent record id of the same type",
	},
	&cli.StringFlag{
		Name:     "primaryAddress-address-line1",
		Required: false,
		Usage:    `Street address, building number (string)`,
	},
	&cli.StringFlag{
		Name:     "primaryAddress-address-line2",
		Required: false,
		Usage:    `Apartment, suite, floor (optional) (string?)`,
	},
	&cli.StringFlag{
		Name:     "primaryAddress-city",
		Required: false,
		Usage:    `City or locality (string?)`,
	},
	&cli.StringFlag{
		Name:     "primaryAddress-state-or-province",
		Required: false,
		Usage:    `State, region, or province (string?)`,
	},
	&cli.StringFlag{
		Name:     "primaryAddress-postal-code",
		Required: false,
		Usage:    `ZIP or postal code (string?)`,
	},
	&cli.StringFlag{
		Name:     "primaryAddress-country-code",
		Required: false,
		Usage:    `ISO 3166-1 alpha-2 (e.g., \"US\", \"DE\") (string?)`,
	},
}
var UserCreateCmd cli.Command = USER_ACTION_POST_ONE.ToCli()
var UserCreateInteractiveCmd cli.Command = cli.Command{
	Name:  "ic",
	Usage: "Creates a new entity, using requied fields in an interactive name",
	Flags: []cli.Flag{
		&cli.BoolFlag{
			Name:  "all",
			Usage: "Interactively asks for all inputs, not only required ones",
		},
	},
	Action: func(c *cli.Context) {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{PERM_ROOT_USER_CREATE},
			AllowOnRoot:    true,
		})
		entity := &UserEntity{}
		fireback.PopulateInteractively(entity, c, UserCommonInteractiveCliFlags)
		if entity, err := UserActions.Create(entity, query); err != nil {
			fmt.Println(err.Error())
		} else {
			f, _ := yaml.Marshal(entity)
			fmt.Println(fireback.FormatYamlKeys(string(f)))
		}
	},
}
var UserUpdateCmd cli.Command = cli.Command{
	Name:    "update",
	Aliases: []string{"u"},
	Flags:   UserCommonCliFlagsOptional,
	Usage:   "Updates entity by passing the parameters",
	Action: func(c *cli.Context) error {
		query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{PERM_ROOT_USER_UPDATE},
			AllowOnRoot:    true,
		})
		entity := CastUserFromCli(c)
		if entity, err := UserActions.Update(query, entity); err != nil {
			fmt.Println(err.Error())
		} else {
			f, _ := json.MarshalIndent(entity, "", "  ")
			fmt.Println(string(f))
		}
		return nil
	},
}

func (x *UserEntity) FromCli(c *cli.Context) *UserEntity {
	return CastUserFromCli(c)
}
func CastUserFromCli(c *cli.Context) *UserEntity {
	template := &UserEntity{}
	if c.IsSet("uid") {
		template.UniqueId = c.String("uid")
	}
	if c.IsSet("pid") {
		template.ParentId = fireback.NewStringAutoNull(c.String("pid"))
	}
	if c.IsSet("first-name") {
		template.FirstName = c.String("first-name")
	}
	if c.IsSet("last-name") {
		template.LastName = c.String("last-name")
	}
	if c.IsSet("photo") {
		template.Photo = c.String("photo")
	}
	if c.IsSet("title") {
		template.Title = c.String("title")
	}
	if c.IsSet("birth-date") {
		value := c.String("birth-date")
		template.BirthDate.Scan(value)
	}
	if c.IsSet("avatar") {
		template.Avatar = c.String("avatar")
	}
	if c.IsSet("last-ip-address") {
		template.LastIpAddress = c.String("last-ip-address")
	}
	return template
}
func UserSyncSeederFromFs(fsRef *embed.FS, fileNames []string, q fireback.QueryDSL) {
	fireback.SeederFromFSImport(
		q,
		UserActions.Create,
		reflect.ValueOf(&UserEntity{}).Elem(),
		fsRef,
		fileNames,
		true,
	)
}
func UserSyncSeeders() {
	fireback.SeederFromFSImport(
		fireback.QueryDSL{WorkspaceId: fireback.USER_SYSTEM},
		UserActions.Create,
		reflect.ValueOf(&UserEntity{}).Elem(),
		userSeedersFs,
		[]string{},
		true,
	)
}
func UserImportMocks() {
	fireback.SeederFromFSImport(
		fireback.QueryDSL{},
		UserActions.Create,
		reflect.ValueOf(&UserEntity{}).Elem(),
		&mocks.ViewsFs,
		[]string{},
		false,
	)
}
func UserWriteQueryMock(ctx fireback.MockQueryContext) {
	for _, lang := range ctx.Languages {
		itemsPerPage := 9999
		if ctx.ItemsPerPage > 0 {
			itemsPerPage = ctx.ItemsPerPage
		}
		f := fireback.QueryDSL{ItemsPerPage: itemsPerPage, Language: lang, WithPreloads: ctx.WithPreloads, Deep: true}
		items, count, _ := UserActions.Query(f)
		result := fireback.QueryEntitySuccessResult(f, items, count)
		fireback.WriteMockDataToFile(lang, "", "User", result)
	}
}
func UsersActionQueryString(keyword string, page int) ([]string, *fireback.QueryResultMeta, error) {
	searchFields := []string{
		`unique_id %"{keyword}"%`,
		`name %"{keyword}"%`,
	}
	m := func(item *UserEntity) string {
		label := item.UniqueId
		// if item.Name != nil {
		// 	label += " >>> " + *item.Name
		// }
		return label
	}
	query := fireback.QueryStringCastCli(searchFields, keyword, page)
	items, meta, err := UserActions.Query(query)
	stringItems := []string{}
	for _, item := range items {
		label := m(item)
		stringItems = append(stringItems, label)
	}
	return stringItems, meta, err
}

var UserDevCommands = []cli.Command{
	UserWipeCmd,
	{
		Name:  "mock",
		Usage: "Generates mock records based on the entity definition",
		Flags: []cli.Flag{
			&cli.IntFlag{
				Name:  "count",
				Usage: "how many activation key do you need to be generated and stored in database",
				Value: 10,
			},
			&cli.BoolFlag{
				Name:  "batch",
				Usage: "Multiple insert into database mode. Might miss children and relations at the moment",
			},
		},
		Action: func(c *cli.Context) error {
			query := fireback.CommonCliQueryDSLBuilderAuthorize(c, &fireback.SecurityModel{
				ActionRequires: []fireback.PermissionInfo{PERM_ROOT_USER_CREATE},
				AllowOnRoot:    true,
			})
			if c.Bool("batch") {
				UserActionSeederMultiple(query, c.Int("count"))
			} else {
				UserActionSeeder(query, c.Int("count"))
			}
			return nil
		},
	},
	{
		Name:    "init",
		Aliases: []string{"i"},
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "format",
				Usage: "Format of the export or import file. Can be 'yaml', 'yml', 'json'",
				Value: "yaml",
			},
		},
		Usage: "Creates a basic seeder file for you, based on the definition module we have. You can populate this file as an example",
		Action: func(c *cli.Context) error {
			seed := UserActions.SeederInit()
			fireback.CommonInitSeeder(strings.TrimSpace(c.String("format")), seed)
			return nil
		},
	},
	cli.Command{
		Name:  "mlist",
		Usage: "Prints the list of embedded mocks into the app",
		Action: func(c *cli.Context) error {
			if entity, err := fireback.GetSeederFilenames(&mocks.ViewsFs, ""); err != nil {
				fmt.Println(err.Error())
			} else {
				f, _ := json.MarshalIndent(entity, "", "  ")
				fmt.Println(string(f))
			}
			return nil
		},
	},
	cli.Command{
		Name:  "msync",
		Usage: "Tries to sync mocks into the system",
		Action: func(c *cli.Context) error {
			fireback.CommonCliImportEmbedCmd(c,
				UserActions.Create,
				reflect.ValueOf(&UserEntity{}).Elem(),
				&mocks.ViewsFs,
			)
			return nil
		},
	},
}
var UserImportExportCommands = []cli.Command{
	{
		Name:    "validate",
		Aliases: []string{"v"},
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "file",
				Usage: "Validates an import file, such as yaml, json, csv, and gives some insights how the after import it would look like",
				Value: "user-seeder-user.yml",
				// Uncomment before publish, they need to specify
				// Required: true,
			},
			&cli.StringFlag{
				Name:  "format",
				Usage: "Format of the export or import file. Can be 'yaml', 'yml', 'json'",
				Value: "yaml",
			},
		},
		Usage: "Reads a yaml file containing an array of users, you can run this to validate if your import file is correct, and how it would look like after import",
		Action: func(c *cli.Context) error {
			data := &[]UserEntity{}
			fireback.ReadYamlFile(c.String("file"), data)
			fmt.Println(data)
			return nil
		},
	},
	cli.Command{
		Name:  "slist",
		Usage: "Prints the list of files attached to this module for syncing or bootstrapping project",
		Action: func(c *cli.Context) error {
			if entity, err := fireback.GetSeederFilenames(userSeedersFs, ""); err != nil {
				fmt.Println(err.Error())
			} else {
				f, _ := json.MarshalIndent(entity, "", "  ")
				fmt.Println(string(f))
			}
			return nil
		},
	},
	cli.Command{
		Name:  "ssync",
		Usage: "Tries to sync the embedded content into the database, the list could be seen by 'slist' command",
		Action: func(c *cli.Context) error {
			fireback.CommonCliImportEmbedCmd(c,
				UserActions.Create,
				reflect.ValueOf(&UserEntity{}).Elem(),
				userSeedersFs,
			)
			return nil
		},
	},
	cli.Command{
		Name:    "export",
		Aliases: []string{"e"},
		Flags: append(fireback.CommonQueryFlags,
			&cli.StringFlag{
				Name:     "file",
				Usage:    "The address of file you want the csv/yaml/json be exported to",
				Required: true,
			}),
		Usage: "Exports a query results into the csv/yaml/json format",
		Action: func(c *cli.Context) error {
			return fireback.CommonCliExportCmd2(c,
				UserEntityStream,
				reflect.ValueOf(&UserEntity{}).Elem(),
				c.String("file"),
				&metas.MetaFs,
				"UserFieldMap.yml",
				UserPreloadRelations,
			)
		},
	},
	cli.Command{
		Name: "import",
		Flags: append(
			append(
				fireback.CommonQueryFlags,
				&cli.StringFlag{
					Name:     "file",
					Usage:    "The address of file you want the csv be imported from",
					Required: true,
				}),
			UserCommonCliFlagsOptional...,
		),
		Usage: "imports csv/yaml/json file and place it and its children into database",
		Action: func(c *cli.Context) error {
			fireback.CommonCliImportCmdAuthorized(c,
				UserActions.Create,
				reflect.ValueOf(&UserEntity{}).Elem(),
				c.String("file"),
				&fireback.SecurityModel{
					ActionRequires: []fireback.PermissionInfo{PERM_ROOT_USER_CREATE},
					AllowOnRoot:    true,
				},
				func() UserEntity {
					v := CastUserFromCli(c)
					return *v
				},
			)
			return nil
		},
	},
}
var UserCliCommands []cli.Command = []cli.Command{
	USER_ACTION_QUERY.ToCli(),
	USER_ACTION_TABLE.ToCli(),
	UserCreateCmd,
	UserUpdateCmd,
	UserAskCmd,
	UserCreateInteractiveCmd,
	fireback.GetCommonRemoveQuery(
		reflect.ValueOf(&UserEntity{}).Elem(),
		UserActions.Remove,
	),
}

func UserCliFn() cli.Command {
	commands := append(UserImportExportCommands, UserCliCommands...)
	if !fireback.GetConfig().Production {
		commands = append(commands, UserDevCommands...)
	}
	return cli.Command{
		Name:        "user",
		Description: "Users module actions",
		Usage:       `Manage the users who are in the current app (root only)`,
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:  "language",
				Value: "en",
			},
		},
		Subcommands: commands,
	}
}

var USER_ACTION_TABLE = fireback.Module3Action{
	Name:          "table",
	ActionAliases: []string{"t"},
	Flags:         fireback.CommonQueryFlags,
	Description:   "Table formatted queries all of the entities in database based on the standard query format",
	Action:        UserActions.Query,
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		fireback.CommonCliTableCmd2(c,
			UserActions.Query,
			security,
			reflect.ValueOf(&UserEntity{}).Elem(),
		)
		return nil
	},
}
var USER_ACTION_QUERY = fireback.Module3Action{
	Method: "GET",
	Url:    "/users",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_USER_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			qs := &UserEntityQs{}
			fireback.HttpQueryEntity(c, UserActions.Query, qs)
		},
	},
	Format:         "QUERY",
	Action:         UserActions.Query,
	ResponseEntity: &[]UserEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "UserEntity",
	},
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		qs := &UserEntityQs{}
		fireback.CommonCliQueryCmd3(
			c,
			UserActions.Query,
			security,
			qs,
		)
		return nil
	},
	CliName:       "query",
	Name:          "query",
	ActionAliases: []string{"q"},
	Flags:         append(fireback.CommonQueryFlags, UserQsFlags...),
	Description:   "Queries all of the entities in database based on the standard query format (s+)",
}
var USER_ACTION_EXPORT = fireback.Module3Action{
	Method: "GET",
	Url:    "/users/export",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_USER_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpStreamFileChannel(c, UserActionExport)
		},
	},
	Format:         "QUERY",
	Action:         UserActionExport,
	ResponseEntity: &[]UserEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "UserEntity",
	},
}
var USER_ACTION_GET_ONE = fireback.Module3Action{
	Method: "GET",
	Url:    "/user/:uniqueId",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_USER_QUERY},
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpGetEntity(c, UserActions.GetOne)
		},
	},
	Format:         "GET_ONE",
	Action:         UserActions.GetOne,
	ResponseEntity: &UserEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "UserEntity",
	},
}
var USER_ACTION_POST_ONE = fireback.Module3Action{
	Name:          "create",
	ActionAliases: []string{"c"},
	Description:   "Create new user",
	Flags:         UserCommonCliFlags,
	Method:        "POST",
	Url:           "/user",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_USER_CREATE},
		AllowOnRoot:    true,
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpPostEntity(c, UserActions.Create)
		},
	},
	CliAction: func(c *cli.Context, security *fireback.SecurityModel) error {
		result, err := fireback.CliPostEntity(c, UserActions.Create, security)
		fireback.HandleActionInCli(c, result, err, map[string]map[string]string{})
		return err
	},
	Action:         UserActions.Create,
	Format:         "POST_ONE",
	RequestEntity:  &UserEntity{},
	ResponseEntity: &UserEntity{},
	Out: &fireback.Module3ActionBody{
		Entity: "UserEntity",
	},
	In: &fireback.Module3ActionBody{
		Entity: "UserEntity",
	},
}
var USER_ACTION_PATCH = fireback.Module3Action{
	Name:          "update",
	ActionAliases: []string{"u"},
	Flags:         UserCommonCliFlagsOptional,
	Method:        "PATCH",
	Url:           "/user",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_USER_UPDATE},
		AllowOnRoot:    true,
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpUpdateEntity(c, UserActions.Update)
		},
	},
	Action:         UserActions.Update,
	RequestEntity:  &UserEntity{},
	ResponseEntity: &UserEntity{},
	Format:         "PATCH_ONE",
	Out: &fireback.Module3ActionBody{
		Entity: "UserEntity",
	},
	In: &fireback.Module3ActionBody{
		Entity: "UserEntity",
	},
}
var USER_ACTION_PATCH_BULK = fireback.Module3Action{
	Method: "PATCH",
	Url:    "/users",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_USER_UPDATE},
		AllowOnRoot:    true,
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpUpdateEntities(c, UserActionBulkUpdate)
		},
	},
	Action:         UserActionBulkUpdate,
	Format:         "PATCH_BULK",
	RequestEntity:  &fireback.BulkRecordRequest[UserEntity]{},
	ResponseEntity: &fireback.BulkRecordRequest[UserEntity]{},
	Out: &fireback.Module3ActionBody{
		Entity: "UserEntity",
	},
	In: &fireback.Module3ActionBody{
		Entity: "UserEntity",
	},
}
var USER_ACTION_DELETE = fireback.Module3Action{
	Method: "DELETE",
	Url:    "/user",
	Format: "DELETE_DSL",
	SecurityModel: &fireback.SecurityModel{
		ActionRequires: []fireback.PermissionInfo{PERM_ROOT_USER_DELETE},
		AllowOnRoot:    true,
	},
	Handlers: []gin.HandlerFunc{
		func(c *gin.Context) {
			fireback.HttpRemoveEntity(c, UserActions.Remove)
		},
	},
	Action:         UserActions.Remove,
	RequestEntity:  &fireback.DeleteRequest{},
	ResponseEntity: &fireback.DeleteResponse{},
	TargetEntity:   &UserEntity{},
}

/**
 *	Override this function on UserEntityHttp.go,
 *	In order to add your own http
 **/
var AppendUserRouter = func(r *[]fireback.Module3Action) {}

func GetUserModule3Actions() []fireback.Module3Action {
	routes := []fireback.Module3Action{
		USER_ACTION_QUERY,
		USER_ACTION_EXPORT,
		USER_ACTION_GET_ONE,
		USER_ACTION_POST_ONE,
		USER_ACTION_PATCH,
		USER_ACTION_PATCH_BULK,
		USER_ACTION_DELETE,
	}
	// Append user defined functions
	AppendUserRouter(&routes)
	return routes
}

var PERM_ROOT_USER = fireback.PermissionInfo{
	CompleteKey: "root.manage.abac.user.*",
	Name:        "Entire user actions (*)",
	Description: "",
}
var PERM_ROOT_USER_DELETE = fireback.PermissionInfo{
	CompleteKey: "root.manage.abac.user.delete",
	Name:        "Delete user",
	Description: "",
}
var PERM_ROOT_USER_CREATE = fireback.PermissionInfo{
	CompleteKey: "root.manage.abac.user.create",
	Name:        "Create user",
	Description: "",
}
var PERM_ROOT_USER_UPDATE = fireback.PermissionInfo{
	CompleteKey: "root.manage.abac.user.update",
	Name:        "Update user",
	Description: "",
}
var PERM_ROOT_USER_QUERY = fireback.PermissionInfo{
	CompleteKey: "root.manage.abac.user.query",
	Name:        "Query user",
	Description: "",
}
var ALL_USER_PERMISSIONS = []fireback.PermissionInfo{
	PERM_ROOT_USER_DELETE,
	PERM_ROOT_USER_CREATE,
	PERM_ROOT_USER_UPDATE,
	PERM_ROOT_USER_QUERY,
	PERM_ROOT_USER,
}

type Googoli2EventPayload struct {
	Entity string `json:"entity" xml:"entity" yaml:"entity"        `
}

func (x *Googoli2EventPayload) Json() string {
	if x != nil {
		str, _ := json.MarshalIndent(x, "", "  ")
		return (string(str))
	}
	return ""
}
func NewGoogoli2Event(
	payload *Googoli2EventPayload,
	query *fireback.QueryDSL,
) (*fireback.Event, error) {
	event := &fireback.Event{
		Name:    "Googoli2",
		Payload: payload,
	}
	// Apply the source of the event based on querydsl
	fireback.ApplyQueryDslContextToEvent(event, *query)
	return event, nil
}
func NewUserCreatedEvent(
	payload *UserEntity,
	query *fireback.QueryDSL,
) (*fireback.Event, error) {
	event := &fireback.Event{
		Name:    "UserCreated",
		Payload: payload,
		Security: &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{
				PERM_ROOT_USER_QUERY,
			},
		},
		CacheKey: "*abac.UserEntity",
	}
	// Apply the source of the event based on querydsl
	fireback.ApplyQueryDslContextToEvent(event, *query)
	return event, nil
}
func NewUserUpdatedEvent(
	payload *UserEntity,
	query *fireback.QueryDSL,
) (*fireback.Event, error) {
	event := &fireback.Event{
		Name:    "UserUpdated",
		Payload: payload,
		Security: &fireback.SecurityModel{
			ActionRequires: []fireback.PermissionInfo{
				PERM_ROOT_USER_QUERY,
			},
		},
		CacheKey: "*abac.UserEntity",
	}
	// Apply the source of the event based on querydsl
	fireback.ApplyQueryDslContextToEvent(event, *query)
	return event, nil
}

var UserEntityBundle = fireback.EntityBundle{
	Permissions: ALL_USER_PERMISSIONS,
	// Cli command has been exluded, since we use module to wrap all the entities
	// to be more easier to wrap up.
	// Create your own bundle if you need with Cli
	//CliCommands: []cli.Command{
	//	UserCliFn(),
	//},
	Actions:      GetUserModule3Actions(),
	MockProvider: UserImportMocks,
	AutoMigrationEntities: []interface{}{
		&UserEntity{},
		&UserPrimaryAddress{},
	},
	MigrationScripts: []fireback.MigrationScript{},
}
