package fireback

import (
	"fmt"
	"reflect"
	"regexp"
	"slices"
	"strings"

	"github.com/torabian/fireback/modules/fireback/application"
)

/*
Any module can declare its own `config:` block in its own Module3/Emi yaml file
(exactly like Fireback.emi.yml's own `config:` section) - the emi compiler already
generates a standalone `Config` struct, package-level `config` var and
`LoadConfiguration()` for that module's own package, completely independently from
fireback's. Nothing, until now, ever combined those per-module configs together or
showed them anywhere - each module's config only existed for its own package to read
its own env vars.

This mirrors abac.Menu/interfacetools.SyncAppMenus: a module contributes its data via
a plain function on application.ModuleProvider (ConfigProvider), without fireback (or
any other module) importing it back, and fireback folds everything together in one
place (GetCombinedConfigInfo) for a single combined listing (see ConfigurationCli.go's
"config list" command).
*/

// One field out of some module's generated Config struct, flattened for display -
// same identifying info the emi `config:` block already carries (name/env/type/
// description), plus which module it came from and its current, live value.
type ConfigItemInfo struct {
	Module      string `json:"module"`
	Name        string `json:"name"`
	Env         string `json:"env,omitempty"`
	Type        string `json:"type"`
	Description string `json:"description,omitempty"`
	Value       string `json:"value"`
}

// Field names/env vars that look sensitive - their value is replaced with "******"
// in GetCombinedConfigInfo unless reveal is true. A heuristic, not a guarantee: a
// module using a name this doesn't recognize (e.g. "apiSigningSeed") still prints in
// clear text, so treat this as a convenience default rather than a security boundary.
//
// Checked against only the last two "_"-separated segments of the env var (or the
// last two words of the field name, split on camel/PascalCase boundaries), not a
// bare substring match anywhere in the name - a plain Contains would also flag
// harmless fields that merely mention one of these words in passing, e.g.
// TOKEN_GENERATION_STRATEGY (an enum like "random"/"jwt", not a credential) or
// VAPID_PUBLIC_KEY (deliberately public, unlike VAPID_PRIVATE_KEY).
// "DSN" is included because a connection dsn (dbDsn) commonly embeds a plaintext
// password inline ("...password=secret...") even though the field itself isn't
// named *_PASSWORD or *_SECRET.
var sensitiveConfigNameHints = []string{"SECRET", "PASSWORD", "TOKEN", "PRIVATE", "DSN"}

var pascalWordBoundary = regexp.MustCompile(`[A-Z]+[a-z0-9]*|[0-9]+`)

func looksSensitive(fieldName string, env string) bool {
	var words []string
	if env != "" {
		words = strings.Split(env, "_")
	} else {
		words = pascalWordBoundary.FindAllString(fieldName, -1)
	}

	if len(words) > 2 {
		words = words[len(words)-2:]
	}

	for _, word := range words {
		if slices.Contains(sensitiveConfigNameHints, strings.ToUpper(word)) {
			return true
		}
	}
	return false
}

// ExtractConfigInfo reflects over any struct (or pointer to struct) generated by the
// emi `config:` block - it only relies on the `envconfig`/`description` tags
// GoConfigGenerate already emits on every field, so it works for fireback's own Config
// as well as any module's, with no per-module hand-written registration needed. cfg
// can be a struct value or a pointer to one; anything else returns nil.
func ExtractConfigInfo(moduleName string, cfg any, reveal bool) []ConfigItemInfo {
	if cfg == nil {
		return nil
	}

	v := reflect.ValueOf(cfg)
	for v.Kind() == reflect.Pointer {
		if v.IsNil() {
			return nil
		}
		v = v.Elem()
	}

	if v.Kind() != reflect.Struct {
		return nil
	}

	t := v.Type()
	items := make([]ConfigItemInfo, 0, t.NumField())

	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		if !field.IsExported() {
			continue
		}

		env := field.Tag.Get("envconfig")
		value := "" // best-effort string form, empty for types we don't try to format

		func() {
			// A field of a type this doesn't understand (nested struct, slice, ...)
			// shouldn't blow up the whole listing - Fields (nested config) support is
			// explicitly "may be limited" per emi's own EmiConfig doc comment.
			defer func() { recover() }()
			value = formatConfigValue(v.Field(i))
		}()

		if !reveal && looksSensitive(field.Name, env) && value != "" {
			value = "******"
		}

		items = append(items, ConfigItemInfo{
			Module:      moduleName,
			Name:        field.Name,
			Env:         env,
			Type:        field.Type.String(),
			Description: field.Tag.Get("description"),
			Value:       value,
		})
	}

	return items
}

func formatConfigValue(v reflect.Value) string {
	switch v.Kind() {
	case reflect.String:
		return v.String()
	case reflect.Bool:
		if v.Bool() {
			return "true"
		}
		return "false"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return fmt.Sprintf("%v", v.Interface())
	default:
		// Nested struct/slice/map fields (config: supports `fields:` nesting, but
		// GoConfigGenerate's own doc comment already calls that support "limited") -
		// skip rather than guess at a representation.
		return ""
	}
}

// GetCombinedConfigInfo walks fireback's own core Config plus every registered
// module's ConfigProvider (application.ModuleProvider) and flattens them into one
// slice - the single "show to user" collection point every module's own config
// funnels into, the same way abac.Menu funnels into interfacetools' AppMenu sync.
func GetCombinedConfigInfo(x *application.Application, reveal bool) []ConfigItemInfo {
	items := ExtractConfigInfo("fireback", &config, reveal)

	for _, module := range x.Modules {
		if module.ConfigProvider == nil {
			continue
		}

		name := module.Name
		if name == "" {
			name = module.Namespace
		}

		items = append(items, ExtractConfigInfo(name, module.ConfigProvider(), reveal)...)
	}

	return items
}
