package worldtimezone

var TIMEZONEGROUP_EVENT_CREATED = "timezoneGroup.created"
var TIMEZONEGROUP_EVENT_UPDATED = "timezoneGroup.updated"
var TIMEZONEGROUP_EVENT_DELETED = "timezoneGroup.deleted"

var TIMEZONEGROUP_EVENTS = []string{
	TIMEZONEGROUP_EVENT_CREATED,
	TIMEZONEGROUP_EVENT_UPDATED,
	TIMEZONEGROUP_EVENT_DELETED,
}
