package worldtimezone

var PERM_ROOT_TIMEZONEGROUP_DELETE = "root/timezonegroup/delete"
var PERM_ROOT_TIMEZONEGROUP_CREATE = "root/timezonegroup/create"
var PERM_ROOT_TIMEZONEGROUP_UPDATE = "root/timezonegroup/update"
var PERM_ROOT_TIMEZONEGROUP_QUERY = "root/timezonegroup/query"
var PERM_ROOT_TIMEZONEGROUP = "root/timezonegroup"

var ALL_TIMEZONEGROUP_PERMISSIONS = []string{
	PERM_ROOT_TIMEZONEGROUP_DELETE,
	PERM_ROOT_TIMEZONEGROUP_CREATE,
	PERM_ROOT_TIMEZONEGROUP_UPDATE,
	PERM_ROOT_TIMEZONEGROUP_QUERY,
	PERM_ROOT_TIMEZONEGROUP,
}
