import { ExecutionContext, createParamDecorator } from '@nestjs/common';
import { fetchx } from 'INTERNAL_SDK_LOCATION';
/**
* Action to communicate with the action createWorkspace
*/


	/**
 * FetchCreateWorkspaceAction
 */

export class FetchCreateWorkspaceAction {
  static URL = '/workspaces/create';
  static Method = 'post';

  
  	static Axios = (clientInstance: AxiosInstance, config: AxiosRequestConfig<unknown>) =>
		clientInstance
		.requestrequest<unknown, AxiosResponse<unknown>, unknown>(config)

		
	
  
  
	static Fetch = (
		init?: TypedRequestInit<unknown, unknown> | undefined,
		qs?: SignoutQueryParams,
		overrideUrl?: string
	) =>
		fetchx<unknown, unknown, unknown>(
			new URL((overrideUrl ?? FetchSignoutAction.URL) + '?' + qs?.toString()),
			init
		)

		
			.then((res) => res.text())
		

	
		

	
}









	
/**
  * @decription The base class definition for createWorkspaceReq
  **/

export class CreateWorkspaceReq {
	 
		/**
  * @type {string}
  * @description 
  **/
 name;
		/**
  * @returns {string}
  * @description 
  **/
getName () { return this[`name`] }
		/**
  * @param {string}
  * @description 
  **/
setName (value) { this[`name`] = value; return this; } 
	 
		/**
  * @type {WorkspaceEntity}
  * @description 
  **/
 workspace;
		/**
  * @returns {WorkspaceEntity}
  * @description 
  **/
getWorkspace () { return this[`workspace`] }
		/**
  * @param {WorkspaceEntity}
  * @description 
  **/
setWorkspace (value) { this[`workspace`] = value; return this; } 
	 
		/**
  * @type {string}
  * @description 
  **/
 workspaceId;
		/**
  * @returns {string}
  * @description 
  **/
getWorkspaceId () { return this[`workspaceId`] }
		/**
  * @param {string}
  * @description 
  **/
setWorkspaceId (value) { this[`workspaceId`] = value; return this; } 
	

	

	/** a placeholder for WebRequestX auto patching the json content to the object **/
	static __jsonParsable;

	
		/**
   * Nest.js decorator for controller headers. Instead of using @Headers() value: any, now you can use for example:
   * @example
   * @Get()
   * getHello(@CreateWorkspaceReq.Nest() headers: CreateWorkspaceReq): string {
   *  return JSON.stringify(headers.getContentType());
   * }
   */
  static Nest = createParamDecorator(
	(_data, ctx) => {
		// @ts-ignore
		const request = ctx.switchToHttp().getRequest();
		// @ts-ignore
		return new CreateWorkspaceReq( request.body );
	},
  );


	
}










/**
 * CreateWorkspaceHeaders class
 * Auto-generated from Module3Action
 */
export class CreateWorkspaceHeaders extends Headers {

  // the getters generated by us would be casting types before returning.
  // you still can use .get function to get the string value.
  #getTyped(key, type) {
    const val = this.get(key);
    if (val == null) return null;

    const t = type.toLowerCase();

    if (t.includes('number')) return Number(val);
    if (t.includes('bool')) return val === 'true';
    return val; // string or any other fallback
  }


  /**
   * @returns {Record<string, string>}
   * Converts Headers to plain object
   */
  toObject() {
    return Object.fromEntries(this.entries());
  }

  
  /**
   * Nest.js decorator for controller headers. Instead of using @Headers() value: any, now you can use for example:
   * @example
   * @Get()
   * getHello(@CreateWorkspaceHeaders.Nest() headers: CreateWorkspaceHeaders): string {
   *  return JSON.stringify(headers.getContentType());
   * }
   */
  static Nest = createParamDecorator(
	(_data, ctx) => {
		// @ts-ignore
		const request = ctx.switchToHttp().getRequest();
		// @ts-ignore
		return new CreateWorkspaceHeaders(Object.entries(request.headers));
	},
  );

  
}




/**
 * CreateWorkspaceQueryParams class
 * Auto-generated from Module3Action
 */
export class CreateWorkspaceQueryParams extends URLSearchParamsX {


  // the getters generated by us would be casting types before returning.
  // you still can use .get function to get the string value.
  #getTyped(key, type) {
    const val = this.get(key);
    if (val == null) return null;

    const t = type.toLowerCase();

    if (t.includes('number')) return Number(val);
    if (t.includes('bool')) return val === 'true';
    return val; // string or any other fallback
  }


  
  /**
   * Nest.js decorator for controller query. Instead of using @Query() value: any, now you can use for example:
   * @example
   * @Get()
   * getHello(@CreateWorkspaceQueryParams.Nest() query: CreateWorkspaceQueryParams): string {
   *  return JSON.stringify(query.getMyfield());
   * }
   */
  static Nest = createParamDecorator(
	(_data, ctx) => {
		// @ts-ignore
		const request = ctx.switchToHttp().getRequest();
		// @ts-ignore
		return new CreateWorkspaceQueryParams(request.query);
	},
  );

  
}


 
