import { ExecutionContext, createParamDecorator } from '@nestjs/common';
import { fetchx } from 'INTERNAL_SDK_LOCATION';
/**
* Action to communicate with the action sendEmailWithProvider
*/


	/**
 * FetchSendEmailWithProviderAction
 */

export class FetchSendEmailWithProviderAction {
  static URL = '/emailProvider/send';
  static Method = 'post';

  
  	static Axios = (clientInstance: AxiosInstance, config: AxiosRequestConfig<unknown>) =>
		clientInstance
		.requestrequest<unknown, AxiosResponse<unknown>, unknown>(config)

		
		.then((res) => {
			return {
			...res,

			
			// if there is a output class, create instance out of it.
			data: new SendEmailWithProviderRes(res.data),
			};
		});
		
	
  
  
	static Fetch = (
		init?: TypedRequestInit<unknown, unknown> | undefined,
		qs?: SignoutQueryParams,
		overrideUrl?: string
	) =>
		fetchx<unknown, unknown, unknown>(
			new URL((overrideUrl ?? FetchSignoutAction.URL) + '?' + qs?.toString()),
			init
		)

		
			.then((res) => res.json())
		

	
		
			.then((data) => new SendEmailWithProviderRes (data));
		

	
}









	
/**
  * @decription The base class definition for sendEmailWithProviderReq
  **/

export class SendEmailWithProviderReq {
	 
		/**
  * @type {EmailProviderEntity}
  * @description 
  **/
 emailProvider;
		/**
  * @returns {EmailProviderEntity}
  * @description 
  **/
getEmailProvider () { return this[`emailProvider`] }
		/**
  * @param {EmailProviderEntity}
  * @description 
  **/
setEmailProvider (value) { this[`emailProvider`] = value; return this; } 
	 
		/**
  * @type {string}
  * @description 
  **/
 toAddress;
		/**
  * @returns {string}
  * @description 
  **/
getToAddress () { return this[`toAddress`] }
		/**
  * @param {string}
  * @description 
  **/
setToAddress (value) { this[`toAddress`] = value; return this; } 
	 
		/**
  * @type {string}
  * @description 
  **/
 body;
		/**
  * @returns {string}
  * @description 
  **/
getBody () { return this[`body`] }
		/**
  * @param {string}
  * @description 
  **/
setBody (value) { this[`body`] = value; return this; } 
	

	

	/** a placeholder for WebRequestX auto patching the json content to the object **/
	static __jsonParsable;

	
		/**
   * Nest.js decorator for controller headers. Instead of using @Headers() value: any, now you can use for example:
   * @example
   * @Get()
   * getHello(@SendEmailWithProviderReq.Nest() headers: SendEmailWithProviderReq): string {
   *  return JSON.stringify(headers.getContentType());
   * }
   */
  static Nest = createParamDecorator(
	(_data, ctx) => {
		// @ts-ignore
		const request = ctx.switchToHttp().getRequest();
		// @ts-ignore
		return new SendEmailWithProviderReq( request.body );
	},
  );


	
}













	
/**
  * @decription The base class definition for sendEmailWithProviderRes
  **/

export class SendEmailWithProviderRes {
	 
		/**
  * @type {string}
  * @description 
  **/
 queueId;
		/**
  * @returns {string}
  * @description 
  **/
getQueueId () { return this[`queueId`] }
		/**
  * @param {string}
  * @description 
  **/
setQueueId (value) { this[`queueId`] = value; return this; } 
	

	

	/** a placeholder for WebRequestX auto patching the json content to the object **/
	static __jsonParsable;

	
		/**
   * Nest.js decorator for controller headers. Instead of using @Headers() value: any, now you can use for example:
   * @example
   * @Get()
   * getHello(@SendEmailWithProviderRes.Nest() headers: SendEmailWithProviderRes): string {
   *  return JSON.stringify(headers.getContentType());
   * }
   */
  static Nest = createParamDecorator(
	(_data, ctx) => {
		// @ts-ignore
		const request = ctx.switchToHttp().getRequest();
		// @ts-ignore
		return new SendEmailWithProviderRes( request.body );
	},
  );


	
}








/**
 * SendEmailWithProviderHeaders class
 * Auto-generated from Module3Action
 */
export class SendEmailWithProviderHeaders extends Headers {

  // the getters generated by us would be casting types before returning.
  // you still can use .get function to get the string value.
  #getTyped(key, type) {
    const val = this.get(key);
    if (val == null) return null;

    const t = type.toLowerCase();

    if (t.includes('number')) return Number(val);
    if (t.includes('bool')) return val === 'true';
    return val; // string or any other fallback
  }


  /**
   * @returns {Record<string, string>}
   * Converts Headers to plain object
   */
  toObject() {
    return Object.fromEntries(this.entries());
  }

  
  /**
   * Nest.js decorator for controller headers. Instead of using @Headers() value: any, now you can use for example:
   * @example
   * @Get()
   * getHello(@SendEmailWithProviderHeaders.Nest() headers: SendEmailWithProviderHeaders): string {
   *  return JSON.stringify(headers.getContentType());
   * }
   */
  static Nest = createParamDecorator(
	(_data, ctx) => {
		// @ts-ignore
		const request = ctx.switchToHttp().getRequest();
		// @ts-ignore
		return new SendEmailWithProviderHeaders(Object.entries(request.headers));
	},
  );

  
}




/**
 * SendEmailWithProviderQueryParams class
 * Auto-generated from Module3Action
 */
export class SendEmailWithProviderQueryParams extends URLSearchParamsX {


  // the getters generated by us would be casting types before returning.
  // you still can use .get function to get the string value.
  #getTyped(key, type) {
    const val = this.get(key);
    if (val == null) return null;

    const t = type.toLowerCase();

    if (t.includes('number')) return Number(val);
    if (t.includes('bool')) return val === 'true';
    return val; // string or any other fallback
  }


  
  /**
   * Nest.js decorator for controller query. Instead of using @Query() value: any, now you can use for example:
   * @example
   * @Get()
   * getHello(@SendEmailWithProviderQueryParams.Nest() query: SendEmailWithProviderQueryParams): string {
   *  return JSON.stringify(query.getMyfield());
   * }
   */
  static Nest = createParamDecorator(
	(_data, ctx) => {
		// @ts-ignore
		const request = ctx.switchToHttp().getRequest();
		// @ts-ignore
		return new SendEmailWithProviderQueryParams(request.query);
	},
  );

  
}


 
