import { ExecutionContext, createParamDecorator } from '@nestjs/common';
import { fetchx } from 'INTERNAL_SDK_LOCATION';
/**
* Action to communicate with the action userPassports
*/


	/**
 * FetchUserPassportsAction
 */

export class FetchUserPassportsAction {
  static URL = '/user/passports';
  static Method = 'get';

  
  	static Axios = (clientInstance: AxiosInstance, config: AxiosRequestConfig<unknown>) =>
		clientInstance
		.requestrequest<unknown, AxiosResponse<unknown>, unknown>(config)

		
		.then((res) => {
			return {
			...res,

			
			// if there is a output class, create instance out of it.
			data: new UserPassportsRes(res.data),
			};
		});
		
	
  
  
	static Fetch = (
		init?: TypedRequestInit<unknown, unknown> | undefined,
		qs?: SignoutQueryParams,
		overrideUrl?: string
	) =>
		fetchx<unknown, unknown, unknown>(
			new URL((overrideUrl ?? FetchSignoutAction.URL) + '?' + qs?.toString()),
			init
		)

		
			.then((res) => res.json())
		

	
		
			.then((data) => new UserPassportsRes (data));
		

	
}











	
/**
  * @decription The base class definition for userPassportsRes
  **/

export class UserPassportsRes {
	 
		/**
  * @type {string}
  * @description The passport value, such as email address or phone number
  **/
 value;
		/**
  * @returns {string}
  * @description The passport value, such as email address or phone number
  **/
getValue () { return this[`value`] }
		/**
  * @param {string}
  * @description The passport value, such as email address or phone number
  **/
setValue (value) { this[`value`] = value; return this; } 
	 
		/**
  * @type {string}
  * @description Unique identifier of the passport to operate some action on top of it
  **/
 uniqueId;
		/**
  * @returns {string}
  * @description Unique identifier of the passport to operate some action on top of it
  **/
getUniqueId () { return this[`uniqueId`] }
		/**
  * @param {string}
  * @description Unique identifier of the passport to operate some action on top of it
  **/
setUniqueId (value) { this[`uniqueId`] = value; return this; } 
	 
		/**
  * @type {string}
  * @description The type of the passport, such as email, phone number
  **/
 type;
		/**
  * @returns {string}
  * @description The type of the passport, such as email, phone number
  **/
getType () { return this[`type`] }
		/**
  * @param {string}
  * @description The type of the passport, such as email, phone number
  **/
setType (value) { this[`type`] = value; return this; } 
	 
		/**
  * @type {boolean}
  * @description Regardless of the secret, user needs to confirm his secret. There is an extra action to confirm user totp, could be used after signup or prior to login.
  **/
 totpConfirmed;
		/**
  * @returns {boolean}
  * @description Regardless of the secret, user needs to confirm his secret. There is an extra action to confirm user totp, could be used after signup or prior to login.
  **/
getTotpConfirmed () { return this[`totpConfirmed`] }
		/**
  * @param {boolean}
  * @description Regardless of the secret, user needs to confirm his secret. There is an extra action to confirm user totp, could be used after signup or prior to login.
  **/
setTotpConfirmed (value) { this[`totpConfirmed`] = value; return this; } 
	

	

	/** a placeholder for WebRequestX auto patching the json content to the object **/
	static __jsonParsable;

	
		/**
   * Nest.js decorator for controller headers. Instead of using @Headers() value: any, now you can use for example:
   * @example
   * @Get()
   * getHello(@UserPassportsRes.Nest() headers: UserPassportsRes): string {
   *  return JSON.stringify(headers.getContentType());
   * }
   */
  static Nest = createParamDecorator(
	(_data, ctx) => {
		// @ts-ignore
		const request = ctx.switchToHttp().getRequest();
		// @ts-ignore
		return new UserPassportsRes( request.body );
	},
  );


	
}








/**
 * UserPassportsHeaders class
 * Auto-generated from Module3Action
 */
export class UserPassportsHeaders extends Headers {

  // the getters generated by us would be casting types before returning.
  // you still can use .get function to get the string value.
  #getTyped(key, type) {
    const val = this.get(key);
    if (val == null) return null;

    const t = type.toLowerCase();

    if (t.includes('number')) return Number(val);
    if (t.includes('bool')) return val === 'true';
    return val; // string or any other fallback
  }


  /**
   * @returns {Record<string, string>}
   * Converts Headers to plain object
   */
  toObject() {
    return Object.fromEntries(this.entries());
  }

  
  /**
   * Nest.js decorator for controller headers. Instead of using @Headers() value: any, now you can use for example:
   * @example
   * @Get()
   * getHello(@UserPassportsHeaders.Nest() headers: UserPassportsHeaders): string {
   *  return JSON.stringify(headers.getContentType());
   * }
   */
  static Nest = createParamDecorator(
	(_data, ctx) => {
		// @ts-ignore
		const request = ctx.switchToHttp().getRequest();
		// @ts-ignore
		return new UserPassportsHeaders(Object.entries(request.headers));
	},
  );

  
}




/**
 * UserPassportsQueryParams class
 * Auto-generated from Module3Action
 */
export class UserPassportsQueryParams extends URLSearchParamsX {


  // the getters generated by us would be casting types before returning.
  // you still can use .get function to get the string value.
  #getTyped(key, type) {
    const val = this.get(key);
    if (val == null) return null;

    const t = type.toLowerCase();

    if (t.includes('number')) return Number(val);
    if (t.includes('bool')) return val === 'true';
    return val; // string or any other fallback
  }


  
  /**
   * Nest.js decorator for controller query. Instead of using @Query() value: any, now you can use for example:
   * @example
   * @Get()
   * getHello(@UserPassportsQueryParams.Nest() query: UserPassportsQueryParams): string {
   *  return JSON.stringify(query.getMyfield());
   * }
   */
  static Nest = createParamDecorator(
	(_data, ctx) => {
		// @ts-ignore
		const request = ctx.switchToHttp().getRequest();
		// @ts-ignore
		return new UserPassportsQueryParams(request.query);
	},
  );

  
}


 
