import { useEmailProviderBrowseActionQuery } from "../sdk/messaging/EmailProviderBrowseAction";
import { type EmailProviderDto } from "../sdk/messaging/EmailProviderDto";

// Adapts useEmailProviderBrowseActionQuery (the generated per-action hook, returning a raw
// @tanstack/react-query result whose payload is the {data: {items, ...}} envelope)
// into the {query, items, keyExtractor} shape FormSelect/FormSelectMultiple's
// querySource prop expects. Replaces the old useGetEmailProviders hook (deleted along with the
// rest of the legacy "Generated by fireback 1.3.2" sdk/modules tree), which returned
// that shape directly.
export const useEmailProvidersQuerySource = () => {
  const query = useEmailProviderBrowseActionQuery({});
  const items = ((query.data as any)?.data?.items ?? []) as EmailProviderDto[];
  return {
    query: query as any,
    items,
    keyExtractor: (item: EmailProviderDto) => item.uniqueId,
  };
};
