/**
* Action to communicate with the action classicPassportRequestOtp
*/
 






	
/**
  * @decription The base class definition for classicPassportRequestOtpReq
  **/

export class ClassicPassportRequestOtpReq {
	 
		/**
  * @type {string}
  * @description Passport value (email, phone number) which would be recieving the otp code.
  **/
 value;
		/**
  * @returns {string}
  * @description Passport value (email, phone number) which would be recieving the otp code.
  **/
getValue () { return this[`value`] }
		/**
  * @param {string}
  * @description Passport value (email, phone number) which would be recieving the otp code.
  **/
setValue (value) { this[`value`] = value; return this; } 
	

	

	/** a placeholder for WebRequesX auto patching the json content to the object **/
	static __jsonParsable;
}













	
/**
  * @decription The base class definition for classicPassportRequestOtpRes
  **/

export class ClassicPassportRequestOtpRes {
	 
		/**
  * @type {number}
  * @description 
  **/
 suspendUntil;
		/**
  * @returns {number}
  * @description 
  **/
getSuspendUntil () { return this[`suspendUntil`] }
		/**
  * @param {number}
  * @description 
  **/
setSuspendUntil (value) { this[`suspendUntil`] = value; return this; } 
	 
		/**
  * @type {number}
  * @description 
  **/
 validUntil;
		/**
  * @returns {number}
  * @description 
  **/
getValidUntil () { return this[`validUntil`] }
		/**
  * @param {number}
  * @description 
  **/
setValidUntil (value) { this[`validUntil`] = value; return this; } 
	 
		/**
  * @type {number}
  * @description 
  **/
 blockedUntil;
		/**
  * @returns {number}
  * @description 
  **/
getBlockedUntil () { return this[`blockedUntil`] }
		/**
  * @param {number}
  * @description 
  **/
setBlockedUntil (value) { this[`blockedUntil`] = value; return this; } 
	 
		/**
  * @type {number}
  * @description The amount of time left to unblock for next request
  **/
 secondsToUnblock;
		/**
  * @returns {number}
  * @description The amount of time left to unblock for next request
  **/
getSecondsToUnblock () { return this[`secondsToUnblock`] }
		/**
  * @param {number}
  * @description The amount of time left to unblock for next request
  **/
setSecondsToUnblock (value) { this[`secondsToUnblock`] = value; return this; } 
	

	

	/** a placeholder for WebRequesX auto patching the json content to the object **/
	static __jsonParsable;
}








/**
 * ClassicPassportRequestOtpHeaders class
 * Auto-generated from Module3Action
 */
export class ClassicPassportRequestOtpHeaders extends Headers {

  // the getters generated by us would be casting types before returning.
  // you still can use .get function to get the string value.
  #getTyped(key, type) {
    const val = this.get(key);
    if (val == null) return null;

    const t = type.toLowerCase();

    if (t.includes('number')) return Number(val);
    if (t.includes('bool')) return val === 'true';
    return val; // string or any other fallback
  }


  /**
   * @returns {Record<string, string>}
   * Converts Headers to plain object
   */
  toObject() {
    return Object.fromEntries(this.entries());
  }

  
  /**
   * Nest.js decorator for controller headers. Instead of using @Headers() value: any, now you can use for example:
   * @example
   * @Get()
   * getHello(@FetchUserHeader.Nest() headers: FetchUserHeader): string {
   *  return JSON.stringify(headers.getContentType());
   * }
   */
  static Nest = createParamDecorator(
	(_data: unknown, ctx: ExecutionContext) => {
		// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
		const request = ctx.switchToHttp().getRequest();
		// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-argument, @typescript-eslint/no-unsafe-member-access
		return new ClassicPassportRequestOtpHeaders(Object.entries(request.headers));
	},
  );

  
}




/**
 * ClassicPassportRequestOtpQueryParams class
 * Auto-generated from Module3Action
 */
export class ClassicPassportRequestOtpQueryParams extends URLSearchParamsX {


  // the getters generated by us would be casting types before returning.
  // you still can use .get function to get the string value.
  #getTyped(key, type) {
    const val = this.get(key);
    if (val == null) return null;

    const t = type.toLowerCase();

    if (t.includes('number')) return Number(val);
    if (t.includes('bool')) return val === 'true';
    return val; // string or any other fallback
  }


  
  /**
   * Nest.js decorator for controller query. Instead of using @Query() value: any, now you can use for example:
   * @example
   * @Get()
   * getHello(@FetchUserQuery.Nest() query: FetchUserQuery): string {
   *  return JSON.stringify(query.getMyfield());
   * }
   */
  static Nest = createParamDecorator(
	(_data: unknown, ctx: ExecutionContext) => {
		// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
		const request = ctx.switchToHttp().getRequest();
		// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-argument, @typescript-eslint/no-unsafe-member-access
		return new ClassicPassportRequestOtpQueryParams(request.query);
	},
  );

  
}


 
