/**
* Action to communicate with the action queryWorkspaceTypesPublicly
*/
 








	
/**
  * @decription The base class definition for queryWorkspaceTypesPubliclyRes
  **/

export class QueryWorkspaceTypesPubliclyRes {
	 
		/**
  * @type {string}
  * @description 
  **/
 title;
		/**
  * @returns {string}
  * @description 
  **/
getTitle () { return this[`title`] }
		/**
  * @param {string}
  * @description 
  **/
setTitle (value) { this[`title`] = value; return this; } 
	 
		/**
  * @type {string}
  * @description 
  **/
 description;
		/**
  * @returns {string}
  * @description 
  **/
getDescription () { return this[`description`] }
		/**
  * @param {string}
  * @description 
  **/
setDescription (value) { this[`description`] = value; return this; } 
	 
		/**
  * @type {string}
  * @description 
  **/
 uniqueId;
		/**
  * @returns {string}
  * @description 
  **/
getUniqueId () { return this[`uniqueId`] }
		/**
  * @param {string}
  * @description 
  **/
setUniqueId (value) { this[`uniqueId`] = value; return this; } 
	 
		/**
  * @type {string}
  * @description 
  **/
 slug;
		/**
  * @returns {string}
  * @description 
  **/
getSlug () { return this[`slug`] }
		/**
  * @param {string}
  * @description 
  **/
setSlug (value) { this[`slug`] = value; return this; } 
	

	

	/** a placeholder for WebRequesX auto patching the json content to the object **/
	static __jsonParsable;
}








/**
 * QueryWorkspaceTypesPubliclyHeaders class
 * Auto-generated from Module3Action
 */
export class QueryWorkspaceTypesPubliclyHeaders extends Headers {

  // the getters generated by us would be casting types before returning.
  // you still can use .get function to get the string value.
  #getTyped(key, type) {
    const val = this.get(key);
    if (val == null) return null;

    const t = type.toLowerCase();

    if (t.includes('number')) return Number(val);
    if (t.includes('bool')) return val === 'true';
    return val; // string or any other fallback
  }


  /**
   * @returns {Record<string, string>}
   * Converts Headers to plain object
   */
  toObject() {
    return Object.fromEntries(this.entries());
  }

  
  /**
   * Nest.js decorator for controller headers. Instead of using @Headers() value: any, now you can use for example:
   * @example
   * @Get()
   * getHello(@FetchUserHeader.Nest() headers: FetchUserHeader): string {
   *  return JSON.stringify(headers.getContentType());
   * }
   */
  static Nest = createParamDecorator(
	(_data: unknown, ctx: ExecutionContext) => {
		// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
		const request = ctx.switchToHttp().getRequest();
		// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-argument, @typescript-eslint/no-unsafe-member-access
		return new QueryWorkspaceTypesPubliclyHeaders(Object.entries(request.headers));
	},
  );

  
}




/**
 * QueryWorkspaceTypesPubliclyQueryParams class
 * Auto-generated from Module3Action
 */
export class QueryWorkspaceTypesPubliclyQueryParams extends URLSearchParamsX {


  // the getters generated by us would be casting types before returning.
  // you still can use .get function to get the string value.
  #getTyped(key, type) {
    const val = this.get(key);
    if (val == null) return null;

    const t = type.toLowerCase();

    if (t.includes('number')) return Number(val);
    if (t.includes('bool')) return val === 'true';
    return val; // string or any other fallback
  }


  
  /**
   * Nest.js decorator for controller query. Instead of using @Query() value: any, now you can use for example:
   * @example
   * @Get()
   * getHello(@FetchUserQuery.Nest() query: FetchUserQuery): string {
   *  return JSON.stringify(query.getMyfield());
   * }
   */
  static Nest = createParamDecorator(
	(_data: unknown, ctx: ExecutionContext) => {
		// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
		const request = ctx.switchToHttp().getRequest();
		// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-argument, @typescript-eslint/no-unsafe-member-access
		return new QueryWorkspaceTypesPubliclyQueryParams(request.query);
	},
  );

  
}


 
