/**
* Action to communicate with the action sendEmailWithProvider
*/
 






	
/**
  * @decription The base class definition for sendEmailWithProviderReq
  **/

export class SendEmailWithProviderReq {
	 
		/**
  * @type {EmailProviderEntity}
  * @description 
  **/
 emailProvider;
		/**
  * @returns {EmailProviderEntity}
  * @description 
  **/
getEmailProvider () { return this[`emailProvider`] }
		/**
  * @param {EmailProviderEntity}
  * @description 
  **/
setEmailProvider (value) { this[`emailProvider`] = value; return this; } 
	 
		/**
  * @type {string}
  * @description 
  **/
 toAddress;
		/**
  * @returns {string}
  * @description 
  **/
getToAddress () { return this[`toAddress`] }
		/**
  * @param {string}
  * @description 
  **/
setToAddress (value) { this[`toAddress`] = value; return this; } 
	 
		/**
  * @type {string}
  * @description 
  **/
 body;
		/**
  * @returns {string}
  * @description 
  **/
getBody () { return this[`body`] }
		/**
  * @param {string}
  * @description 
  **/
setBody (value) { this[`body`] = value; return this; } 
	

	

	/** a placeholder for WebRequesX auto patching the json content to the object **/
	static __jsonParsable;
}













	
/**
  * @decription The base class definition for sendEmailWithProviderRes
  **/

export class SendEmailWithProviderRes {
	 
		/**
  * @type {string}
  * @description 
  **/
 queueId;
		/**
  * @returns {string}
  * @description 
  **/
getQueueId () { return this[`queueId`] }
		/**
  * @param {string}
  * @description 
  **/
setQueueId (value) { this[`queueId`] = value; return this; } 
	

	

	/** a placeholder for WebRequesX auto patching the json content to the object **/
	static __jsonParsable;
}








/**
 * SendEmailWithProviderHeaders class
 * Auto-generated from Module3Action
 */
export class SendEmailWithProviderHeaders extends Headers {

  // the getters generated by us would be casting types before returning.
  // you still can use .get function to get the string value.
  #getTyped(key, type) {
    const val = this.get(key);
    if (val == null) return null;

    const t = type.toLowerCase();

    if (t.includes('number')) return Number(val);
    if (t.includes('bool')) return val === 'true';
    return val; // string or any other fallback
  }


  /**
   * @returns {Record<string, string>}
   * Converts Headers to plain object
   */
  toObject() {
    return Object.fromEntries(this.entries());
  }

  
  /**
   * Nest.js decorator for controller headers. Instead of using @Headers() value: any, now you can use for example:
   * @example
   * @Get()
   * getHello(@FetchUserHeader.Nest() headers: FetchUserHeader): string {
   *  return JSON.stringify(headers.getContentType());
   * }
   */
  static Nest = createParamDecorator(
	(_data: unknown, ctx: ExecutionContext) => {
		// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
		const request = ctx.switchToHttp().getRequest();
		// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-argument, @typescript-eslint/no-unsafe-member-access
		return new SendEmailWithProviderHeaders(Object.entries(request.headers));
	},
  );

  
}




/**
 * SendEmailWithProviderQueryParams class
 * Auto-generated from Module3Action
 */
export class SendEmailWithProviderQueryParams extends URLSearchParamsX {


  // the getters generated by us would be casting types before returning.
  // you still can use .get function to get the string value.
  #getTyped(key, type) {
    const val = this.get(key);
    if (val == null) return null;

    const t = type.toLowerCase();

    if (t.includes('number')) return Number(val);
    if (t.includes('bool')) return val === 'true';
    return val; // string or any other fallback
  }


  
  /**
   * Nest.js decorator for controller query. Instead of using @Query() value: any, now you can use for example:
   * @example
   * @Get()
   * getHello(@FetchUserQuery.Nest() query: FetchUserQuery): string {
   *  return JSON.stringify(query.getMyfield());
   * }
   */
  static Nest = createParamDecorator(
	(_data: unknown, ctx: ExecutionContext) => {
		// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
		const request = ctx.switchToHttp().getRequest();
		// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-argument, @typescript-eslint/no-unsafe-member-access
		return new SendEmailWithProviderQueryParams(request.query);
	},
  );

  
}


 
