name: fireback-desktop
publicServer:
  enabled: true
  port: "61901"
  grpcPort: "619017"
  host: localhost
mqtt:
  connectTimeout: 100
  keepAlive: 90
  autoReconnect: true
  cleanSession: true
database:
  database: {appDataDirectory}fireback-desktop-database.db
  vendor: sqlite

gin:
  mode: production
headers:
  access-control-allow-origin: "*"
  access-control-allow-headers:
    Accept, Authorization, Content-Type, Content-Length,
    X-CSRF-Token, Token, session, Origin, Host, Connection, Accept-Encoding, Accept-Language,
    X-Requested-With, Workspace, Workspace-Id, deep, query, role-id, workspace-id
drive:
  storage: {appDataDirectory}storage
  port: "61900"
  enabled: true
