import { UserSessionDto } from "./UserSessionDto";
import { buildUrl } from "../../sdk/common/buildUrl";
import {
  fetchx,
  handleFetchResponse,
  type FetchxContext,
  type PartialDeep,
  type TypedRequestInit,
  type TypedResponse,
} from "../../sdk/common/fetchx";
import { type UseMutationOptions, useMutation } from "react-query";
import { useFetchxContext } from "../../sdk/react/useFetchx";
import { useState } from "react";
import { withPrefix } from "../../sdk/common/withPrefix";
/**
 * Action to communicate with the action ConfirmClassicPassportTotp
 */
export type ConfirmClassicPassportTotpActionOptions = {
  queryKey?: unknown[];
  qs?: URLSearchParams;
};
export type ConfirmClassicPassportTotpActionMutationOptions = Omit<
  UseMutationOptions<unknown, unknown, unknown, unknown>,
  "mutationFn"
> &
  ConfirmClassicPassportTotpActionOptions & {
    ctx?: FetchxContext;
    onMessage?: (ev: MessageEvent) => void;
    overrideUrl?: string;
    headers?: Headers;
  } & Partial<{
    creatorFn: (item: unknown) => ConfirmClassicPassportTotpActionRes;
  }>;
export const useConfirmClassicPassportTotpAction = (
  options?: ConfirmClassicPassportTotpActionMutationOptions,
) => {
  const globalCtx = useFetchxContext();
  const ctx = options?.ctx ?? globalCtx ?? undefined;
  const [isCompleted, setCompleteState] = useState(false);
  const [response, setResponse] = useState<TypedResponse<unknown>>();
  const fn = (body: ConfirmClassicPassportTotpActionReq) => {
    setCompleteState(false);
    return ConfirmClassicPassportTotpAction.Fetch(
      {
        body,
        headers: options?.headers,
      },
      {
        creatorFn: options?.creatorFn,
        qs: options?.qs,
        ctx,
        onMessage: options?.onMessage,
        overrideUrl: options?.overrideUrl,
      },
    ).then((x) => {
      x.done.then(() => {
        setCompleteState(true);
      });
      setResponse(x.response);
      return x.response.result;
    });
  };
  const result = useMutation({
    mutationFn: fn,
    ...(options || {}),
  });
  return {
    ...result,
    isCompleted,
    response,
  };
};
/**
 * ConfirmClassicPassportTotpAction
 */
export class ConfirmClassicPassportTotpAction {
  //
  static URL = "/passport/totp/confirm";
  static NewUrl = (qs?: URLSearchParams) =>
    buildUrl(ConfirmClassicPassportTotpAction.URL, undefined, qs);
  static Method = "post";
  static Fetch$ = async (
    qs?: URLSearchParams,
    ctx?: FetchxContext,
    init?: TypedRequestInit<ConfirmClassicPassportTotpActionReq, unknown>,
    overrideUrl?: string,
  ) => {
    return fetchx<
      ConfirmClassicPassportTotpActionRes,
      ConfirmClassicPassportTotpActionReq,
      unknown
    >(
      overrideUrl ?? ConfirmClassicPassportTotpAction.NewUrl(qs),
      {
        method: ConfirmClassicPassportTotpAction.Method,
        ...(init || {}),
      },
      ctx,
    );
  };
  static Fetch = async (
    init?: TypedRequestInit<ConfirmClassicPassportTotpActionReq, unknown>,
    {
      creatorFn,
      qs,
      ctx,
      onMessage,
      overrideUrl,
    }: {
      creatorFn?:
        | ((item: unknown) => ConfirmClassicPassportTotpActionRes)
        | undefined;
      qs?: URLSearchParams;
      ctx?: FetchxContext;
      onMessage?: (ev: MessageEvent) => void;
      overrideUrl?: string;
    } = {
      creatorFn: (item) => new ConfirmClassicPassportTotpActionRes(item),
    },
  ) => {
    creatorFn =
      creatorFn || ((item) => new ConfirmClassicPassportTotpActionRes(item));
    const res = await ConfirmClassicPassportTotpAction.Fetch$(
      qs,
      ctx,
      init,
      overrideUrl,
    );
    return handleFetchResponse(
      res,
      (item) => (creatorFn ? creatorFn(item) : item),
      onMessage,
      init?.signal,
    );
  };
  static Definition = {
    name: "ConfirmClassicPassportTotp",
    url: "/passport/totp/confirm",
    method: "post",
    description:
      "When user requires to setup the totp for an specifc passport, they can use this endpoint to confirm it.",
    in: {
      fields: [
        {
          name: "value",
          description:
            "Passport value, email or phone number which is already successfully registered.",
          type: "string",
          tags: {
            validate: "required",
          },
        },
        {
          name: "password",
          description:
            "Password related to the passport. Totp is only available for passports with a password. Basically totp is protecting passport, not otp over email or sms.",
          type: "string",
          tags: {
            validate: "required",
          },
        },
        {
          name: "totpCode",
          description:
            "The totp code generated by authenticator such as google or microsft apps.",
          type: "string",
          tags: {
            validate: "required",
          },
        },
      ],
    },
    out: {
      fields: [
        {
          name: "session",
          type: "one",
          target: "UserSessionDto",
        },
      ],
    },
  };
}
/**
 * The base class definition for confirmClassicPassportTotpActionReq
 **/
export class ConfirmClassicPassportTotpActionReq {
  /**
   * Passport value, email or phone number which is already successfully registered.
   * @type {string}
   **/
  #value: string = "";
  /**
   * Passport value, email or phone number which is already successfully registered.
   * @returns {string}
   **/
  get value() {
    return this.#value;
  }
  /**
   * Passport value, email or phone number which is already successfully registered.
   * @type {string}
   **/
  set value(value: string) {
    this.#value = String(value);
  }
  setValue(value: string) {
    this.value = value;
    return this;
  }
  /**
   * Password related to the passport. Totp is only available for passports with a password. Basically totp is protecting passport, not otp over email or sms.
   * @type {string}
   **/
  #password: string = "";
  /**
   * Password related to the passport. Totp is only available for passports with a password. Basically totp is protecting passport, not otp over email or sms.
   * @returns {string}
   **/
  get password() {
    return this.#password;
  }
  /**
   * Password related to the passport. Totp is only available for passports with a password. Basically totp is protecting passport, not otp over email or sms.
   * @type {string}
   **/
  set password(value: string) {
    this.#password = String(value);
  }
  setPassword(value: string) {
    this.password = value;
    return this;
  }
  /**
   * The totp code generated by authenticator such as google or microsft apps.
   * @type {string}
   **/
  #totpCode: string = "";
  /**
   * The totp code generated by authenticator such as google or microsft apps.
   * @returns {string}
   **/
  get totpCode() {
    return this.#totpCode;
  }
  /**
   * The totp code generated by authenticator such as google or microsft apps.
   * @type {string}
   **/
  set totpCode(value: string) {
    this.#totpCode = String(value);
  }
  setTotpCode(value: string) {
    this.totpCode = value;
    return this;
  }
  constructor(data: unknown = undefined) {
    if (data === null || data === undefined) {
      return;
    }
    if (typeof data === "string") {
      this.applyFromObject(JSON.parse(data));
    } else if (this.#isJsonAppliable(data)) {
      this.applyFromObject(data);
    } else {
      throw new Error(
        "Instance cannot be created on an unknown value, check the content being passed. got: " +
          typeof data,
      );
    }
  }
  #isJsonAppliable(obj: unknown) {
    const g = globalThis as unknown as { Buffer: any; Blob: any };
    const isBuffer =
      typeof g.Buffer !== "undefined" &&
      typeof g.Buffer.isBuffer === "function" &&
      g.Buffer.isBuffer(obj);
    const isBlob = typeof g.Blob !== "undefined" && obj instanceof g.Blob;
    return (
      obj &&
      typeof obj === "object" &&
      !Array.isArray(obj) &&
      !isBuffer &&
      !(obj instanceof ArrayBuffer) &&
      !isBlob
    );
  }
  /**
   * casts the fields of a javascript object into the class properties one by one
   **/
  applyFromObject(data = {}) {
    const d = data as Partial<ConfirmClassicPassportTotpActionReq>;
    if (d.value !== undefined) {
      this.value = d.value;
    }
    if (d.password !== undefined) {
      this.password = d.password;
    }
    if (d.totpCode !== undefined) {
      this.totpCode = d.totpCode;
    }
  }
  /**
   *	Special toJSON override, since the field are private,
   *	Json stringify won't see them unless we mention it explicitly.
   **/
  toJSON() {
    return {
      value: this.#value,
      password: this.#password,
      totpCode: this.#totpCode,
    };
  }
  toString() {
    return JSON.stringify(this);
  }
  static get Fields() {
    return {
      value: "value",
      password: "password",
      totpCode: "totpCode",
    };
  }
  /**
   * Creates an instance of ConfirmClassicPassportTotpActionReq, and possibleDtoObject
   * needs to satisfy the type requirement fully, otherwise typescript compile would
   * be complaining.
   **/
  static from(possibleDtoObject: ConfirmClassicPassportTotpActionReqType) {
    return new ConfirmClassicPassportTotpActionReq(possibleDtoObject);
  }
  /**
   * Creates an instance of ConfirmClassicPassportTotpActionReq, and partialDtoObject
   * needs to satisfy the type, but partially, and rest of the content would
   * be constructed according to data types and nullability.
   **/
  static with(
    partialDtoObject: PartialDeep<ConfirmClassicPassportTotpActionReqType>,
  ) {
    return new ConfirmClassicPassportTotpActionReq(partialDtoObject);
  }
  copyWith(
    partial: PartialDeep<ConfirmClassicPassportTotpActionReqType>,
  ): InstanceType<typeof ConfirmClassicPassportTotpActionReq> {
    return new ConfirmClassicPassportTotpActionReq({
      ...this.toJSON(),
      ...partial,
    });
  }
  clone(): InstanceType<typeof ConfirmClassicPassportTotpActionReq> {
    return new ConfirmClassicPassportTotpActionReq(this.toJSON());
  }
}
export abstract class ConfirmClassicPassportTotpActionReqFactory {
  abstract create(data: unknown): ConfirmClassicPassportTotpActionReq;
}
/**
 * The base type definition for confirmClassicPassportTotpActionReq
 **/
export type ConfirmClassicPassportTotpActionReqType = {
  /**
   * Passport value, email or phone number which is already successfully registered.
   * @type {string}
   **/
  value: string;
  /**
   * Password related to the passport. Totp is only available for passports with a password. Basically totp is protecting passport, not otp over email or sms.
   * @type {string}
   **/
  password: string;
  /**
   * The totp code generated by authenticator such as google or microsft apps.
   * @type {string}
   **/
  totpCode: string;
};
// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace ConfirmClassicPassportTotpActionReqType {}
/**
 * The base class definition for confirmClassicPassportTotpActionRes
 **/
export class ConfirmClassicPassportTotpActionRes {
  /**
   *
   * @type {UserSessionDto}
   **/
  #session!: UserSessionDto;
  /**
   *
   * @returns {UserSessionDto}
   **/
  get session() {
    return this.#session;
  }
  /**
   *
   * @type {UserSessionDto}
   **/
  set session(value: UserSessionDto) {
    // For objects, the sub type needs to always be instance of the sub class.
    if (value instanceof UserSessionDto) {
      this.#session = value;
    } else {
      this.#session = new UserSessionDto(value);
    }
  }
  setSession(value: UserSessionDto) {
    this.session = value;
    return this;
  }
  constructor(data: unknown = undefined) {
    if (data === null || data === undefined) {
      this.#lateInitFields();
      return;
    }
    if (typeof data === "string") {
      this.applyFromObject(JSON.parse(data));
    } else if (this.#isJsonAppliable(data)) {
      this.applyFromObject(data);
    } else {
      throw new Error(
        "Instance cannot be created on an unknown value, check the content being passed. got: " +
          typeof data,
      );
    }
  }
  #isJsonAppliable(obj: unknown) {
    const g = globalThis as unknown as { Buffer: any; Blob: any };
    const isBuffer =
      typeof g.Buffer !== "undefined" &&
      typeof g.Buffer.isBuffer === "function" &&
      g.Buffer.isBuffer(obj);
    const isBlob = typeof g.Blob !== "undefined" && obj instanceof g.Blob;
    return (
      obj &&
      typeof obj === "object" &&
      !Array.isArray(obj) &&
      !isBuffer &&
      !(obj instanceof ArrayBuffer) &&
      !isBlob
    );
  }
  /**
   * casts the fields of a javascript object into the class properties one by one
   **/
  applyFromObject(data = {}) {
    const d = data as Partial<ConfirmClassicPassportTotpActionRes>;
    if (d.session !== undefined) {
      this.session = d.session;
    }
    this.#lateInitFields(data);
  }
  /**
   * These are the class instances, which need to be initialised, regardless of the constructor incoming data
   **/
  #lateInitFields(data = {}) {
    const d = data as Partial<ConfirmClassicPassportTotpActionRes>;
    if (!(d.session instanceof UserSessionDto)) {
      this.session = new UserSessionDto(d.session || {});
    }
  }
  /**
   *	Special toJSON override, since the field are private,
   *	Json stringify won't see them unless we mention it explicitly.
   **/
  toJSON() {
    return {
      session: this.#session,
    };
  }
  toString() {
    return JSON.stringify(this);
  }
  static get Fields() {
    return {
      session$: "session",
      get session() {
        return withPrefix("session", UserSessionDto.Fields);
      },
    };
  }
  /**
   * Creates an instance of ConfirmClassicPassportTotpActionRes, and possibleDtoObject
   * needs to satisfy the type requirement fully, otherwise typescript compile would
   * be complaining.
   **/
  static from(possibleDtoObject: ConfirmClassicPassportTotpActionResType) {
    return new ConfirmClassicPassportTotpActionRes(possibleDtoObject);
  }
  /**
   * Creates an instance of ConfirmClassicPassportTotpActionRes, and partialDtoObject
   * needs to satisfy the type, but partially, and rest of the content would
   * be constructed according to data types and nullability.
   **/
  static with(
    partialDtoObject: PartialDeep<ConfirmClassicPassportTotpActionResType>,
  ) {
    return new ConfirmClassicPassportTotpActionRes(partialDtoObject);
  }
  copyWith(
    partial: PartialDeep<ConfirmClassicPassportTotpActionResType>,
  ): InstanceType<typeof ConfirmClassicPassportTotpActionRes> {
    return new ConfirmClassicPassportTotpActionRes({
      ...this.toJSON(),
      ...partial,
    });
  }
  clone(): InstanceType<typeof ConfirmClassicPassportTotpActionRes> {
    return new ConfirmClassicPassportTotpActionRes(this.toJSON());
  }
}
export abstract class ConfirmClassicPassportTotpActionResFactory {
  abstract create(data: unknown): ConfirmClassicPassportTotpActionRes;
}
/**
 * The base type definition for confirmClassicPassportTotpActionRes
 **/
export type ConfirmClassicPassportTotpActionResType = {
  /**
   *
   * @type {UserSessionDto}
   **/
  session: UserSessionDto;
};
// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace ConfirmClassicPassportTotpActionResType {}
